### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by c9777777** [OfficeDev/office-js-docs-pr#1056]
What permissions are required to use centralized deployment I.E. this feature here

https://docs.microsoft.com/en-us/office/dev/add-ins/publish/centralized-deployment

Thanks

**Comment by kbrandl** [comment]
@c9777777 thanks for your interest in Office Add-ins, and for reaching out with this question. You must be an O365 admin for your organization in order to use centralized deployment to deploy Office Add-ins to users within your organization. Additional information about requirements for using centralized deployment can be found in [Determine if Centralized Deployment of add-ins works for your organization](https://docs.microsoft.com/en-us/office365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide).
