### ISSUE TITLE
There's no way to remove a sideloaded add-in on web or windows

### ISSUE THREAD

**Issue by jasonqsong** [OfficeDev/office-js-docs-pr#1137]
In office 365 word web app, after manually uploading the manifest.xml file, the button stick on the ribbon menu and the add-in doesn't shown in the my-addins page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ab35128-1e97-c6ad-babc-f696f2e7b0fe
* Version Independent ID: cd1bacb1-14d7-a38d-321c-ebc2a526e03b
* Content: [Sideload Office Add-ins in Office on the web for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing#feedback)
* Content Source: [docs/testing/sideload-office-add-ins-for-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/sideload-office-add-ins-for-testing.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by jasonqsong** [comment]
On Web:

![image](https://user-images.githubusercontent.com/6178947/60190223-e35a2c80-9864-11e9-81f9-0d434e895f6b.png)

![image](https://user-images.githubusercontent.com/6178947/60190294-fec53780-9864-11e9-9e91-0b7c45e68c67.png)

On Windows:

![image](https://user-images.githubusercontent.com/6178947/60190345-113f7100-9865-11e9-8530-84b9f8a087d1.png)

**Comment by Rick-Kirkham** [comment]
It is normal for sideloaded add-ins to not appear in the MY ADD-INS tab. 
This repo is used to track errors in the documentation. For technical puzzles like this, please raise the issue on Stack Overflow and be sure to tag it `office-js`. This will help the whole community benefit from the answers that you get.

**Comment by andrewkittredge** [comment]
This is not a technical puzzle, there is no documented way to uninstall sideloaded add-in.

**Comment by nilswloewen** [comment]
I cannot find any answers to this on stackoverflow either. @andrewkittredge has a legit concern here.

**Comment by AlexJerabek** [comment]
Hi @andrewkittredge and @nilswloewen,

To remove sideloaded add-ins, you'll need to clear the Office cache. The instructions on how to do this are in [this article](https://docs.microsoft.com/office/dev/add-ins/testing/clear-cache). Please let me know if that solves your ribbon overcrowding.

I'm going reorganize and rename some articles to make this solution more clear. I'll reopen this issue to track that work.

**Comment by nilswloewen** [comment]
That solves it, thank you for the help.

**Comment by mikehearn** [comment]
The article is helpful for the desktop apps, but doesn't say what to do about the web. I've installed an add-in into Excel via the upload path, and now there seems to be no way to get rid of it. Every new document now has my add-in, and because at some point I had to alter the manifest I re-uploaded it, and now it's there twice! 

Can you please document how to clear the uploaded add-ins for Excel for Web? (I'm assuming here, that there actually is a way to do it).

**Comment by mikehearn** [comment]
For anyone else who finds this, it turns out that it actually is documented, but not in the "clear office caches" section of the site. On the web the office cache is just the browser cache.

*NB:* Clearing "cached files" is not sufficient. I tried that at first and it didn't work. In Chrome, there doesn't seem to be any way to clear individual sites anymore, so you'll have to clear out everything from within the time range in which you installed the add-in. Then restart Chrome. Then delete the workbooks you uploaded it to (I think?). Then you should be free of the add-in.

**Comment by AlexJerabek** [comment]
Thanks for sharing your experience @mikehearn. We'll use your comments to improve the documentation and make the information about clearing the browser cache more clear. 
@alison-mk, can you please create a follow-up item and look into these improvements?

**Comment by alison-mk** [comment]
@AlexJerabek Sure thing. I've created an internal work item to track these improvement suggestions: [Link to internal work item](https://office.visualstudio.com/OC/_workitems/edit/4924870).
