### ISSUE TITLE
Browser control for Office AddIns

### ISSUE THREAD

**Issue by rohitrewa** [OfficeDev/office-js-docs-pr#1192]
Any plans for moving to better browser control inside office apps for AddIns. Currently, Office Apps in desktop uses IE and it being less performant degrades the user experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42faa32c-446b-0209-4a24-9a29b4921ea1
* Version Independent ID: a5f0fc77-a881-df1e-1f49-aa0e555022e0
* Content: [Office Add-ins platform overview - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins)
* Content Source: [docs/overview/office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/overview/office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Dalgam** [comment]
On the current previews on Windows 10/Office, the add-ins are using Edge instead of IE11 so there is work being done there. https://developer.microsoft.com/en-us/office/blogs/microsoft-edge-webview-for-office-add-ins/

**Comment by kbrandl** [comment]
@rohitrewa thanks for your interest in Office Add-ins development, and for providing this feedback. As @Dalgam has pointed out, newer versions of Windows 10/Office are now using Microsoft Edge instead of IE, as described on the [Office Developer blog](https://developer.microsoft.com/en-us/office/blogs/microsoft-edge-webview-for-office-add-ins). You can find more details about the browsers used by Office Add-ins in the docs as well: https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins. As things continue to evolve in the days ahead, we'll be making announcements via the Office Developer Blog and will be keeping that article in the docs current as well.
