### ISSUE TITLE
error: catch(errorHandlerFunction); not define 

### ISSUE THREAD

**Issue by TheGridLock** [OfficeDev/office-js-docs-pr#1211]

**Comment by TheGridLock** [comment]
when i test office addin by visual studio 2019 with excel 2019
this my function: 
Excel.run(function (context) {
            var sheet = context.workbook.worksheets.getItem("Sheet1");
            var data = [
                ["Potato Chips", 10, 1.80],
            ];
            var range = sheet.getRange("B5:D5");
            range.values = data;
            range.format.autofitColumns();

            return context.sync();
        }).catch(errorHandlerFunction);
----------------------------------------------
but when run this code.i get error above.how i can edit this.
Thanks you!

**Comment by kbrandl** [comment]
The code within the `catch()` specifies the code that will run when any error is thrown by the preceding code. In the example code that you copied from the docs, the `errorHandlerFunction` text inside of the `catch()` is simply a placeholder value that's intended to represent the name of the function that contains error handling logic/code -- i.e., the name of the function that should run whenever an error is caught by the `catch()`. I'd suspect that the "undefined" error is occurring because your code doesn't contain a function called `errorHandlerFunction`. You can either create an error handling function that's named the same as the function name referenced inside the `catch()` or include error handling logic inside the catch itself (instead of within a separate function).  

Hope this helps. If you have additional 'how to' programming questions about using the Office JavaScript APIs, please post your question(s) to Stack Overflow (tagged with [office-js](https://stackoverflow.com/questions/tagged/office-js)), as that's the best place to get help with questions like this. Thanks!

**Comment by TheGridLock** [comment]
too clear and detailed
Thanks for your explanation, kbrandl !
