### ISSUE TITLE
Application does not run on HTTPS following provided instructions

### ISSUE THREAD

**Issue by mclean25** [OfficeDev/office-js-docs-pr#1278]
I followed all of the instructions to create a an [office task bar with vue](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-vue), but I can't get my server to run on https:

`λ npm run dev`
` Your application is running here: http://localhost:8080`

This is my `scripts in ./package.json`:
```
  "scripts": {
    "dev": "webpack-dev-server --https --inline --progress --config build/webpack.dev.conf.js",
    "start": "npm run dev",
    "build": "node build/build.js"
  },
```

Additionally, if I try going to http://localhost:8080 it says I don't have a certificate, which makes sense I suppose but nothing in the "[solution](https://github.com/OfficeDev/generator-office/blob/master/src/docs/ssl.md)" for this works for me. I don't get a prompt from `yo` to install a certificate.

### Versions:
I'm using Windows 10

```
λ npm list -g vue-cli yo generator-office
+-- generator-office@1.3.0
+-- vue-cli@2.9.6
-- yo@3.1.0
```

**Comment by kbrandl** [comment]
@AlexJerabek FYI, assigning this one to you (since it's related to PR #1243 which updates the Vue quick start). Thanks!

**Comment by mclean25** [comment]
Thanks for the detail @kbrandl. I've resorted to using the React template which was smooth sailing and was up and running in no time as I'm just exploring at this point in time. Look forward to the PR for Vue though as I believe that's what my team will want to use in the end.

**Comment by AlexJerabek** [comment]
Hi @mclean25,
The Vue quick start has been updated with PR https://github.com/OfficeDev/office-js-docs-pr/pull/1243. Those changes will be pushed to live soon.
Whenever you are able, could you confirm the updated Vue quick start addresses your concerns? Thanks!

**Comment by kbrandl** [comment]
@mclean25 glad to hear that you had a better experience with the React quick start -- thanks for letting us know! Per @AlexJerabek's comment above, the updated [Vue quick start](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-vue) should be published later this week (most likely tomorrow - Tuesday). You'll know when that's happened, because the date that appears directly below the article title will be recent than it currently is:

![image](https://user-images.githubusercontent.com/3019529/64196807-7e5d1d00-ce39-11e9-9135-29ee9d15af8e.png)

If possible, please do give that a run through after it's been updated, and let us know if it resolves the certificate-related issue you reported here. Thanks!

**Comment by mclean25** [comment]
@kbrandl @AlexJerabek  Sounds good, I'll go over it tomorrow (assuming you mean Wednesday ;) ) and will let you know how it goes.

**Comment by kbrandl** [comment]
@mclean25 ah yes -- the holiday threw me off -- today is *already* Tuesday, so doc updates will be published later today :)

**Comment by mclean25** [comment]
New docs work, thank you!
