### ISSUE TITLE
OnChanged Event Undocumented Change in Behavior

### ISSUE THREAD

**Issue by david-ps** [OfficeDev/office-js-docs-pr#1303]
The [OnChanged](https://docs.microsoft.com/en-au/javascript/api/excel/excel.table?view=excel-js-preview#onchanged) event returns a new Change Type "RowInserted" in version API 1.9 Version 1908. This was not included in API 1.8
## Article URL
[OnChanged](https://docs.microsoft.com/en-au/javascript/api/excel/excel.table?view=excel-js-preview#onchanged)
## Issue
This not documented and we do not know how to receive notifications about changes like this  and as result the application failed.

**Comment by AlexJerabek** [comment]
Hi @david-ps,

I'm sorry to hear your application is failing as a result of this change. Just to clarify, is the issue that [DataChangeType](https://docs.microsoft.com/en-au/javascript/api/excel/excel.datachangetype?view=excel-js-preview) does not specify the requirement sets in which the change event types were added? Or is it that adding an enum value to the enum caused the issues?

**Comment by AlexJerabek** [comment]
Also tagging @lumine2008 for help track down API requirement sets for the [DataChangeType](https://docs.microsoft.com/javascript/api/excel/excel.datachangetype?view=excel-js-preview) values. Let's sync up to properly document this API.

**Comment by david-ps** [comment]
@AlexJerabek Both. It was not specified in what requirement set the changes to DataChangeType change event types were added, there was no release log or prior notification and, adding an enum value to the enum caused the failure. Coincidently the new functionality seems to be related to a [serious bug](https://github.com/OfficeDev/office-js/issues/728) we have raised and are awaiting advice.

**Comment by AlexJerabek** [comment]
Thanks @david-ps. I'll work with the product team to get the enum requirement sets properly documented. https://github.com/OfficeDev/office-js/issues/728 will track the underlying product bug.

**Comment by ElizabethSamuel-MSFT** [comment]
@AlexJerabek Any update on this? Thanks.

**Comment by AlexJerabek** [comment]
@ElizabethSamuel-MSFT Not yet. I've pinged the product team for an update on their end.

**Comment by AlexJerabek** [comment]
Hi @david-ps, 

The product team dug into the build history regarding these changes. It appears all of the [DataChangeTypes](https://docs.microsoft.com/en-au/javascript/api/excel/excel.datachangetype?view=excel-js-preview) were added as part of ExcelApi 1.7 except for "Unknown". "Unknown" was added in 1.8 and replaced "Others", which only existed for 1.7. Documenting this change is tracked as [this internal bug](https://office.visualstudio.com/OC/_workitems/edit/3746143).

Since the documentation for "RowInserted" as accurate, I'll close this issue. I'm following [your related iusse](https://github.com/OfficeDev/office-js/issues/728), since there are documentation updates that will arise from that.

On a more meta note, we will look into adding better channels to communicate behavior changes, should a situation like this happen again. Thank you pointing out that gap.
