### ISSUE TITLE
Yeoman, npm install errors registry

### ISSUE THREAD

**Issue by Dilema-s** [OfficeDev/office-js-docs-pr#1321]
> office-addin-debugging start manifest.xml

Debugging is being started...
App type: desktop
Enabled debugging for add-in c1cdb1cd-e1cf-4386-ba6c-83a4c8888bf6. Debug method: 0
Starting the dev server... (webpack-dev-server --mode development)
The dev server is running on port 3000. Process id: 2768
Sideloading the Office Add-in...
Error: Unable to start debugging.
Error: Unable to sideload the Office Add-in.
Error: Unable to delete registry value "C:\Users\Mati Ferrero\Simular+\manifest.xml" in key "HKCU\SOFTWARE\Microsoft\Office\16.0\Wef\Developer".
ProcessUncleanExitError: DELETE command exited with code 1:

ERROR: El sistema no ha podido encontrar la clave o el valor del Registro
especificados.
 
CC: https://stackoverflow.com/questions/57833613/yeoman-npm-install-errors-registry

**Comment by AlexJerabek** [comment]
Hi @Dilema-s, 
Thanks for reporting this issue. @akrantz, do you have any insight into this yo office error message?

**Comment by akrantz** [comment]
Yes, this issue was fixed. https://github.com/OfficeDev/Office-Addin-Scripts/issues/215

Please get the latest version of office-addin-debugging. 

There are a couple of ways to do this.
1. `npm update --dev` can update all packages according to semver. (You can see outdated packages using `npm outdated --long`.)
2. You could update office-addin-debugging package using `npm install -D office-addin-debugging`.

**Comment by Dilema-s** [comment]
Great, thanks!!

**Comment by kbrandl** [comment]
Closing this issue as "fixed", per @akrantz's [comment](https://github.com/OfficeDev/office-js-docs-pr/issues/1321#issuecomment-533753343). @Dilema-s please feel free to reach out again if you need further assistance. Thanks!
