### ISSUE TITLE
IEChooser.exe tool cannot display the target for debugging / Office 2019

### ISSUE THREAD

**Issue by jrpally** [OfficeDev/office-js-docs-pr#1346]
## Description

I can run IEChooser.exe to debug Addins at Office 2017, worked perfectly but now I am having issues to debug at Office 2019 windows home edition

## Issue

IEChooser can't pick the web browser for embedded addins on office 2019

**Comment by Rick-Kirkham** [comment]
Are you using the subscription Office or the perpetual license Office? If it is subscription, then you computer might be using Edge instead of IE to host the add-in. See [Browsers used by Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins). In that case, you can't use IEChooser. You should use [Edge Developer Tools Preview](https://www.microsoft.com/en-us/p/microsoft-edge-devtools-preview/9mzbfrmz0mnj?activetab=pivot:overviewtab).

**Comment by Rick-Kirkham** [comment]
Original poster marked my answer thumbs up, so I'm closing this.
