### ISSUE TITLE
Add tags to disable caching of Home.html

### ISSUE THREAD

**Issue by LevDev1** [OfficeDev/office-js-docs-pr#1393]
While going through the tutorial I had problems with the new HTML elements not appearing across builds and then magically appearing the next day without any changes. Having researched this I find that with recent versions of Office (1910 - 12130.20238) and Windows (1909 - 18363.418) the Office clients when running add-ins will use the Edge WebViewHost to display the HTML that has a different caching behaviour as IE before.

Adding the following meta tag to Home.html has fixed this behaviour going forward:

```HTML
<meta http-equiv="Pragma" content="no-cache" />
```
Of course as there already was a cached version of the file without the tag I would have needed to wait until that expired but the command line recommended by user ndee here on StackOverflow (see latest reply added on 25/10/2019) has helped to clear the WebViewHost cache and get me going: https://stackoverflow.com/questions/57909922/office-js-addin-with-excel-and-edge-webview-how-to-delete-cache

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18abb533-5be7-d533-8106-c52d458ddc1d
* Version Independent ID: 6af81176-d832-d3d5-5060-5218b2ba75ac
* Content: [PowerPoint add-in tutorial - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/powerpoint-tutorial)
* Content Source: [docs/tutorials/powerpoint-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/tutorials/powerpoint-tutorial.md)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by LevDev1** [comment]
This needs to be done for the home.js file too - still looking for the best way to do that. The command line cache deletion keeps me going until I find that.

**Comment by kbrandl** [comment]
@LevDev1 thanks for the feedback about this. I've reassigned this issue to @Rick-Kirkham, since he was the person who engaged on the Stack Overflow thread you've linked to, and therefore has more context about this topic. @Rick-Kirkham -- FWIW, IMO, seems like this type of information belongs with the [other caching-related info in the docs](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest#clear-the-office-cache), rather than in the PowerPoint tutorial where this issue was logged.

**Comment by Rick-Kirkham** [comment]
Fixed by PR 1421.
