### ISSUE TITLE
Breakpoints are not hit; there are no details on how to enable this

### ISSUE THREAD

**Issue by Pher0ah** [OfficeDev/office-js-docs-pr#1438]
Problem URL: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-and-debug-office-add-ins-in-visual-studio#debug-the-code-for-an-excel-powerpoint-or-word-add-in

Issue: Following the steps to enable the add-in in word and having a breakpoint in VisualStudio; the breakpoint does not trigger and there is a message in VisualStudio saying:

"The breakpoint will not currently be hit. No symbols have been loaded for this document"

The breakpoint is in the functionfile.js file that was created by the VisualStudio wizard. The function with the breakpoint does run because I can see results; just the breakpoint is not honoured. 

Please correct this in the documentation to explain how to get breakpoints to work.

**Comment by ElizabethSamuel-MSFT** [comment]
@Pher0ah Thanks for raising this issue. We'll work on getting this sorted out.

@davidchesnut Is this something you can look into or help with? Thanks.

**Comment by slabereemsft** [comment]
@nokafor - Is this the same as the Edge debugging issue?

**Comment by davidchesnut** [comment]
Hi @Pher0ah 

Can you provide which version of Visual Studio and which version of Office desktop you are using? This will help us look into this a bit more.

I have seen this problem once and it turned out to be a caching issue that caused the debugger to not be able to connect properly. You can clear the cache by following steps in this [article](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest#clear-the-office-cache).

Also if you can create a new add-in project in Visual Studio, and the breakpoints start working in that project, it is likely a caching issue.

Thanks!
David

**Comment by Pher0ah** [comment]
Hi @davidchesnut 

No, it is not a caching issue, as creating a new project has the exact same issue. If I run a virgin project and add a bookmark to the task pane that is there by default, the breakpoint works. Any new code I add will give the above-mentioned warning and doesn't break at it. Also, all my code goes into the function.js file as they are button commands and not task pane related.

**Comment by ElizabethSamuel-MSFT** [comment]
@Pher0ah Did you consider the "Enable debugging for add-in commands and UI-less code" section of the article (https://docs.microsoft.com/office/dev/add-ins/develop/debug-office-add-ins-in-visual-studio#enable-debugging-for-add-in-commands-and-ui-less-code)?

Thanks.

**Comment by nergal1986** [comment]
I'm having the exact same issue. Can someone please provide a solution for this? I'm using VS 2019 .Thanks!
