### ISSUE TITLE
sessionStorage is not accessible from web add-ins

### ISSUE THREAD

**Issue by ahofman** [OfficeDev/office-js-docs-pr#1458]
When javascript in an add-in tries to read sessionStorage, I see the following console error:

Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.

This looks like it was a recent change in the add-in infrastructure, as it was working up until now - are add-ins still allowed to access sessionStorage or does the 2nd bullet point at the top of this doc need to updated to note that sessionStorage cannot be used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b683480b-a4fe-97ba-64f9-45ecfe829bf4
* Version Independent ID: a0993174-18dd-9594-9c3c-102d078e2217
* Content: [Persisting add-in state and settings - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings#feedback)
* Content Source: [docs/develop/persisting-add-in-state-and-settings.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/persisting-add-in-state-and-settings.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @ahofman - thanks for checking out Office Add-ins and our docs. Just checking: you aren't using custom functions in this add-in that is trying to access sessionStorage? If you happen to be using custom functions, this is expected because they don't allow access to global objects such as Window. 
If you're not using custom functions, I don't know of any changes off-hand, but I will go ahead and transfer this issue to the office-js repo just to have someone check if this is a recent product change. Just let me know if you are or are not using custom functions and I can try to get you the right answer on this. Thanks!
