### ISSUE TITLE
The add example does not work

### ISSUE THREAD

**Issue by andrewkittredge** [OfficeDev/office-js-docs-pr#1468]
You have to pass a value for invocation, I think you need to specify the type of invocation in the meta-data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17035fc0-ca69-03f2-fe37-8189ff870cc7
* Version Independent ID: 2d43e719-043b-7a62-04bb-66b2cce7bf1d
* Content: [Options for Excel custom functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-parameter-options?tabs=javascript#addressing-cells-context-parameter)
* Content Source: [docs/excel/custom-functions-parameter-options.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-parameter-options.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi Andrew - thanks for writing in. I believe the type {CustomFunctions.Invocation} is specified in the sample? You are right that you have to pass a value (i.e. cell A1) to get a value back. It is a bit of a weird example taken out of a larger context (because why would you ask the cell to get the context of itself)- although I've included it here so folks can get an understanding of how it can be used in the simplest possible way. It is more useful in the described scenarios but they involve a lot more code which we felt was not super useful to aid understanding of what this feature does. Let me know if that all addresses your question. If not, I am happy to provide more guidance. I'd love to understand how we can make this section clearer.

**Comment by andrewkittredge** [comment]
I was referring to this example-

/**
 * Add two numbers.
 * @customfunction
 * @param {number} first First number.
 * @param {number} second Second number.
 * @returns {number} The sum of the two (or optionally three) numbers.
 */
function add(first, second, invocation) {
  return first + second;
}

**Comment by mscharlock** [comment]
Ah ok! Yes if you were to use invocation in this example for something you would have to specify a type. However, it's indicated in this sample just so you know it always silently exists at the end of the parameters, even if not explicitly stated. I think we say somewhere on the page it is explicitly stated in the sample just for show. But, good to hear feedback that the language here could be improved. Would a code comment help here?

**Comment by mscharlock** [comment]
Hi @andrewkittredge, I'm going to close this thread and put this up to our team for discussion about making a change to make this clearer. If you need anything else, let me know by commenting on this thread and I will re-open it. Thanks!
