### ISSUE TITLE
What Office Add-in "Learning Paths" would you like to see?

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#1486]
### We Have a Request

We'd really like to have the opinions of Office Add-in developers about what **Learning Paths** we should add to our developer documentation. 

Some subjects in add-in development cannot be contained in a single article. A **Learning Path** is a sequence of related articles and other media, (or in some cases a tutorial) that is intended to provide developers with guidance about what they should read/view about an area of add-in development. 

The following have been suggested as good subjects for Learning Paths. _**We like to hear additional suggestions from you.**_ Also, please tell us which of the following you think we should prioritize first and/or which of these aren't really needed. 

#### Some suggestions

1. Working with the manifest
2. Debugging add-ins
3. Testing add-ins across platforms (Windows, Mac, web, etc.) 
4. Mastering Excel custom functions 
5. Transitioning from VBA/VSTO/COM to web add-ins 
6. Transitioning from Office Scripts to Office Web Add-ins 
7. Working with Requirement Sets 
8. Moving from development to production 
9. Implementing a smooth, attractive UI and UX 
10. Working with OOXML 
11. Working with whole documents; creating, downloading, uploading, getting the whole document. Also, launch a document with your add-in started.
12. Integrating with Azure, including importing data from Azure storage and integrating Azure functions with Excel Custom Functions
13. Implementing an Outlook add-in that supports both desktop and mobile extension points

**Comment by tuyoyexcel** [comment]
1.- Transitioning from VBA to web add-ins
2.- Deploy web add-ins in a local and remote server
3.- Connection between content pane and and Excel Data
4.- Mastering Excel custom functions

**Comment by mscharlock** [comment]
@tuyoyexcel Thanks for this input, this really helps us decide which direction to move in as a docs team. We definitely realize there is a large gap between modern web add-ins and VBA. Quick question for you as someone who writes on the custom functions documentation - did you find that you used our "See Also" sections or utilized any of the patterns and practices samples while you were learning?

**Comment by tuyoyexcel** [comment]
@mscharlock,
I will detail my process of learning the Office JavaScript API.
I started to learn the OJA because I am an Excel & VBA user for the last 20 years and I realized that JavaScript could add many new things to Excel.
First, I started playing with Script Lab, very useful for the beginning.
Then, I learnt some basic JavaScript code
Then, I installed Visual Studio and played with some Web Add-In templates including my own JavaScript Functions and customizing the Ribbon through the Manifest file.
Now, I am learning how to customize the task pane and interact with cells, rows, sheets and other Excel object from the HTML and CSS elements created in the Task Pane.
For the future I would like to learn how to create JS custom functions to be used from Excel, use the content pane as I use the task pane and deploy the web addin in a web server (I learnt to deploy it in a local server)
As there are not may examples out there to follow, my best friend is the Office JavaScript API documentation that I found here: https://docs.microsoft.com/es-es/office/dev/add-ins/reference/javascript-api-for-office or its version in English.

Here, you can find a playlist of my youtube channel with videos about what I am learning related to the OJA https://www.youtube.com/watch?v=nb3t_Kdpzxs&list=PLubxgncvQHs8GkYnYNG4K7w8Hwx61u677

I hope this helps!
José

**Comment by aagamdoshi** [comment]
Is there a way where we can create Office.js with Angular in Visual studio

**Comment by mscharlock** [comment]
There is no automatic template for an Office Add-in with Angular using Visual Studio, although I would suggest you read [our documentation about creating an add-in using Angular. ](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/add-ins-with-angular2) Let me know if that helps! Thanks. :)

**Comment by aagamdoshi** [comment]
@mscharlock thanks for reverting
i am using [https://github.com/OfficeDev/Office-Addin-TaskPane-Angular](url) as a sample reference
After building a Word Addin and using angular ,Yo generator following issue occurs
1. Not able to view the hosted addin on web browser
2. Need to run the solution with higher admin rights
3. Also in VS2019
No symbols are loaded. even after starting and then setting breakpoints, the debugger doesn't sync up with the map files to allow a debug session to happen.

 I was looking for a github sample project with angular, but wasn't able to fine one.
And most of the repo are archived and youtube videos are outdated.

**Comment by mscharlock** [comment]
@aagamdoshi - I see you have opened an issue in the sample repo (https://github.com/OfficeDev/Office-Addin-TaskPane-Angular) - I believe our engineers will be able to help you there! Let me know if they do not respond in a few days - we do want to get you an answer and they are usually good about replying. Thanks!

**Comment by Rick-Kirkham** [comment]
Thanks to everyone who provided feedback on this question. We have recently published our first learning path. It is for beginners to add-in development. The next learning path in the works is for helping VSTO/VBA developers transition to either Office Scripts or add-ins. I'm closing this issue, but anyone can still add suggestions and we will be alerted when you do.

**Comment by tuyoyexcel** [comment]
Could you provide us with the link where it has been published?
Thank you!!!!!

**Comment by Rick-Kirkham** [comment]
@tuyoyexcel 
It's here: [Start Here! A guide for beginners making Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/learning-path-beginner)

**Comment by tuyoyexcel** [comment]
@Rick-Kirkham Thanks!!! I found yesterday this link https://docs.microsoft.com/es-es/learn/paths/m365-office-add-in-associate/
I guess both are the same, I have checked it last night and it is really very good documentation for starting.
Regards.

**Comment by Rick-Kirkham** [comment]
We now have a learning path for people transitioning from VSTO add-ins to web add-ins: [Transition Here! A guide for VSTO add-in creators making Office Web Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/learning-path-transition)
