### ISSUE TITLE
Open a website in Chrome or Mozilla

### ISSUE THREAD

**Issue by binhnguyen1984** [OfficeDev/office-js-docs-pr#1554]
Hello,
I have an Excel Addin application. In my app, I have a link to a razor website. I use Office.context.ui.displayDialogAsync to open that website in a new window. However, I have an issue. Since the Excel Addin runs Internet Explorer 11 embedded in it, Office.context.ui.displayDialogAsync seems to use this browser to open the razor page. This leads to an error because Internet Explorer does not support Webassembly which is required to run Blazor client-side applications. 
Is there any way to configure Office.context.ui.displayDialogAsync so that it will use a different browser, e.g., Chrome or Mozilla to open a razor website? How can I get around this problem?

**Comment by Rick-Kirkham** [comment]
I'm sorry but there is no way to choose the browser that is used. This is controlled by Office and the OS. For details see [Browsers used by Office Web Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins). If you are not going to distribute the add-in through AppSource (aka the Microsoft app store) and you know that none of your add-in's end users are going to be in an Office/OS combination that uses IE, then this won't be a problem. Otherwise, you're going to have to accomplish what you are planning to do with the Blazor-based website. 

I'll close this issue, but you can still add comments and request that it be reopened.
