### ISSUE TITLE
Would you please provide information about Unit Test ?

### ISSUE THREAD

**Issue by NT-D** [OfficeDev/office-js-docs-pr#1611]
Hi Outlook team,
Thank you for providing good documents for debugging. We are now enjoying development and debugging, but let me provide feedback about contents. 

In general, developers run unit test on the client and CI pipeline on the cloud for keeping app quality. Our team also want to do Unit test, but there are no information about it. If possible, would you please provide how to do Unit test with Office.js and how to get Exchange Id Token and SSO token from agent on CI pipeline?  Because we protect backend with Exhcange Id token and SSO token, we need to get them for testing backend.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7157101-a1ee-f150-9275-1348b6597d19
* Version Independent ID: 35fa4941-f062-614a-6e10-cc787416d1e4
* Content: [Deploy and install Outlook add-ins for testing - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/testing-and-tips)
* Content Source: [docs/add-ins/testing-and-tips.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/testing-and-tips.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by NT-D** [comment]
@kbrandl Which issue can I see for progress in OfficeDev/office-js-docs-pr?

**Comment by kbrandl** [comment]
@NT-D I'm no longer a Microsoft employee, so cannot answer your question. @ElizabethSamuel-MSFT are you able to provide input here?

**Comment by ElizabethSamuel-MSFT** [comment]
Thanks, @kbrandl.

@NT-D For now, there's no further update. You can keep track with this same issue as it's now in the office-js-docs-pr repo.

Thanks.

**Comment by JensMadsen** [comment]
It has been almost three years since https://github.com/OfficeDev/office-js-docs-pr/issues/584, so to me it seems that supporting testing, CI/CD is not a priority for Microsoft. If that's so then fine I find other means to test my addin. But right now Microsoft does not clearly state that they are not going to provide these features in the near future. This situation is difficult for us because we would not like to invest a lot of time in developing a non-standard test solution if Microsoft release a framework for testing addins in all the various environments etc. So it would be very helpful if the team could provide us with a realistic timeline (this year, next year, never, no division has been made).

**Comment by JensMadsen** [comment]
Bump

**Comment by AlexJerabek** [comment]
Hi everyone,

We appreciate all the discussion and feedback requesting testing solutions for Office Add-ins and Office JS. Unfortunately, there are no automated or unit testing solutions that we provide at this time. We're working on a solution, but have no concrete implementation or release details to share at this time. We realize this is an unsatisfying answer, but we feel it’s better to be clear about the support story, rather than to create false expectations.

We are moving the discussion to M365 Developer Platform Ideas. For the primary concern around standardized testing, please upvote and comment on this idea: [Standard way to unit test and mock office-js API](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/standard-way-to-unit-test-and-mock-office-js-api/idi-p/2718673). For the other related requests that have accumulated on this issue, we also ask that you take your requests to the [M365 Developer Platform Ideas](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Office%20Add-ins%20development) and submit them as ideas (or upvote existing ones). This will help us prioritize things in an orderly fashion.
 
If there are other issues about the documentation that have been raised in this thread but were not addressed, please create a new issue to track each specific problem. 
 
Thank you.

**Comment by Rick-Kirkham** [comment]
We now have documentation for unit testing and mocking in Office.js.

[Unit testing in Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/unit-testing)

**Comment by JensMadsen** [comment]
Thank you for the efforts. However, IMHO we still need to test the office API (if possible). All methods are manually mocked in the aforementioned approach so we do not really test much functionality...

**Comment by GabrielHangor** [comment]
It feels that office-addin-mock library doesn't actually allow us to test anything and can be replaced with just plain mock objects...
