### ISSUE TITLE
No details on websocket possible errors and security

### ISSUE THREAD

**Issue by tytech3** [OfficeDev/office-js-docs-pr#1627]
I've been trying to connect to a websocket server with a react excel addin and have had no luck. The docs do not cover security, usage of WSS over WS. The error i get is ambiguous and not very helpful. It just says Error: SecurityError. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db285f50-5770-e426-47f6-a9f78536cab3
* Version Independent ID: 55778f17-2bdd-898b-41fc-e3f4e5517197
* Content: [Runtime for Excel custom functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-runtime)
* Content Source: [docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-runtime.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
Closing as duplicate of https://github.com/OfficeDev/office-js/issues/1018. 

@tytech3 sorry to hear you're having trouble. FYI, the Office JS team monitors all related repos, so you just need to open an issue once, in a single repo. For product-related questions/issues like this, **OfficeDev/office-js** is the best place to open the issue, so I'll leave your issue open there (and close duplicate issues elsewhere, like here). If it turns out that the docs need to be updated, based on the outcome of the issue in OfficeDev/office-js, we'll re-open this issue here in the docs repo for tracking at that time. Thanks!
