### ISSUE TITLE
Office 2013

### ISSUE THREAD

**Issue by jjtfsalgado** [OfficeDev/office-js-docs-pr#1683]
Is the custom functions API supported on Office 2013 (connected to an Office 365 subscription)? Is not clear in the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5456f6c2-991d-a35c-a39e-1613fc0ddbb8
* Version Independent ID: 63b393c1-66d5-4dc5-8010-c8c65d92bd52
* Content: [Custom Functions requirement sets - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-requirement-sets)
* Content Source: [docs/excel/custom-functions-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-requirement-sets.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @jjtfsalgado, 

Thanks for the question. Office 2013 refers the perpetual version of Office released at that time. Office 365 refers to the subscription model. If you have an Office 365 subscription, then you have Office 365, not Office 2013/2016/2019.  

As such, any Office 365 build at version 1904 or higher (as per the article) supports custom functions. Office 2013 does not.

Since the documentation is consistent with how Microsoft generally brands these products, I'm going to close the issue. If you have further questions, please respond to this thread and we'll open it back up. 

Thanks!

**Comment by jjtfsalgado** [comment]
Hi @AlexJerabek thanks for your reply. 

Just to contextualize my initial question, we have an excel add-in using the custom functions API and recently a customer reported that couldn't find it on the office store. It's typically because their Excel version don't comply with the minimum API requirements but this customer was using an Office 365 subscription (ProPlus) with an Excel 2013 version (15.0.5215.1000) released on the 13th February 2020 which is, time wise, ahead of the version 1904 (14th May 2019). 

So new releases of Excel 2013, even under an Office 365 subscription, aren't eligible in this case?

![image](https://user-images.githubusercontent.com/14180997/77111128-b0714d80-6a1e-11ea-9519-d5c7de91d1d3.png)

**Comment by AlexJerabek** [comment]
@jjtfsalgado 
That's an interesting state the customer is in. If they're connected to an Office 365 subscription, they should be able to download and use Excel for Office 365. I don't think you can upgrade Excel 2013 like that in the client. You can only upgrade to the latest 15.x version with 2013, which will never have custom functions.
