### ISSUE TITLE
Using variables in range

### ISSUE THREAD

**Issue by PramodKumarYadav** [OfficeDev/office-js-docs-pr#1699]
Its a common requirement to use variables in selected range. Is it possible and if yes, can you give an example for 
- rows only (say var range = sheet.getRange(rowFirst:rowLast); [ Dont know if this works though)
-  columns only (say var range = sheet.getRange(colFirst:colLast); 
-  cells only (say var range = sheet.getRange("A"+firstRow +":" + "D" + :rowLast); 
All these are wrong examples but you get the idea. Is it possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e16ee19-d66e-c44d-d0fb-12088f6977b3
* Version Independent ID: 30d84c68-f682-795c-664d-b5b2652e57fa
* Content: [Work with ranges using the Excel JavaScript API (advanced) - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-ranges-advanced#feedback)
* Content Source: [docs/excel/excel-add-ins-ranges-advanced.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-ranges-advanced.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @PramodKumarYadav, 

The `getRange` method takes in a string representing a cell range in the worksheet, such as "A1:D4", "A:D" for just the columns, or "1:4" for just the rows. As long as your variables map to Excel rows or columns, you can use string concatenation to build the argument. You may need to use `range.columnIndex`, `range.rowIndex`, and `range.getCell` to translate to and from zero-based numbers into the letter-based columns.

I'd recommend exploring these APIs by using [Script Lab](https://docs.microsoft.com/office/dev/add-ins/overview/explore-with-script-lab?view=excel-js-preview) . There are plenty of samples to look at, plus it lets you use the Excel APIs without having to host a service.

In the future, I'd recommend raising programming questions such as this on [Stack Overflow](http://stackoverflow.com/questions/tagged/office-js). That way, other members of the community can learn from your questions. Be sure to tag your Stack Overflow question with "office-js".

Because this question is more about programming than the specific APIs, I'm going to close the issue. Please let me know if you have any other questions.

**Comment by PramodKumarYadav** [comment]
This helped Alex. I tried again with your explanation and it worked like a charm. Thank you!

**Comment by PramodKumarYadav** [comment]
Just to add an example, if someone else stumbles on this page:
    const sheet = context.workbook.worksheets.getActiveWorksheet();
    var firstrow = 1
    var lastRow = 6
    var range = sheet.getRange(firstrow + ":" + lastRow)
