### ISSUE TITLE
No iTunes on macOS Catalina for add-in sideload on iPad

### ISSUE THREAD

**Issue by Magnielcz** [OfficeDev/office-js-docs-pr#1716]
Hi,

on the last version of macOS (Catalina), there is no iTunes available and there won't be in future versions. A new way is to select an iPad in Finder, choose tab Files and drag&drop manifest in Word.

![image](https://user-images.githubusercontent.com/5764186/78140361-2cf62a00-742a-11ea-9582-dd0f52e5c7e4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589820d2-9925-dc5e-76a7-83921a569137
* Version Independent ID: ab8bde36-096f-81f3-f4d1-9b25fc69e6ee
* Content: [Sideload Office Add-ins on iPad and Mac for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac)
* Content Source: [docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@Magnielcz Thanks for letting us know about this.

@Rick-Kirkham Can you take a look?

Thanks.

**Comment by Rick-Kirkham** [comment]
@keyur32 
I don't know a thing about iPads or Macs and I don't even fully understand the question. Can you assign to someone who would know how to respond?

**Comment by ps-git** [comment]
### Context:
I recently built a JS Add-In for Excel, and am facing a similar to that noted by @Magnielcz where manifest.xml files uploaded to the iPad are not picked up in the My-Add ins section on the insert tab. Saving the manifest file directly on the ipad, by sending it to the Files app --> Excel. Also failed. I don't know whether this is due to corporate management setting on my device or something else.

@Rick-Kirkham , @keyur32 , @JuaneloJuanelo 

1.  Can you please confirm sideloading on iPad still works.
2.  Update the documentation for uploading to iPad per the changes to iTunes. 
3.  Add a sample manifest.xml file (preferably to the documentation and unit/integration tests) that is guaranteed to work on iPad so that developers (and fans like myself) can establish that we didn't screw up and this is related to something else than our manifests. 


### To clarify on the original question:
As it relates to Macs, the underlying issue is that the documentation provided at https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac is out of date as it relates to uploading to an iPad from a Mac. In particular, Apple has discontinued iTunes on Mac. Replacing it with a dedicated 'Music' app whilst integrating the remaining functionality into Finder. The screenshot attached by @Magnielcz highlights this new look.

Importantly, manifest xml files uploaded to the iPad via the obvious routes do not get picked up when the Office Apps are launched.

The documentation is also referring to an add-ins folder which no either no longer exists or used to refer to something else.


@Magnielcz, can you please confirm if you still have this problem. If not, which steps did you take to resolve this.

**Comment by ps-git** [comment]
Please note that this **ticket is awaiting reassignment since April 3rd**


@Rick-Kirkham , @keyur32 , @JuaneloJuanelo, @ElizabethSamuel-MSFT, @alison-mk 

Adding to my comment from two weeks ago.

**Could someone on the MS Office Dev team please have a look and confirm that side-loading on iPad (newest OS) still works.**

I cannot get it to work despite loading the manifest.xml file from Windows (iTunes), Mac (Finder), and directly on the device.

The Add-In works fine for Excel versions running on MacOS, Windows, and the Online version.


If still supported, a working manifest would be much appreciated.

**Comment by ElizabethSamuel-MSFT** [comment]
@Magnielcz and @ps-git, thanks for raising this issue and giving us tons of feedback on it.

@ps-git, thanks for creating a PR to help address the issue.
