### ISSUE TITLE
Enabling SSO | Is the "Grant administrator consent to the add-in" mandatory during developement ?

### ISSUE THREAD

**Issue by cmanoliu** [OfficeDev/office-js-docs-pr#174]
Hello, 

Documentation says that the "Grant administrator consent to the add-in" procedure is 
"only needed when you're developing the add-in. When your production add-in is deployed to AppSource or an add-in catalog, users will individually trust it or an admin will consent for organization at installation."
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/grant-admin-consent-to-an-add-in

Is it mandatory for SSO during the development phase ? If so, can you explain why ?
Thank you.

Regards,

**Comment by Rick-Kirkham** [comment]
It used to be required when developing (because we didn't have a way of sideloading it and generating the user consent form), and we still recommend it if you are using a Developer O365 tenant. However, if you prefer, it should be possible now to sideload an SSO add-in under development and the user will be prompted with a consent form. See [Sideload on Windows](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins) and [Sideload on Office Online](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing).

**Comment by lindalu-MSFT** [comment]
Added this to topic for clarity.
