### ISSUE TITLE
How to deploy to azure?

### ISSUE THREAD

**Issue by sulwa74** [OfficeDev/office-js-docs-pr#1741]
## Article URL

https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator

## Issue

 I am struggling with deployment of this example code to azure (webapp) or any other server than localhost. The project runs on localhost like a charm but I can't deploy it on any other platform. Could you provide detailed description how to deploy this example to for example azure webapp or any other platform supporting nodejs?

**Comment by Rick-Kirkham** [comment]
We have this article: [Host an Office add-in on Microsoft Azure](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/host-an-office-add-in-on-microsoft-azure), but it assumes that you are working in Visual Studio. We don't generally provide information about how to host on a web server or cloud account because add-in's are hosted in all the same ways as any other web application, and there is a lot of information about how to do this on the web. To begin with search in Bing for "How to host a node.js web application on Azure".  

One way that add-ins do differ from other web apps is that they have a manifest and the manifest does not get hosted with the other files of the web app. So, be sure you are familiar with the [Publish](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish) section of our documentation.
