### ISSUE TITLE
Sideloading Installation Failed

### ISSUE THREAD

**Issue by paulghodgson** [OfficeDev/office-js-docs-pr#1769]
Attempting to side load using the manifest file example results in an "Installation Failed" message of "An internal server error occurred. The operation failed., Object reference not set to an instance of and obect. "  I this my fault or is there an omission in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a55fe4-0fe1-858c-26a4-dddc3ee128ea
* Version Independent ID: 0a643291-936f-b374-37fd-7db497c73cce
* Content: [Create an Outlook mobile add-in for an online-meeting provider (preview) - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting)
* Content Source: [docs/outlook/online-meeting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/online-meeting.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@paulghodgson Thanks for trying out this feature but sorry you hit this issue. However, the manifest example is actually an excerpt of a section of the manifest instead of a full manifest. We'll clarify that in the docs.

For more about manifests for Outlook, see [Outlook add-in manifests](https://docs.microsoft.com/office/dev/add-ins/outlook/manifests) and [Add support for add-in commands for Outlook Mobile](https://docs.microsoft.com/office/dev/add-ins/outlook/add-mobile-support).

Let us know if this helps or if you hit any further issues.

Thanks.

**Comment by paulghodgson** [comment]
I have a full add-in manifest that works fine for desktop, the issue here is that replacing the <DesktopFormFactor> element with a<MobileFormFactor> always results in a "An internal server error occurred. The operation failed., Object reference not set to an instance of and object. ".  According to the Yeoman generator the schema is valid, what seems to be lacking is away to debug this error, any ideas?

**Comment by paulghodgson** [comment]
I have a full add-in manifest that works fine for desktop, the issue here is that replacing the DesktopFormFactor element with a MobileFormFactor element always results in a "An internal server error occurred. The operation failed., Object reference not set to an instance of and object. ". According to the Yeoman generator the schema is valid, what seems to be lacking is away to debug this error, any ideas?

**Comment by Briix** [comment]
Hi, I noticed this was marked as closed, but none of the links above helped me figure out what was wrong with my manifest so I just wanted to quickly share my solution in case anyone else stumbles upon this issue in the future.

We were running into the same issue when trying to add a `<MobileFormFactor>` element to our manifest, and in the end it turned out that if we just moved the `<MobileFormFactor>` host definition to be after the `<DesktopFormFactor>` definition it worked! 

So our structure ended up being like this:
```
<Hosts>
  <Host>
    <DesktopFormFactor></DesktopFormFactor>
  </Host>
  <Host>
    <MobileFormFactor></MobileFormFactor>
  </Host
</Hosts>
```

Feels like both the docs and the error shown could be a bit clearer as neither stated anything close to this solution.

**Comment by AlexJerabek** [comment]
Thanks for pointing this out @Briix. Let me tag @Rick-Kirkham for awareness.

**Comment by Rick-Kirkham** [comment]
@Briix Do you really have `<DesktopFormFactor>` and `<MobileFormFactor>` each nested within its own parent `<Host>`? I'm surprised that works. They should be peers within the same parent. 

You are correct about their relative ordering. For some reason `<MobileFormFactor>` never got included in our article [How to find the proper order of manifest elements](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?view=powerpoint-js-preview). I'll get that fixed.

**Comment by Briix** [comment]
@Rick-Kirkham It does work having them in their own parent `<Host>` but nesting them works just as well, as long as `<MobileFormFactor>` is still after `<DesktopFormFactor>`. Thanks for pointing that out :)

Maybe not important since nesting the `<Host>` elements shouldn't work, but your cli validation tool still validates the manifest as being correct even when it doesn't work because `<MobileFormFactor>` comes first.
