### ISSUE TITLE
How to install JavaScript Add In

### ISSUE THREAD

**Issue by swimhiking** [OfficeDev/office-js-docs-pr#1789]
This is a very cool project; I am very interested in develop Excel Add In using javascript; I have a very beginning question about how to install? I try to follow the instruction, not sure how to manually install the Add In, and which file should to install. Document mention "Mail Add-ins", but if I develop one for myself, no need to mail, don't know  where and which file is for installation. Thanks

**Comment by AlexJerabek** [comment]
Hi @swimhiking, 

Thank you for your interest in Office Add-ins. You won't install an Office Add-in in the traditional sense. You'll need to deploy and publish the add-in by hosting the web service somewhere. More information can be found [in this article](https://docs.microsoft.com/office/dev/add-ins/publish/publish).

I'd also recommend starting your learning journey on [this page](https://docs.microsoft.com/office/dev/add-ins/overview/learning-path-beginner). Starting there, you'll learn the prerequisites to building an Office Add-in and become familiar with the ecosystem.

I'm going to close this issue, as this repo tracks problems with the documentation. I recommend going to [Stack Overflow](https://stackoverflow.com/questions/tagged/office-js) to ask programming questions. Be sure to tag your question with "office-js" so that members of the Office Add-ins product team and community see your question.
