### ISSUE TITLE
WorksheetCollection.addFromBase64() api not available in latest version of office.js

### ISSUE THREAD

**Issue by anantjs11** [OfficeDev/office-js-docs-pr#1801]
We are in a desperate need of an excel office javascript api to Insert the specified worksheets of a workbook into the current workbook.

I found below api in the preview version
WorksheetCollection.addFromBase64()
[Details here](https://docs.microsoft.com/en-us/javascript/api/excel/excel.worksheetcollection#addfrombase64-base64file--sheetnamestoinsert--positiontype--relativeto-)

Please include this api in the upcoming version of office js, so that it can help us to solve our business road block we are currently facing in our new office Excel addin application.

Also, please let me know the official release of upcoming version of office.js.

Thanks in Advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee2d4bf5-85ab-7f5e-0112-25b4c41f5db0
* Version Independent ID: ebd8e0f7-9ff4-b0f0-e4eb-36453d68d937
* Content: [Excel JavaScript preview APIs - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-preview-apis#feedback)
* Content Source: [docs/reference/requirement-sets/excel-preview-apis.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/requirement-sets/excel-preview-apis.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @anantjs11, 

We are working on releasing this API into general availability. It is presently in preview because it is not supported across all platforms. We understand the customer need and are trying to add this feature to an upcoming requirement set.

We'll be talking about this API on the upcoming Office Add-ins Community Call. There, we'll be answering customer questions and surveying developers to help us properly design this feature and release it in a quick and useful fashion. Please join us May 13th, the invite is here: https://aka.ms/officeaddinscommunitycall

I'll be closing the issue, as there's nothing actionable we can do in the documentation.

**Comment by anantjs11** [comment]
Thanks @AlexJerabek for quick and helpful response.
I Hope, we can get this feature included in the upcoming release of office.js.
