### ISSUE TITLE
PLEASE Add Support to Connect Pivot Tables to External Database

### ISSUE THREAD

**Issue by thunter05** [OfficeDev/office-js-docs-pr#1809]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-pivottables

## Issue
Excited about the new JS Excel API, BUT can we PLEASE add support to connect Pivot Tables to External Database Datasources? This is available in the VBA Excel Object Model and is something we use a lot at my organization. It's a key feature. We refreash our pivot tables when the database data changes. Very powerful combination. Would be an absolute game changer to have this with the new JS API!

**Comment by AlexJerabek** [comment]
Hi @thunter05, 

Glad to hear you're excited about the new Excel APIs. The new requirement set, ExcelAPI 1.11, is releasing to general availability this week, so you'll have a few more features for your add-ins.

If you'd like to request external connection support for PivotTables, please head over to the [Office Developer UserVoice](https://officespdev.uservoice.com/). There, you can request features for the platform (or upvote existing requests). The site is monitored by the product team and used to prioritize new feature work. I'll also pass on your suggestion to the team, though a UserVoice request with multiple votes will carry more weight.

I'm going to close this issue, since issues in this repo are intended to track documentation requests and issues. You can respond to this thread or start a new one if you have further questions.
