### ISSUE TITLE
Capability comparison between Office Add-ins (web technology) and VBA

### ISSUE THREAD

**Issue by flutable** [OfficeDev/office-js-docs-pr#1840]
Could you please point to a comparison of the Office Add-ins API and VBA. Is there anything that VBA can do that Office Add-ins cannot do? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42faa32c-446b-0209-4a24-9a29b4921ea1
* Version Independent ID: a5f0fc77-a881-df1e-1f49-aa0e555022e0
* Content: [Office Add-ins platform overview - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins#feedback)
* Content Source: [docs/overview/office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/overview/office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @flutable, 

Unfortunately, the document you're looking for doesn't exist. There's no side-by-side comparisons of the two platforms. There is [a top-level overview comparing VBA to Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/resources/vba-differences) (which have similar benefits and limitations to add-ins except that add-ins are cross-platform and scripts are web client-only). In general, the API surface is smaller for add-ins than VBA, but almost all the commonly used features are implemented. There's also the difference of web hosting for add-ins and desktop-based execution for VBA. With that comes access to web resources instead of access to the user's desktop.

Are there specific scenarios you want to support? You could also about those on [Stack Overflow](https://stackoverflow.com/questions/tagged/office-js) (with the "office-js" tag). Additionally, you could peruse the [Office JavaScript APIs](https://docs.microsoft.com/en-us/javascript/api/overview?view=excel-js-preview) and look for individual features you are looking to use.

We do acknowledge the need for this direct comparison between the two platforms. It's on our long-term backlog.  

Because this is a broader ask, I'm going to close the issue. I'm happy to carry on the conversation in the thread.
