### ISSUE TITLE
What is the release scheduler for 1.8?

### ISSUE THREAD

**Issue by timothyhoffmann** [OfficeDev/office-js-docs-pr#1890]
[Enter feedback here]
What are the planned dates for when 1.8 will be released on the various platforms?  I see it's available in OWA today but the May 2020 version of Windows Outlook 365 Semi-Annual channel  is still only supporting 1.7 with build 11929.20776 V 1908.  I ask for an Outlook update and nothing new was available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54fc996c-b446-640d-b297-535cfa64d623
* Version Independent ID: 591625be-0b31-c57b-b771-3fd12b3a0538
* Content: [Outlook add-in API requirement set 1.8 - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.8/outlook-requirement-set-1.8)
* Content Source: [docs/reference/objectmodel/requirement-set-1.8/outlook-requirement-set-1.8.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/requirement-set-1.8/outlook-requirement-set-1.8.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@timothyhoffmann On the [requirement sets page](https://docs.microsoft.com/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets#outlook-client-support), we note that 1.8 is available from version 1910 (build 12130.20272). Based on the [Microsoft 365 update history page](https://docs.microsoft.com/officeupdates/update-history-microsoft365-apps-by-date), it seems like your channel is updated in January and July. As such, if that pattern continues, support for 1.8 should be available in the next update in July when the channel should likely be updated to version 2002 (build 12527.20442).

My team doesn't control the channel update schedule so that's the best info we can provide at this point.

I'll go ahead and close this issue but if you have any further questions, let us know.

Thanks.
