### ISSUE TITLE
What is 'Office 2016 on Windows, Build 77xx.xxxx or later'?

### ISSUE THREAD

**Issue by BradyDonovan** [OfficeDev/office-js-docs-pr#1952]
Hi all,

I'm trying to debug an Office Add-In right now in a Windows Outlook client and I'm not certain what the documents mean by that build major. The Office 2016 suite I have has a major rev of '16.0', so I'm a bit confused as to what this points to.

Per the docs:
`In Office 2016 on Windows, Build 77xx.xxxx or later, you can attach the debugger from the task pane.`

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8b1badd-9a43-6935-a6e6-76508e7f9741
* Version Independent ID: bdeabb00-8eeb-07a2-0de9-967f018a2c8a
* Content: [Attach a debugger from the task pane - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/attach-debugger-from-task-pane)
* Content Source: [docs/testing/attach-debugger-from-task-pane.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/attach-debugger-from-task-pane.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@BradyDonovan Thanks for your question! From Office 2016, the major version is truncated from the build notation so instead of 16.0.6326.1010, you may see 6326.1010. This is reflected in the product. You can check your current build version (see this article: https://docs.microsoft.com/office/dev/add-ins/develop/office-versions-and-requirement-sets#how-to-check-your-office-version). The documentation usually reflects this notation too. (Example docs: update history for [M365 Apps](https://docs.microsoft.com/officeupdates/update-history-microsoft365-apps-by-date) and [Office 2016 Click-to-Run](https://docs.microsoft.com/officeupdates/update-history-office-2019).)

If your Outlook version doesn't quite look like that, then the following articles may help.
- [What version of Outlook do I have?](https://support.office.com/article/what-version-of-outlook-do-i-have-b3a9568c-edb5-42b9-9825-d48d82b2257c)
- [What version of Office am I using?](https://support.office.com/article/about-office-what-version-of-office-am-i-using-932788b8-a3ce-44bf-bb09-e334518b8b19)
- [Find details for other versions of Office](https://support.microsoft.com/office/8e83dd74-3b83-4528-bda6-6ff6118f8293)

By the way, regarding testing in Outlook, you can also take a look at the articles under the [**Outlook > Testing and tips** section](https://docs.microsoft.com/office/dev/add-ins/outlook/testing-and-tips) of the documentation.

Thanks again for your interest in Office Add-ins development, and if you have any further questions, let us know.
