### ISSUE TITLE
document.write feature

### ISSUE THREAD

**Issue by ishitadatta** [OfficeDev/office-js-docs-pr#2002]
## Issue

I cannot find any information regarding how to increment document.write feature or to display any content to the taskpane of the add-in using create element. The documentation for all JavaScript elements is not available.

**Comment by ishitadatta** [comment]
![Screenshot (369)](https://user-images.githubusercontent.com/48859631/86928234-eebb8580-c151-11ea-955e-a0ef07b7a605.png)

**Comment by lindalu-MSFT** [comment]
Hey @AlexJerabek, this is a doc request. Can you help me triage this and assign to the correct Excel/JS writer? THANKS in advance.

**Comment by Rick-Kirkham** [comment]
Please provide more details of what you are trying to do and what is going wrong. Also, what is the `list.child()` method you are using and what kind of object does it return? I can't find any info on it. Finally, `Microsoft.Office.WebExtension.EventType` is an enum. It is not a value itself that can be passed as a parameter.

**Comment by lindalu-MSFT** [comment]
@Rick-Kirkham Thanks for your reply! Also, since this appears to be more of a programming question than a doc request, I suggest that @ishitadatta posts this on [Stack Overflow tagged [office-js] and [excel]](https://stackoverflow.com/questions/tagged/excel+office-js). I'm sure the developer community there can help with this! Thanks,
