### ISSUE TITLE
Error in Update All Cells... example

### ISSUE THREAD

**Issue by choiway** [OfficeDev/office-js-docs-pr#2013]
There is an error in the Update All Cells In Range section:

The following two lines need to be wrapped in a 2d array.
```
    range.numberFormat = 'm/d/yyyy';
    range.values = '3/11/2015';
```

It works as follows:
```
    range.numberFormat = '[[m/d/yyyy]]';
    range.values = '[[3/11/2015]]';
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 819bf53b-d792-85b3-e616-7b5e2f087a4f
* Version Independent ID: 0611031f-6d92-c508-9680-179d5832722a
* Content: [Fundamental programming concepts with the Excel JavaScript API - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-core-concepts)
* Content Source: [docs/excel/excel-add-ins-core-concepts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-core-concepts.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @choiway. I'll look into fixing the sample code and report back.

**Comment by AlexJerabek** [comment]
Hi @choiway, 

So that sample code actually works as is. It won't compile with TypeScript definitions, but setting those properties (`formulas`, `numberFormat`, and `values`) with a single value (not in an array) does populate the entire range. 

I'm working with the product team to figure out how to reconcile the behavior with the definitions.  I just wanted to keep you updated so you're not blocked.

**Comment by choiway** [comment]
Got it. I should have mentioned that I am using Typescript React.

**Comment by AlexJerabek** [comment]
Hi @choiway, 

Thanks again for pointing this out. We decided that while the sample code originally in the article does work, the convenience is mitigated by the confusing TypeScript narrative. Rather than explaining the workaround (#2021), we'll just follow our own type definitions.

The corrected articles have been checked into the master branch and will be live soon. Please let me know if you have any other questions.
