### ISSUE TITLE
UI-less Custom functions does not trigger when a workbook is opened

### ISSUE THREAD

**Issue by vikasm1720** [OfficeDev/office-js-docs-pr#2047]
I have a custom function, which fetches data from stock API and display data in cells. When a workbook with this function is opened it fails to refreshes automatically. The user has to forcefully click on the refresh button to force recalculate. Is there a way to force recalculate when a spreadsheet is opened. 

/**
 * Gets stock values.
 * @customfunction
 * @param {string[][]} identifier Identifier values
 * @param [p1] Optional parameters
 * @param address {CustomFunctions.Invocation} cell address
 * @returns {any[][]} A dynamic array with multiple historical values.
 * @requiresAddress
 */
//@ts-ignore
export function getstock(identifier,p1?: string[], address) {
    return getDatafromAPI(identifier, p1, address._address);
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db285f50-5770-e426-47f6-a9f78536cab3
* Version Independent ID: 55778f17-2bdd-898b-41fc-e3f4e5517197
* Content: [Runtime for UI-less Excel custom functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-runtime)
* Content Source: [docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-runtime.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @vikasm1720, 

Thanks for the question. Have you tried making this a streaming function? Since you're fetching stock prices, I assume you want everything to update with the market. There's a tutorial on making this type of custom function here: https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?view=excel-js-preview&tabs=excel-windows#create-a-streaming-asynchronous-custom-function

Please let me know if that helps. Thanks!

**Comment by vikasm1720** [comment]
@AlexJerabek , thank you for pointing me to streaming functions, that actually solved half my problem. 
With streaming function is there a way to return dynamic array as results. I am pulling historical data sets, so previously I was using dynamic arrays to return data but with streaming function, i am unable setresults for dynamic array.
@returns {any[][]} A dynamic array with multiple historical values.

**Comment by vikasm1720** [comment]
I tried the solution given in https://github.com/OfficeDev/office-js/issues/1220 for the dynamic array, it worked closing this issue

**Comment by vikasm1720** [comment]
Reopening this issue. In my current workflow, I am using the requiresAddress parameter to assign data in the cell. The requiresAddress is used for offsetting data. Is there a way to offset data with dynamic arrays. the offset should be cell-1(row, column) and should not override the formula while displaying values. 
For example: If I insert a formula in B2, then I want to show Company Name in B1 and date in A2 and actually stock price in B2.

**Comment by AlexJerabek** [comment]
Assigning @mscharlock to investigate.

**Comment by mscharlock** [comment]
@vikasm1720 I'll look into this with our engineers and let you know. Thanks!

**Comment by mscharlock** [comment]
Hi @vikasm1720 It's my understanding that this doesn't work with dynamic arrays. Reason being, our dependency model is such that formulas can only impact the cells that they live in. Otherwise, you run into weird side effects when a spreadsheet recalculates. Hope that helps answer your question. Let me know if you need anything else.
