### ISSUE TITLE
Need Workbook On Save Event

### ISSUE THREAD

**Issue by ysachin7** [OfficeDev/office-js-docs-pr#2059]
I have a requirement to do some functionality on workbook on save event. 
I am using office.js and blocked right now because of this.

Can anyone please help or suggest anything

**Comment by AlexJerabek** [comment]
Hi @ysachin7, 

Thanks for using Office Add-ins. I'm sorry to hear you're blocked needing a save-related event. There was [a Stack Overflow thread](https://stackoverflow.com/questions/62066379/save-functionality-in-excel-addin-using-officejs-and-reactjs) about this, but it seems like we determined an onSave event would be noisy due to the number of times Excel autosaves.

I'd recommend creating a request on [UserVoice](https://officespdev.uservoice.com/). There, you can also describe your scenario, so we can have a better understanding on what you're trying to accomplish. We use UserVoice to prioritize requests when adding new features to Excel, so the community can upvote your suggestion if it's a feature they also want.

You can also post on [Stack Overflow](https://stackoverflow.com/questions/tagged/office-js) using the "office-js" tag to see if there's a workaround.

I'm going to close the issue, since there's nothing actionable we can in the documentation. Let me know if you have any other questions.
