### ISSUE TITLE
Pass parameter from host to the addin

### ISSUE THREAD

**Issue by KapilGeorge** [OfficeDev/office-js-docs-pr#2066]
I am opening my excel workbook from command prompt and passing some arguments to it as shown in the below example.
I am able to load my addin when the document is opened but how do i pass the parameter to the addin or is there a way to read the parameter in Office.initialize function?

example:
excel.exe xyz.xlsx parameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc45d88c-993f-01c9-6134-8b28cce6697f
* Version Independent ID: 4823080f-5e05-41d3-26c4-0cdb5037ede5
* Content: [Run code in your Excel add-in when the document opens - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/run-code-on-document-open)
* Content Source: [docs/excel/run-code-on-document-open.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/run-code-on-document-open.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @KapilGeorge,

Today, you can't pass parameters from the command line into `Office.initialize`. I'd recommend you create a request on [UserVoice](https://officespdev.uservoice.com/). We use UserVoice to prioritize community requests for addition to the product. If the community also needs the feature and upvotes your request, it'll be more likely to be added to the add-ins platform.

Since there's no actionable documentation work item, I'm going to close this issue. Please let me know if you have any other questions. Thanks!

**Comment by Shujee** [comment]
and where is UserVoice?

**Comment by AlexJerabek** [comment]
Hi @Shujee,

Since my last post, Microsoft has moved away from using UserVoice. We now track community feature requests for the M365 Developer Platform on Tech Community: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
