### ISSUE TITLE
OAuth from Outlook for mac

### ISSUE THREAD

**Issue by ChristopherHButler** [OfficeDev/office-js-docs-pr#214]
Hi, 
I am trying to perform OAuth from a react-based (with state managed by redux) front-end add-in for outlook (running on mac) with a node/express backend. Can I follow the same pattern as outlined here or would I need to change it somehow? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 714ec64d-6ee8-ad80-3347-d559534413f2
* Version Independent ID: 1bf3b8e7-4b73-7e64-a96f-f3771d7bbbb7
* Content: [Use the OAuth authorization framework in an Office Add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/use-the-oauth-authorization-framework-in-an-office-add-in)
* Content Source: [docs/develop/use-the-oauth-authorization-framework-in-an-office-add-in.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/use-the-oauth-authorization-framework-in-an-office-add-in.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Reezaali** [comment]
@Rick-Kirkham do you know the answer to this?

**Comment by Rick-Kirkham** [comment]
@ChristopherHButler This article is obsolete. It is not in the TOC and hasn't been for a long time (maybe never).  It should have been removed from our repo of source files when we introduced the Dialog API over two years ago. I suspect it was overlooked simply because it wasn't in the TOC and we didn't know it was there. We no longer recommend using `window.open` and sockets. We recommend that you use our Dialog API, which has a built in mechanism for communication from the dialog back to the main task pane. Please see the following two articles, which should be considered a replacement for this one: 

[Authorize external services in an Office add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/auth-external-add-ins)

[Use the Dialog API in your Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins)

We will soon remove this article.
