### ISSUE TITLE
Outlook Calendar REST API issue

### ISSUE THREAD

**Issue by aman3011** [OfficeDev/office-js-docs-pr#2195]
I have been trying to update a calendar event using the Calendar REST API, and I am getting a 403 The api you are trying to access does not support item scoped OAuth." 

I have given the read/write permission in calendar. I'm posting my request as well. The officeREST config has been working for getting the events. 

Please let me know what's going wrong . The documentation doesn't explain scoping much and how to do so. Also we are designing this Add-in with React. 

```
  updateEvent = (authToken,id) => officeREST.configurePatchRequest(
    `/v2.0/me/events/${id}`,
    {
      Location: {
        DisplayName: 'Your office',
        Address: null
      }
    },
    {
      headers: {
        Authorization: `Bearer ${authToken}`,
        'Content-Type': 'application/json'
      }
    })
```

**Comment by exextoc** [comment]
Thanks for posting the error and sample code.

@aman3011 Can you check the value of the `<Permissions>` element in your add-in's manifest?

Since the error message mentions 'item scoped OAuth', this likely indicates that the Permissions in the manifest is either `ReadItem` or `ReadWriteItem`. Changing this to `ReadWriteMailbox` will allow the server to issue a REST token with additional scope.

I checked on the [Use the Outlook REST APIs from an Outlook add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/use-rest-api#add-in-permissions-and-token-scope) documentation and I believe this section describes the issue you are seeing (assuming the Permissions element is not already `ReadWriteMailbox`):

> In most cases, the token returned by getCallbackTokenAsync will provide read-only access to the current item only. This is true even if your add-in specifies the `ReadWriteItem` permission level in its manifest.
> If your add-in will require write access to the current item or other items in the user's mailbox, your add-in must specify the `ReadWriteMailbox` permission level in its manifest. In this case, the token returned will contain read/write access to the user's messages, events, and contacts.

**Comment by aman3011** [comment]
Thank you, I was able to configure it correctly.
