### ISSUE TITLE
context.workbook.getSelectedRange() throws an error if called from Custom Tab, but works fine from task pane

### ISSUE THREAD

**Issue by nikhilism15** [OfficeDev/office-js-docs-pr#2232]
I have a method in my commands.ts file, which is called from two places: from a button in the taskpane and from a button in the custom tab. Although both buttons call the exact same method, I get this error while calling from the tab:
`{"name":"RichApi.Error","code":"InvalidArgument","traceMessages":[],"innerError":null,"debugInfo":{"code":"InvalidArgument","message":"The argument is invalid or missing or has an incorrect format.","errorLocation":"Worksheet.getRange","statement":"var range = worksheet.getRange(...);","surroundingStatements":["...","var tables = workbook.tables;","var table = tables.getItem(...);","table.load([\"text\"]);","var worksheets = workbook.worksheets;","var worksheet = worksheets.getItem(...);","// >>>>>","var range = worksheet.getRange(...);","// <<<<<","// Instantiate {range}","range.load([\"values\"]);"],"fullStatements":["Please enable config.extendedErrorLogging to see full statements."]},"httpStatusCode":400}`

I am actually doing this: `context.workbook.getSelectedRange()`.

When I enabled extendedLogging, I saw that the `getSelectedRange()` gets converted into `worksheet.getRange('INaN')`, no matter whether I select a single cell or a block of cells.

Can someone help me understand what I am doing wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6b16473-fffd-9ebf-ee91-2f0012a496ee
* Version Independent ID: 3f147de9-0138-9104-f462-c6f4097b1167
* Content: [Work with workbooks using the Excel JavaScript API - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-workbooks)
* Content Source: [docs/excel/excel-add-ins-workbooks.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-workbooks.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by alison-mk** [comment]
Hi @nikhilism15, thank you for submitting an issue! Can you provide the complete add-in code you're using, so that we can reproduce the issue? If we can reproduce the problem and it's a product bug, I'll transfer this issue over to the office-js repository so our engineers can help resolve it. We can't debug product issues here in the office-js-docs-pr repository, but I can help by assigning your issue to the right team. You could also consider checking the [questions tagged office-js tag on StackOverflow](https://stackoverflow.com/questions/tagged/office-js) to see if anyone has resolved an issue like yours. 

Thanks again, 
-Alison

**Comment by nikhilism15** [comment]
The code goes something like this:
`
let sheet: Excel.Worksheet = context.workbook.worksheets.getActiveWorksheet();
        let tables = sheet.tables.load("name");
        context.runtime.load("enableEvents");
        await syncContext(context);
        if (tables.items.length == 1 && tables.items[0].name.startsWith("companyTable")) {
            let table = tables.items[0];
            let selectedRange = context.workbook.getSelectedRange();
            selectedRange.load("address");
            await syncContext(context);
            table.load("rows/count");
            table.load("columns/count");
            sheet.load("format/protection");
            await context.sync().catch((ex) => {
        console.log(ex);
        loadMessageDialog(JSON.stringify(ex));
    });
// Here I write other business logic
`

The issue comes during the context sync. It looks like the selectedRange address will be INaN every time it's called from a button in the custom tab. But the same range will actually give the right address if the method is called from a button in the react app in the taskpane.

**Comment by alison-mk** [comment]
Hi @nikhilism15, thank you for providing some code. I'm not able to test with this code and reproduce the bug, however, because it's incomplete. Please provide everything within your add-in's src directory (all files within the commands and taskpane directories), plus the manifest.xml. No need to include business logic, as long as we can reproduce the `context.workbook.getSelectedRange()` tab issue with the code you provide. Thanks again!

**Comment by nikhilism15** [comment]
Thank you Alison for responding. I am not sure but I myself am not able to reproduce the issue anymore. We can close this issue for now. If it reappears I will raise a separate ticket.

Thank you for your help!
