### ISSUE TITLE
Running Office Node JS SSO from host environment

### ISSUE THREAD

**Issue by Mike-tech** [OfficeDev/office-js-docs-pr#2279]
Hi there

I have installed and setup the Office Node JS SSO typescript using Yo Office. It works fine locally including the SSO. But when I deploy the addin using the deployment documentation [here ](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish-add-in-vs-code). When I tried to run the manifest when running from the deployed Azure static website, the SSO doesn't work. I get 404:
GET https://myhostname.web.core.windows.net/auth?_=1603205168265 404 (The requested content does not exist.)

I have a feeling a static website host is not for sso application. Can you advise how to host the SSO from a hosting location (not localhost)?

Thanks

**Comment by AlexJerabek** [comment]
Thank you for the questions @Mike-tech. 

@davidchesnut, can you please investigate?

**Comment by davidchesnut** [comment]
Hi @Mike-tech ,

Sorry for the late reply on this. We've reproduced this same behavior, and are looking into how to get an SSO-based add-in to deploy to Azure. I'll reply once we have the answer. Thanks!

**Comment by davidchesnut** [comment]
Hi @Mike-tech ,

It looks like what is happening is the SSO code is attempting to store and get the app secret in Windows credential manager. This likely won't work on an Azure deployment. The code is in the [Office-Addin-SSO package](https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages/office-addin-sso/README.md). See  https://github.com/OfficeDev/Office-Addin-Scripts/blob/4ec80a9d247e1764c40559cdc978fe1877d81ee2/packages/office-addin-sso/src/ssoDataSettings.ts#L40 which has code as follows:

```
export function getSecretFromCredentialStore(ssoAppName: string, isTest: boolean = false): string {
    try {
        switch (process.platform) {
            case "win32":
                const getSecretFromWindowsStoreCommand = `powershell -ExecutionPolicy Bypass -File "${defaults.getSecretCommandPath}" "${ssoAppName}" "${os.userInfo().username}"`;
                return execSync(getSecretFromWindowsStoreCommand, { stdio: "pipe" }).toString();
            case "darwin":
                const getSecretFromMacStoreCommand = `${isTest ? "" : "sudo"} security find-generic-password -a ${os.userInfo().username} -s ${ssoAppName} -w`;
                return execSync(getSecretFromMacStoreCommand, { stdio: "pipe" }).toString();;
            default:
                const errorMessage: string = `Platform not supported: ${process.platform}`;
                throw new Error(errorMessage);
        }
    } catch {
        return '';
    }
}

```
Since that code is in a package, you can't update it to handle the Azure scenario. However you can get the same code from the [Office-Add-in-NodeJS-SSO sample](https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO). And you find the same code at https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO/blob/master/SSOAutoSetup/src/configure/ssoAppDataSetttings.js (which you can modify.)

So it might make more sense to start with this code sample, and modify it to handle the secret for Azure. I'm still working with the engineering team to figure out the specific steps to modify this code for Azure deployment. 

BTW: We are also tracking this issue [here](https://github.com/OfficeDev/Office-Addin-Scripts/issues/342) where there is additional information.

Thanks,
David

**Comment by Mike-tech** [comment]
Hi @davidchesnut 

Thanks for the information on alternative method of hosting sso. I have two follow up questions regarding this:

1. Is there a TypeScript version of the sample template Office-Add-in-NodeJS-SSO?

2. To deploy the Office-Add-in-NodeJS-SSO project template - is the target host environment also Azure Storage Static Website? So running npm run build and deploying from the dist folder?

Regards

**Comment by davidchesnut** [comment]
Hi @Mike-tech,

No, right now that sample is only JavaScript. Although JavaScript should run fine under TypeScript. Or if you are working to mix and match the JS pieces from the sample in a TS project, you could use the office-addin-sso package as a reference. For example, the TypeScript versions of the secret handling functions are [here](https://github.com/OfficeDev/Office-Addin-Scripts/blob/4ec80a9d247e1764c40559cdc978fe1877d81ee2/packages/office-addin-sso/src/ssoDataSettings.ts#L40).

Don't use the Azure Storage Static Website. You'll want to deploy to an Azure app service. The sample works by sending API calls to itself, which a static site can't handle (this is what is causing the 404 error you see.) This deployment piece is what I'm working with the engineering team on.

Cheers,
David

**Comment by Mike-tech** [comment]
Ok @davidchesnut, points noted.

Many thanks

**Comment by rijulaggarwal16** [comment]
Is there any update on this? I have a prod server running elsewhere. However, getting the same issue. Is this solved?

**Comment by davidchesnut** [comment]
Hi @rijulaggarwal16 sorry for not spotting this issue had reopened. We've made updates to the article [Deploy a single sign-on (SSO) Office Add-in to Microsoft Azure App Service](https://learn.microsoft.com/office/dev/add-ins/publish/deploy-office-add-in-sso-to-azure). Hope this works for you! Thanks!
