### ISSUE TITLE
fix the styles

### ISSUE THREAD

**Issue by Bartolomeus-649** [OfficeDev/office-js-docs-pr#2293]
fix the styles
![image](https://user-images.githubusercontent.com/7513795/97406677-e3a38580-18f9-11eb-87bf-02288a8c7635.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5942e59a-9e08-d7bc-f170-698882a84936
* Version Independent ID: d8730c4d-bf3f-c92d-9c4a-418ea5848538
* Content: [Localize custom functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-localize)
* Content Source: [docs/excel/custom-functions-localize.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-localize.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @Bartolomeus-649, 

Thank you for the feedback on the docs.microsoft.com platform. I'll pass your feedback along to the right team.

Since this repo is used to track issues specific to the Office Add-ins documentation, I'll go ahead and close the issue. If you have further feedback about the docs.microsoft.com platform, please raise the issues here: https://github.com/MicrosoftDocs/feedback/issues
