### ISSUE TITLE
How do I run the script on heroku? I am getting an h10 error all the time

### ISSUE THREAD

**Issue by irfancue** [OfficeDev/office-js-docs-pr#2302]
I am trying to deploy the app on heroku and I am getting following error message:

`2020-11-02T21:57:23.551556+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/commands.html?_host_Info=Outlook$Mac$16.00$en-GB$$$$0" host=sm-outlook-plugin.herokuapp.com request_id=fa3897d3-0e73-4a36-b30e-278998b13b62 fwd="51.154.42.87" dyno= connect= service= status=503 bytes= protocol=https
2020-11-02T21:57:24.875646+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=sm-outlook-plugin.herokuapp.com request_id=78ae6950-8fc0-4a8e-95ee-40f980b6c37e fwd="51.154.42.87" dyno= connect= service= status=503 bytes= protocol=https`

`  "config": {
    "app-to-debug": "outlook",
    "app-type-to-debug": "desktop",
    "dev-server-port": 3000
  },
  "scripts": {
    "build": "webpack -p --mode production --https false",
    "build:dev": "webpack --mode development --https false",
    "build-dev": "webpack --mode development --https false && echo . && echo . && echo . && echo Please use 'build:dev' instead of 'build-dev'.",
    "dev-server": "webpack-dev-server --mode development",
    "lint": "office-addin-lint check",
    "lint:fix": "office-addin-lint fix",
    "prettier": "office-addin-lint prettier",
    "start": "office-addin-debugging start manifest.xml",
    "start:desktop": "office-addin-debugging start manifest.xml desktop",
    "start:web": "office-addin-debugging start manifest.xml web",
    "stop": "office-addin-debugging stop manifest.xml",
    "validate": "office-addin-manifest validate manifest.xml",
    "watch": "webpack --mode development --watch"
  },`

**Comment by AlexJerabek** [comment]
Hi @irfancue, 

I'd recommend asking this question on [Stack Overflow](https://stackoverflow.com/questions/tagged/office-js). Be sure to include both the "office-js" and "heroku" tags. That way, people from both communities can help diagnose the error.

Since the Office Add-ins documentation is agnostic about the cloud service to use, this seems out of scope for this repo. I'll close the issue, but I'd encourage you to post the link to your Stack question in the comments to help others find the answers later.
