### ISSUE TITLE
Add-In Sample Failing

### ISSUE THREAD

**Issue by elthombre** [OfficeDev/office-js-docs-pr#2529]
I have an outlook.office.com account and I created a developer ID per the instructions. It fails to properly launch giving me a 401 "unauthorized" error.

It's so frustrating when your samples don't work. As a developer... it just makes you wanna pull your hair out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 930ce4fc-c8b8-f756-f03f-a716f1ef7883
* Version Independent ID: 753a2e38-9430-25bb-5409-b7eed9c88e47
* Content: [Build your first Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/outlook-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/outlook-quickstart.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @elthombre,

I'm sorry to hear about your frustration. Can you please tell us where in the quick start you're encountering the error? Also, are you using the [yeoman generator](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator) or [Visual Studio](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=visualstudio) to create your add-in?

**Comment by elthombre** [comment]
Presently, I'm using the Visual Studio version. It launches the new window in Chrome where I receive this error:

"Something went wrong and we couldn't start this add-in..."

When I bring up the 'Developer Tools' -> Console, there's a bunch of 404 errors.

I will ad that I had to change the "~remoteAppUrl" in the source to point to the localhost in order to get it to run.

Also, if I do not close the OWA window when I stop debugging, the context add-in options within the message window don't show up

**Comment by AlexJerabek** [comment]
Thank you for sharing those details. Are you encountering the same issues when following the yeoman generator path?

@ElizabethSamuel-MSFT. are you able to repo the issue in Visual Studio?

**Comment by ElizabethSamuel-MSFT** [comment]
@elthombre You should be able to keep ~remoteAppUrl in the manifest. We'll investigate the issues you're facing.

It's great that you joined the developer program! If you haven't already read them, can you also see if the [developer program docs](https://docs.microsoft.com/office/developer-program/microsoft-365-developer-program) are helpful with configuring your tenant/account?

**Comment by elthombre** [comment]
The problem with the Yeoman version of the tutorial is that its functionality is not the same.

**Comment by ElizabethSamuel-MSFT** [comment]
@elthombre I haven't been able to repro your situation.

What I did:
- Created a dev program subscription and [set it up](https://docs.microsoft.com/office/developer-program/microsoft-365-developer-program-get-started#set-up-your-subscription)
- In VS 2019, created a new projects and made updates per the quick start instructions (Note: I did NOT replace ~remoteAppUrl in the manifest)
- In VS, set browser to Google Chrome then pressed "Start" to start debugging
- In the "Connect to Exchange email account" dialog box, entered user name (e.g. username@domain*.onmicrosoft.com) and password of the account I created in dev program subscription setup
- VS automatically opened outlook.office365.com in Chrome. I had no emails so I sent myself one then clicked on it to view in the Reading Pane. Clicked ellipsis (...) for more actions then clicked the name of the add-in in the menu. The task pane opened with the message properties as expected.

If I missed anything in my repro, let me know so I can include and try again.

Also, can you clarify what you mean by "if I do not close the OWA window when I stop debugging, the context add-in options within the message window don't show up"? Do you mean the context menu if you, for example, right-click in the message? If that's what you mean, then that's expected since Outlook web add-ins are not included in that menu whether or not you're debugging.

Thanks.

**Comment by elthombre** [comment]
> @elthombre I haven't been able to repro your situation.
> 
> What I did:
> 
> * Created a dev program subscription and [set it up](https://docs.microsoft.com/office/developer-program/microsoft-365-developer-program-get-started#set-up-your-subscription)
> * In VS 2019, created a new project and made updates per the quick start instructions (Note: I did NOT replace ~remoteAppUrl in the manifest)
> * In VS, set browser to Google Chrome then pressed "Start" to start debugging
> * In the "Connect to Exchange email account" dialog box, entered user name (e.g. username@domain*.onmicrosoft.com) and password of the account I created in dev program subscription setup
> * VS automatically opened outlook.office365.com in Chrome. I had no emails so I sent myself one then clicked on it to view in the Reading Pane. Clicked ellipsis (...) for more actions then clicked the name of the add-in in the menu. The task pane opened with the message properties as expected.
> 
> If I missed anything in my repro, let me know so I can include and try again.
> 
> Also, can you clarify what you mean by "if I do not close the OWA window when I stop debugging, the context add-in options within the message window don't show up"? Do you mean the context menu if you, for example, right-click in the message? If that's what you mean, then that's expected since Outlook web add-ins are not included in that menu whether or not you're debugging.
> 
> Thanks.

Yes, right-click context menu
