### ISSUE TITLE
Is sessionStorage still supported?

### ISSUE THREAD

**Issue by lafe** [OfficeDev/office-js-docs-pr#2535]
The page states that state can also be stored through browser techniques like localStorage or sessionStorage. It also links to [an example](https://github.com/OfficeDev/Excel-Add-in-JavaScript-PersistCustomSettings) that demonstrates this approach. However, the example is now archived without giving a reason for this and a [previous issue on GitHub](https://github.com/OfficeDev/office-js-docs-pr/issues/1458) seems to indicate that sessionStorage is not supported anymore.

Is the article still up to date or has the usage of localStorage and sessionStorage been deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b683480b-a4fe-97ba-64f9-45ecfe829bf4
* Version Independent ID: a0993174-18dd-9594-9c3c-102d078e2217
* Content: [Persisting add-in state and settings - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings)
* Content Source: [docs/develop/persisting-add-in-state-and-settings.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/persisting-add-in-state-and-settings.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @lafe,

Thanks for the question. Let me tag @davidchesnut and @jeremy-msft to help out. 

In the meantime, can you tell us what application you're developing an add-in for (Excel, Word, etc)?

**Comment by lafe** [comment]
The Add-In would be for Word, Excel and PowerPoint.

**Comment by davidchesnut** [comment]
Hi @lafe  

Very sorry for the late reply as I missed this on my radar. Yes you can use localStorage and sessionStorage. Of course, just be aware of potential pitfalls (security, browser version support...) which would apply to any web project. Please let us know if you are running into any issues.

In the meantime I've added a task (internal: 5401728) to update the article and sample so that it is not pointing to archived material. Also there are some related custom function storage mechanisms it should mention that I'll link in.

Thanks!
David

**Comment by lafe** [comment]
@davidchesnut Thank you for the response!
