### ISSUE TITLE
Issue with Sideloading Instructions for Outlook Add-In on iPad

### ISSUE THREAD

**Issue by dvshkn** [OfficeDev/office-js-docs-pr#2615]
Content: [sideload-an-office-add-in-on-ipad-and-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md)

I have a development build of an Outlook add-in that I'm trying to sideload onto an iPad for testing. I've followed the macOS Catalina instructions in the docs listed above, but the Outlook app does not show up in the Files section of Finder when the iPad is connected to a computer with a cable. For good measure I installed the Word app also, and that app _does_ show up in Finder.

![image](https://user-images.githubusercontent.com/1450559/114324980-4d979c00-9ae2-11eb-8479-f79024169c47.png)

Are there different instructions for sideloading Outlook add-ins? Or are these instructions out of date with respect to Outlook add-ins?

**Comment by AlexJerabek** [comment]
Hi @dvshkn,

Thank you for raising this issue. @macOutlookExtensibility, can you please provide assistance?

**Comment by ElizabethSamuel-MSFT** [comment]
@dvshkn The docs have since been updated. Please take a look at the guidance for [sideloading an Outlook add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing).

I'll go ahead and close this but if you're still having issues, let us know by creating a new issue or responding on this thread as appropriate.

Thanks.
