### ISSUE TITLE
Catalog Url Error

### ISSUE THREAD

**Issue by mscaitlina** [OfficeDev/office-js-docs-pr#266]
When I pasted the path to the folder that contains my add-in, I get the error "Sorry, the location you entered isn't correct - did you forget to use "https:"//"?" I assume I'm doing something wrong. I'm not using a web address, I'm simply trying to point to the folder on my computer that has the code. For context, I started from the "Build your first Excel add-in using jquery" and got directed here as part of "Try it out."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ddce0bd-5c66-c2cb-0640-ee4d5bd401c5
* Version Independent ID: b5d4bc26-a43e-4a85-e7d5-fe4fc4ec3d0d
* Content: [Sideload Office Add-ins for testing](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins)
* Content Source: [docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @mscaitlina,
I have mine pointing at a local folder. My trusted catalog address something like `\\AlexPC\AddInFolder`.
Did you follow the instructions to [add self-signed certificates as trusted root certificates](https://github.com/OfficeDev/generator-office/blob/master/src/docs/ssl.md)?

**Comment by jayrat** [comment]
I've followed these instructions with an app that creates a custom tab.  It works on my computer, but others try to sideload it and they get the option to "Insert" instead of "Add" in word and it only opens the task panel and doesn't add the Custom Tab into the Ribbon.

**Comment by AlexJerabek** [comment]
Hi @jayrat,
Thank you for sharing your issue. Could I get some clarification on the problem? 

Are you hosting your app locally or elsewhere? Where are the others accessing your app from? 

Is the "Insert" versus "Add" from the Office Add-ins manager? If there's a different UI, they probably have an older version of Office.

**Comment by jayrat** [comment]
@AlexJerabek,
Thank you for relying.

I've tried two methods.  The first was the share a folder on my computer and have everyone access the manifest file from there.  The current method is to send the manifest file to everyone and have them place it into a folder on their computer and share it.  We all use the version of Word that is provided through the company's office 365.  That means we should all have the same version of word, right?

The screen is the Office Add-ins that you get to through the Insert Tab on the Ribbon.  Once you add the shared folder into your trusted add-in catalogs you get a shared folder tab and that is where the add-in I create shows up.

The add-in itself works, but everyone else only gets the Insert button at the bottom instead of Add and they have to repeat those steps every time they want to use the add-in.

**Comment by AlexJerabek** [comment]
I know @TCourtneyOwen has been working on sideloading recently. Any thoughts on the issue?

**Comment by jayrat** [comment]
@AlexJerabek, 
I've discovered what is going on.  Most of the people in my group have installed Office 2016 Plus Professional and not the install that we have though Office 365 Business.  They are only on Version 16.0.46 and I am on 16.0.9.. I have one person reinstall Office from the Office 365 dashboard and it is working properly for him now.

**Comment by AlexJerabek** [comment]
@jayrat 
Great to hear! I'll close this issue for now. Feel free to reopen it if you encounter further issues.
