### ISSUE TITLE
Custom Function - TypeError: Network request failed (working fine in online , failing only in desktop verison)

### ISSUE THREAD

**Issue by Gowthambabug** [OfficeDev/office-js-docs-pr#2734]
async function getStarCount(userName = "OfficeDev", repoName = "office-js") {
  //You can change this URL to any web request you want to work with.
 // const url = "https://api.github.com/repos/OfficeDev/office-js";
  const url = "https://localhost:44355/api/values/5";
  const response = await fetch(url);
  //Expect that status code is in 200-299 range
  if (!response.ok) {

    throw new Error(response.statusText);
  }
  return response
}

Followed this documentation as well 
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-runtime#requesting-external-data 

Executed this command as well  - CheckNetIsolation LoopbackExempt -a -n="microsoft.win32webviewhost_cw5n1h2txyewy"

but no luck

**Comment by AlexJerabek** [comment]
Thanks for reporting this @Gowthambabug.

@alison-mk, can you please investigate?

**Comment by davidchesnut** [comment]
Hi @Gowthambabug,

It looks like you are trying to fetch from an API server? That URL looks a lot like an ASP.NET localhost URL. Be sure you added that URL to the [AppDomain](https://docs.microsoft.com/office/dev/add-ins/reference/manifest/appdomain) list in your manifest otherwise you could be blocked from calling it. 

```xml
<AppDomains>
    <AppDomain>https://localhost:44355</AppDomain>
  </AppDomains>
```

It's also possible the defaults for fetch in the context of running on desktop are not sending the expected headers for your localhost server. You may need to explicitly set any required headers for your server.

If you are still stuck, please ask on our Microsoft Q&A site at https://aka.ms/office-js-dev-questions. Or StackOverflow with the [office-js] tag.

Hope this helps,
David
