### ISSUE TITLE
Outlook for Mac - Mailbox 1.10 API support

### ISSUE THREAD

**Issue by jozefizso** [OfficeDev/office-js-docs-pr#2747]
Hi, when will the **Microsoft Outlook for Mac** support the **Mailbox 1.10** API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7c255e4-d0f9-5b35-bec0-fdd690bdeff1
* Version Independent ID: dae8b049-0f53-ea13-9998-cfb4362b7553
* Content: [Office client application and platform availability for Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability)
* Content Source: [docs/overview/office-add-in-availability.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/overview/office-add-in-availability.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @jozefizso,

We are working to bring API parity to Outlook on Mac. However, we do not have a concrete timeline. I would encourage you to tune in to the next [Office Add-ins Community Call ](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins-community-call). There, you can hear the latest information about the platform and ask the product teams for the latest release timelines.

I'm going to close this issue, because there's nothing actionable we can do in the documentation. Please open a new issue if you need further assistance. Thanks!
