### ISSUE TITLE
IE11 / Win7 End of Support

### ISSUE THREAD

**Issue by rh78** [OfficeDev/office-js-docs-pr#2756]
Hello it would be good to state how the end to IE11 support by Microsoft affects the requirements for Addin certification. Will we still have to support Win7 and IE11 or is this also expiring?

It is honestly a nightmare to keep that support up and running, even if just considering security issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca0e1fb1-b0ec-bb06-795a-add2b1f5c476
* Version Independent ID: b22528ae-f6cb-1cc7-8342-e298b1e5ce6c
* Content: [Support Internet Explorer 11 - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/support-ie-11)
* Content Source: [docs/develop/support-ie-11.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/support-ie-11.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
I'm seeking more information internally. In the meantime, I believe the end of support for IE does not change much for Office Add-ins. There is still a large installed base of one-time purchase (not subscription Office 365) Office customers and add-ins are still required to support them, which means continuing to support IE since that is the browser webview that add-ins use on non-subscription Office.

**Comment by Rick-Kirkham** [comment]
I have confirmed internally what I said in my previous comment. I will try to make this clearer in the documentation.
