### ISSUE TITLE
Examples and links to docs please!

### ISSUE THREAD

**Issue by TheTimKiely** [OfficeDev/office-js-docs-pr#2787]
Hi,
It would be very helpful to have an example of implementing a tab bar on a task pane.
Thanks,
Tim

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38551b6a-d42b-c142-cda6-57550492fa65
* Version Independent ID: ee054a87-d61e-a706-08a7-e49c9d26f2a1
* Content: [Navigation patterns for Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/navigation-patterns)
* Content Source: [docs/design/navigation-patterns.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/navigation-patterns.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@TheTimKiely Thanks for asking about this.

@Rick-Kirkham Is this something you can help with?

Thanks.

**Comment by Rick-Kirkham** [comment]
How you implement a tab bar depends on what UI framework you are using (e.g., React, vanilla JS, Vue, etc.). We can't produce implementations for all of them, but we have example implementations in this repo:  [Office Add-in Ux Design Patterns Code](https://github.com/OfficeDev/Office-Add-in-UX-Design-Patterns-Code).

In particular, see [tab-bar](https://github.com/OfficeDev/Office-Add-in-UX-Design-Patterns-Code/tree/master/templates/navigation/tab-bar). There's no JavaScript for that example, but I suspect that the JavaScript for command bar could be adapted: [CommandBar.js](https://github.com/OfficeDev/Office-Add-in-UX-Design-Patterns-Code/blob/master/templates/navigation/navigation-commands/CommandBar.js). 

This add-in uses the tab bar pattern: [Excel-Add-in-JavaScript-SalesTracker](https://github.com/OfficeDev/Excel-Add-in-JavaScript-SalesTracker)

Also, an add-in is basically a web app, so creating a tab bar for an add-in is essentially the same as for any web app. If I search on Bing for "how to implement a tab bar in a web app?", I get some valuable hits, including [How To - Tabs](https://www.w3schools.com/howto/howto_js_tabs.asp).

I'll close this for now, since it does not result in any new documentation items for Microsoft. But you can still add comments.

**Comment by TheTimKiely** [comment]
Thanks @ElizabethSamuel-MSFT  and @Rick-Kirkham 
-Tim
