### ISSUE TITLE
Update Backend database when any user in the organization edits an appointment in his/her calendar

### ISSUE THREAD

**Issue by sohilbhalla** [OfficeDev/office-js-docs-pr#2806]
I have a business requirement where when any user edits an already created appointment in outlook, the event needs to be captured and an backend web api needs to be called to update the database based on the change done in the outlook appointment.

Will the event based outlook add-ins  best suited for this case and can it be used in production apps ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193780ba-aa43-dc5c-fc28-adc96a0fdeda
* Version Independent ID: da41da2b-207e-e976-3491-61672d1e3493
* Content: [Configure your Outlook add-in for event-based activation - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch)
* Content Source: [docs/outlook/autolaunch.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/autolaunch.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
@sohilbhalla - Are you looking for events on changes to some specific fields on the appointment (like recipient added/deleted) or an event for **any** change to the item, say when the body changed? We may be able to help you better or provide alternatives, if available, once we have more details about the use case you're trying to achieve. If you're expecting an event for any generic change to the item, we unfortunately don't have that feature yet and as @ElizabethSamuel-MSFT mentioned, it'd be great to add that to the tech community/upvote if it already exists. If you're targeting specific fields on the appointment, we may be able to help you with that. Let us know.

**Comment by sohilbhalla** [comment]
Hi, first of all sorry for the late response. We had a long holiday here :) .

So here is a brief description about the business case we have.

We are syncing the specific outlook appointments with a custom application and are thinking of using outlook add ins to capture the events of changes happening in the appointments from outlook and update the application back. I can understand making a generic event for any change in the appointment is not feasible as of now. 

As part of the first MVP we are mostly looking for the events of the following changes in the appointment in outlook as per the priority order.

1) Deleting or cancelling the appointment
2) Change in the appointment start or end date
3) Change in the recipients
4) Change in the Subject / Title
5) Change in the meeting location
6) Change in the meeting body or content

I hope this clarifies the business case and our requirement, happy to hear from you the suggestion and the best possible approach as of today.

Thanks for the support, appreciated.

**Comment by exextoc** [comment]
Since you want to receive notifications on your backend when a calendar event changes, you may consider using the Graph API from your backend to subscribe to [change notifications](https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0) on [events](https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0) (calendar appointments). This would allow you to capture changes to events, even when your add-in is not running, and only when the user actually saves/sends the appointment.

I believe this would return all event changes, and your backend would need to filter the results to just the items it is interested in.

Does this meet your requirements?

**Comment by sohilbhalla** [comment]
Yes I did think of this solution, but the change notifications for the events are user based `/users/{id}/events` , so we have to create change subscriptions for every user in the organization and keep it alive to capture the changes made by any user. If we are talking about an organization with 10,000 plus employees, we might end up creating 10,000 change subscription and maintaining it.

I am not quite sure about the upper limit of the number of subscriptions that can be created for the events by an application.
[resource limitation](https://docs.microsoft.com/en-us/graph/webhooks#azure-ad-resource-limitations)

What are your thoughts?

**Comment by exextoc** [comment]
Maintaining a huge number of subscriptions doesn't seem like a good idea.
Also, a maximum of 1000 active subscriptions per mailbox for all applications is allowed, so that limit could easily be hit after a while if you have a subscription to every appointment changed on a single user's mailbox, unless the subscriptions are deleted after the events have taken place.

Event-Based Add-ins also have some form of limitations.

1. Not all changes made to an appointment will trigger an event.
2. We do not guarantee that your add-in will be executed or will finish running before the user closes the appointment window.

This means that you could end up in a scenario where you sometimes get notifications and other times you don't get them because the user closed the appointment window, or closed Outlook before we finished running your add-in.
