### ISSUE TITLE
Outlook mobile icon size

### ISSUE THREAD

**Issue by jean-wujingyi** [OfficeDev/office-js-docs-pr#2857]
Hello, a question about icon configuration.
From Office articles, it says Mobile add-ins minimally must support 25x25, 32x32 and 48x48 pixel icons. But from example code, this Image element for 25px is actually provided by 16px-icon. 
Is it a typo or something?
![image](https://user-images.githubusercontent.com/66811843/128325455-e0c7fd0c-8775-42e3-b1e9-c539c5f73d19.png)
![image](https://user-images.githubusercontent.com/66811843/128325484-38fd2d79-d98c-4d43-94b3-8d1bcb483180.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d8e5f40-63fe-f71c-a021-4842a26ef9ec
* Version Independent ID: 75dfa44c-08f3-0328-b4a1-26014a305e51
* Content: [Icon element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/icon)
* Content Source: [docs/reference/manifest/icon.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/icon.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @jean-wujingyi,
Thanks for raising this issue. @ElizabethSamuel-MSFT, could you please investigate?

**Comment by jean-wujingyi** [comment]
any updates?

**Comment by ElizabethSamuel-MSFT** [comment]
@jean-wujingyi From my initial investigation, a couple of the required sizes for mobile are not supported by the Icon manifest element. As such, I believe that the current guidance is correct, that you'll need to scale a supported size icon for mobile purposes.

Are you hitting errors or other issues with the current guidance?

Thanks.

**Comment by jean-wujingyi** [comment]
Thanks for your help. No isuues for current stage, just curious about this.

**Comment by jean-wujingyi** [comment]
You mean that 25px icon is not supoorted by Icon manifest element, so we replace it as 16px icon, am I right? 
<img width="541" alt="Screen Shot 2021-08-11 at 9 27 50 AM" src="https://user-images.githubusercontent.com/66811843/128955800-8042c9e2-f077-4f36-9223-f865b13f3669.png">

**Comment by ElizabethSamuel-MSFT** [comment]
@jean-wujingyi Thanks for asking. I've dug into this a bit more and I need to clarify. As you noted, the MobileFormFactor has different requirements for image definitions. The examples we provide show your options when referencing a size that's the same as the resource image (e.g. size="32") and referencing a size that's different (e.g. size="25"). Given the mobile context, I should have said that the [Resources manifest element](https://docs.microsoft.com/office/dev/add-ins/reference/manifest/resources) (rather than the Icon element) has these supported size limitations since the MobileFormFactor uses Icon as well but with size requirements that differ from the other form factors.

So, to answer your last question, while you may not need to reference the 16px image, your image must reference an image from the Resources section that's of a size supported by the Resources section since 25px *is* required by the Icon element when it's under MobileFormFactor but 25px is not a size supported by the Resources section.

You'll also want to verify that the image sizes you're using look good in your mobile add-in.

Note that our example gives you a way to use the 3 sizes required by the Resources section and map them to the required MobileFormFactor sizes as well as to the required sizes for other form factors. You of course have the option to create additional icons of other optional, supported sizes and reference those instead or as well for mobile.

Hope that helps. Let us know if you have further questions.

Thanks.
