### ISSUE TITLE
More specific information regarding internet header quotas in Outlook Add-ins

### ISSUE THREAD

**Issue by rocketedaway** [OfficeDev/office-js-docs-pr#2897]
We are currently have an Outlook Add-in in development and are looking to set headers on outgoing emails. We have scoured the internet and are not able to find out any more specific information about the Internet Header quotas outlined [here](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/internet-headers#recommended-practices).

If the documentation mentions that internet headers on a users Outlook mailbox are a finite resource, the actual limits or an approximation should be included.

If someone could respond to this issue with some more information that would be really appreciated.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac0e08e9-b043-1a03-9505-2b3a9ca95e14
* Version Independent ID: e465cfb6-e349-1d24-30b2-2ea4bc56d976
* Content: [Get and set internet headers - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/internet-headers#recommended-practices)
* Content Source: [docs/outlook/internet-headers.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/internet-headers.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by rstoye** [comment]
My colleagues and I second this. We are currently in the same boat of developing an add-in with header functionality and this information is crucial for the scope of our project.

Furthermore we would be interested to know if the quota can be changed via exchange settings / rules.

Thanks in advance.

**Comment by exextoc** [comment]
Could you describe your scenario in more detail? How many internet headers do you plan on adding to the item? Generally, it is good practice to try to re-use headers that change dynamically.

**Comment by rstoye** [comment]
I'd rather you tell us more about these internet header limitations, so that we have some concrete information that we can leverage in our talks with the customer, but for the sake of argument I can go into a little more detail.

Our customer has a mail gateway that takes incoming mails, reads the required custom headers, validates these information and does some further voodoo we don't know anything about. The add-in we're building is used to add information to each mail and their attachments. Attachments can be marked as important and confidential among other things. The gateway expects a header for each attachment with the name of the attachment as part of the header name. 

We understand that a dynamic header name does not abide by the guidelines mentioned in the Microsoft docs. But that's why we need more information about the quotas.

**Comment by rocketedaway** [comment]
Well said @rstoye

**Comment by exextoc** [comment]
internet headers are ultimately are mapped to Named Properties and as such there is a limit specified in Exchange as per [this documentation](https://docs.microsoft.com/en-us/previous-versions/office/exchange-server-2007/bb851492(v=exchg.80)#named-properties-limits).

**Comment by rstoye** [comment]
Thank you for the information.

> As a reminder, when the quota is exhausted, you can't create any more internet headers on that mailbox

Is there a way to clear a mailbox of internet headers or named properties for that matter?

**Comment by rocketedaway** [comment]
Thanks @exextoc!

**Comment by exextoc** [comment]
> Is there a way to clear a mailbox of internet headers or named properties for that matter?
There currently isn't a straightforward or an easy way to do this and is something that's not recommended to go after. For an OnPrem server you'll need to move the mailbox to another database and use the DoNotPreserveMailboxSignature switch that'll reset the NamedProperties. If its Office365, you'll need to engage with support and they may be able to help.

**Comment by rstoye** [comment]
Ok thank you. I have no further questions.
