### ISSUE TITLE
Custom functions require npm 6

### ISSUE THREAD

**Issue by EricForgy** [OfficeDev/office-js-docs-pr#2987]
I'm trying to create a custom function following the instructions here:

https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows

My first issue was with `agentkeepalive`. I don't know what that is, but I could not get `yo` to work without it, so I had to

```
> npm install -g agentkeepalive --save
```

If this step is really necessary, it should be documented. I think there is an assumption that a lot of packages are already installed globally. I had a similar issue with webpack, which I guess was assumed to be installed globally. That should also be documented.

Next, after getting `yo` to work, I was notified of a new version of `npm`, so followed the recommendation and ran:

```
> npm install -g npm@8.0.0
```

From there, I followed the instructions here:

https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows#build-your-first-custom-functions-project

And got some notice about data so I had to run:

```
> npx ofice-addin-usage-data off
```

This should be documented too I think.

Trying again, I am getting an error:

```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: excel-custom-functions-js@2.0.0
npm ERR! notsup Not compatible with your version of node/npm: excel-custom-functions-js@2.0.0
npm ERR! notsup Required: {"node":">=14 <15","npm":">=6 <7"}
npm ERR! notsup Actual:   {"npm":"8.0.0","node":"v14.17.0"}
```

If I am reading this correctly, it is saying I need npm version 6 to run any of these samples? I hope that is not right. I even went back to npm v.7.24.2 and still get the same error, but obviously with "actual" replaced with `{"npm":"7.24.2","node":"v14.17.0"}`.

How can I get these samples to work with newer versions of npm?

As I search other parts of the docs, I always get the same error above.

I urgently need to convert some VBA to JavaScript. How can I get this to work? I'll try SO, but thought I'd create this issue because I think the documentation also needs improvement.

Thanks

**Comment by millerds** [comment]
As far as the npm version requirement . . . it's there because there were changes to npm in v7 (didn't even know that v8 was out) that broke the templates we generated.  We have fixed some of those, but we don't have it working just yet and so the requirement remains at v6 (which is what is installed with the LTS version of node last I knew).  

You can remove the requirement by deleting that part of the package.json file, but I can't say that things are going to work right.  If we figure it out we'll update the templates.  If you figure it out please let us know so we can pass this on to others.
