### ISSUE TITLE
Remove the IE11 support requirement

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js-docs-pr#3072]
Please raise this with the leadership team. 

I think since Internet Explorer is officially sunset, by this point of time the requirement to support of IE11 in "Predictable behaviour" should be opt-out-able.

I propose to be able to opt out of IE11 support on the product listing page. 

IMO the necessity to polyfill like it's 1999 and to downcompile to ES5 is too strict in 2021.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb06c24b-9d11-9cc5-2e98-561601452638
* Version Independent ID: abda21d9-6e80-8319-c56f-004658014e3c
* Content: [Enable single sign-on for Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins)
* Content Source: [docs/develop/sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/sso-in-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @wh1t3cAt1k,

Thanks for flagging this as a development concern, We'll pass this along to the appropriate teams. 

In the meantime, could you please create an idea asking to remove IE11 support requirements for Office Add-ins over in [Microsoft Tech Community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)? We use Tech Community to help prioritize issues and gauge customer needs.

I'm going to close this issue, since there's nothing actionable that can be done from the documentation side. We'll be sure to let the community know if and when our support requirements change.

**Comment by Rick-Kirkham** [comment]
@wh1t3cAt1k The requirement that add-ins still support IE can be misleading. It is acceptable for the add-in to gracefully fail when the user agent is IE. See this article: [Support Internet Explorer](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/support-ie-11), especially the section **Determine at runtime if the add-in is running in Internet Explorer**.

**Comment by wh1t3cAt1k** [comment]
@Rick-Kirkham this is excellent news! 

Does this also apply to Edge Legacy?

![image](https://user-images.githubusercontent.com/5159662/143265959-c91f1f49-97e9-49de-9d45-34e891cf16b1.png)

This will allow us to make use of native `await import()` features and finally switch the module system to ES from CommonJS.

**Comment by AlexJerabek** [comment]
Hi @wh1t3cAt1k,

I believe the same is true for Edge Legacy: a graceful failure that helps users understand your support story is acceptable. @JuaneloJuanelo can confirm.
