### ISSUE TITLE
Will we be getting add-on support using Angular like excel for word as well?

### ISSUE THREAD

**Issue by dvanurag1308** [OfficeDev/office-js-docs-pr#308]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e380a7-6e2e-ada8-d297-3fd5018a1958
* Version Independent ID: f23490e8-6eeb-f2d5-6c94-69e3c9ed83f4
* Content: [Build your first Word add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=visual-studio)
* Content Source: [docs/quickstarts/word-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/word-quickstart.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
I will create a user request for this idea. In the meantime, you can use the [Excel Angular Quickstart](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-angular) with a few simple changes. When you get to the question "Which Office client application would you like to support?" answer "Word" instead of "Excel". In the step where you modify **src/app/app.component.ts**, Replace "Excel" with "Word" in both places. Then replace the two lines 

```
const range = context.workbook.getSelectedRange();
    range.format.fill.color = 'green';
```

With these lines:

```
const range = context.document.getSelection();
        range.font.color = "red";
```
Then after step 1 of the **Try it out** section, type some text in the document, highlight part of it, and press the button to see the font change to red.
