### ISSUE TITLE
Information missing on porting custom functions to TypeScript

### ISSUE THREAD

**Issue by daniel-ezee** [OfficeDev/office-js-docs-pr#3118]
I'm trying to get an Excel custom function ported from JavaScript to TypeScript. It is not clear in this document (or elsewhere) how to define a custom function in TS. In particular, this code snippet from FunctionFile.ts/js does not work in TypeScript:

  CustomFunctionMappings.ADD = add;
  CustomFunctionMappings.INCREMENT = increment;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b888399c-fe96-0934-00ce-86db8fa8cf5b
* Version Independent ID: 2c5d24e8-5639-42b1-4d12-119f89591550
* Content: [Convert an Office Add-in project in Visual Studio to TypeScript - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/convert-javascript-to-typescript)
* Content Source: [docs/develop/convert-javascript-to-typescript.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/convert-javascript-to-typescript.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by alison-mk** [comment]
Hi @daniel-ezee, thank you for submitting an issue. 

Have you tried the [Custom functions tutorial](https://docs.microsoft.com/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions)? This tutorial shows how to use the `yo office` generator to create a custom functions add-in. You can choose TypeScript instead of JavaScript when following the tutorial. The yo office generator will then create a custom functions add-in, with a couple custom functions already defined in TypeScript in the /src/functions/functions.ts file. You'll only need to complete the first section of the tutorial, **Create a custom functions project**, to create the sample add-in.

To define a new custom function in the add-in after completing the first tutorial section, you can follow the existing pattern and add a new custom function in /src/functions/functions.ts, such as: 

```ts
/**
 * Adds three numbers.
 * @customfunction
 * @param first First number
 * @param second Second number
 * @param third Third number
 * @returns The sum of the three numbers.
 */
export function addThreeNumbers(first: number, second: number, third: number): number {
  return first + second + third;
}
```

After adding your custom function to /src/functions/functions.ts, run `npm run build` in the command prompt to rebuild the project. Next, check /dist/functions.json to confirm that your new custom function (addThreeNumbers) is defined in the JSON. It will look like this: 

```json 
        {
            "description": "Adds three numbers.",
            "id": "ADDTHREENUMBERS",
            "name": "ADDTHREENUMBERS",
            "parameters": [
                {
                    "description": "First number",
                    "name": "first",
                    "type": "number"
                },
                {
                    "description": "Second number",
                    "name": "second",
                    "type": "number"
                },
                {
                    "description": "Third number",
                    "name": "third",
                    "type": "number"
                }
            ],
            "result": {
                "type": "number"
            }
        },
```

To use your new custom function in Excel, run `npm run start` in the command prompt. Let me know if you have any further questions. 

Cheers, 
Alison

**Comment by alison-mk** [comment]
Hi @daniel-ezee, I didn't intend for the bot to close this issue. My mistake. If you have any more questions, you are welcome to reopen the issue. I'll be happy to provide further information! 

Alison

**Comment by daniel-ezee** [comment]
Hi Alison, 

Sorry for the delay. 

I have indeed found the Yeoman custom functions tutorial and made this work with TypeScript. I have also successfully been able to use Visual Studio to create a custom function in JavaScript. I have also been able to convert an add-in project (without custom functions) from JavaScript to TypeScript using the information in [Convert an Office Add-in project in Visual Studio to TypeScript](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/convert-javascript-to-typescript).

However, I want to use Visual Studio, TypeScript and implement a custom function. This is the part that I can't quite make work. How do I e.g. convert the following working JavaScript code to TypeScript:

```JavaScript
function add(first, second) {
    return first + second + 0.123;
}

function increment(incrementBy, callback) {
    var result = 0;
    var timer = setInterval(function () {
        result += incrementBy;
        callback.setResult(result);
    }, 1000);

    callback.onCanceled = function () {
        clearInterval(timer);
    };
}

CustomFunctionMappings.ADD = add;
CustomFunctionMappings.INCREMENT = increment;
```

**Comment by AlexJerabek** [comment]
Reopening, as per @daniel-ezee's request. @alison-mk, can you please take another look?

**Comment by alison-mk** [comment]
Hi @daniel-ezee, 

I have a couple questions and suggestions. 

1. Which version of Visual Studio are you using? 
2. If you're using a TypeScript compiler, try turning off any minimization to ensure that the names of your functions aren't minified. 
3. Are you seeing any errors reported to your console? 
4. Are you using runtime logging? Sometimes you can catch custom functions errors with runtime logging. 
5. What is the origin of these CustomFunctionsMappings lines in your JavaScript? Were they part of a legacy project? 
```
CustomFunctionMappings.ADD = add;
CustomFunctionMappings.INCREMENT = increment;
```

The CustomFunctionMappings lines might correlate to the TypeScript export syntax. For example: 
```
export function add(first, second) {
    ...
}

export function increment(incrementBy, callback) {
    ...
}
```

Thanks,
Alison
