### ISSUE TITLE
Outlook add-in usage

### ISSUE THREAD

**Issue by Tomer-Priel** [OfficeDev/office-js-docs-pr#3156]
Hi, 

Is there any way to know the number of installations I had for my add-in? 
I couldn't find it in the docs.

Thanks.

**Comment by AlexJerabek** [comment]
Hi @Tomer-Priel,

I also couldn't find an answer in our docs or the [admin management docs](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-addins-in-the-admin-center?view=o365-worldwide).  Let me tag @Wenjun-Gong to help out.

Also, how are you deploying your add-in? Is it published to AppSource?

**Comment by Wenjun-Gong** [comment]
@Tomer-Priel, if your app is published via Microsoft AppSource, you can find the usage report from the Partner Center: https://docs.microsoft.com/en-us/office/dev/store/view-usage-report?tabs=workspaces-view 
Note that the report is for the active user who launched your add-in, instead of the number of installations. 

Assign to Outlook add-in team to see whether there is other way to check the usage.

**Comment by exextoc** [comment]
What Wenjun mentioned above is correct, that would be the way to check usage.
