### ISSUE TITLE
Mac advice irrevelant

### ISSUE THREAD

**Issue by mtthwborg** [OfficeDev/office-js-docs-pr#3160]
None of the suggested options on my MacBook Pro 2021 are available. The personality menu and all the provided links aren't available (Library/Containers is not an available folder).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e273e29-10ac-440e-634e-588b5208e484
* Version Independent ID: a5a6dc8a-b504-686e-80ce-45aabd6f832b
* Content: [Clear the Office cache - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache)
* Content Source: [docs/testing/clear-cache.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/clear-cache.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wenjun-Gong** [comment]
Thank you for taking the time to report an issue. Would you mind provide additional information for us to triage your issue? Here is a template for you to start with. Thank you.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior


## Current behavior



## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)



1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context



## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)
