### ISSUE TITLE
Build number reference for "Office 2021 or later on Windows (one-time purchase)"

### ISSUE THREAD

**Issue by vault79** [OfficeDev/office-js-docs-pr#3169]
Hi there,

Would you please provide link about  "Office 2021 or later on Windows(one-time purchase)" build numbers ?

In this document, I can find [link](https://docs.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date) for  MS365 app build numbers but I could not find for Office 2021 one-time purchase's one.

When I walk around documents, I found [Update history for Office LTSC 2021 and Office 2021](https://docs.microsoft.com/en-us/officeupdates/update-history-office-2021). It looks Office 2021 one-time purchase build number history, but there is no `Build 16.0.14326.20454` described in this document. All build number is smaller than 16.x. Developers, including me, can understand release date of target build if you provide the link. 

FYI: I utilize release date to decide whether we start to develop with newer APIs. If target build is released one years ago, I think it is mature and good timing to start development. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33229c8f-7e6c-a8fe-f6c1-0f452f8758c0
* Version Independent ID: 596c9d93-6990-e7d2-03fa-1f3781a23c81
* Content: [Identity API requirement sets - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/identity-api-requirement-sets)
* Content Source: [docs/reference/requirement-sets/identity-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/requirement-sets/identity-api-requirement-sets.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @vault79,

Thank you for the feedback.

We provide build numbers instead of release dates because [different channels](https://docs.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date) of Office release updates at different times. If you're on Insiders, Monthly, Semi-Annual, or a one-time release (such as 2021), you'll receive a requirement set on a different date. This also holds true for different platforms: a requirement set may become available on Windows, Mac, and Online on different dates.

As for your FYI, all our APIs are in a preview state while we stabilize them and gather customer feedback. They only get promoted to a release state when we're confident in them. Once an API is released, we provide continued support for that API (barring some exceptional circumstance), as to not break your add-in.

In practice, we find that larger enterprise customers use the semi-annual channel. If your add-in targets the APIs available there, you should have the most confidence in the product and that your add-in will have the best reach.

I'm going to close this issue, since there's nothing actionable to be done. If you disagree or have further questions, please reach back out and I'll reopen the issue. Thank you.
