### ISSUE TITLE
After the Convert, Code is not Even Called - Does NOT Work!

### ISSUE THREAD

**Issue by laultman** [OfficeDev/office-js-docs-pr#320]
Followed the instructions multiple times to ensure that I am not missing any steps. The Home.ts code is NEVER called at runtime. No breakpoints are ever hit and the page does not have even the simple text that should be emitted by the javascript. So the conversion is a dud.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b888399c-fe96-0934-00ce-86db8fa8cf5b
* Version Independent ID: 2c5d24e8-5639-42b1-4d12-119f89591550
* Content: [Convert an Office Add-in project in Visual Studio to TypeScript](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/convert-javascript-to-typescript)
* Content Source: [docs/develop/convert-javascript-to-typescript.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/convert-javascript-to-typescript.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks for bringing this to our attention. We're looking into it.

**Comment by rxcontributorone** [comment]
hello

**Comment by kbrandl** [comment]
@laultman thanks again for the feedback; this article has been updated. Please note that breakpoints you set in the **Home.ts** TypeScript file won't be hit at runtime, because that TypeScript gets compiled to JavaScript, and it's the JavaScript code that's running at runtime. So to debug in Visual Studio, you'll need to build the project, then add the corresponding JavaScript file (**Home.js**) to your project, and set the breakpoints in that file.

**Comment by G00golplex** [comment]
Hi Microsoft! I have the exact same problem like Laultman. I am trying to learn Office add-in's with the book from Michael Zlatkovsky (https://leanpub.com/buildingofficeaddins/). He is very enthusiastic about TypeScript and therefore I try to get my projects converted to TypeScript but the breakpoints are never hit! If something goes wrong, visual Studio 2017 always loads up the generated Home.JS file. And because I am no JavaScript expert, that does not help me. By the way the configuration file (tsconfig.json) is also faulty and should contain other parameters. 
PS.: I cannot access the MS internal link .
