### ISSUE TITLE
What is the exact version of Office.js library?

### ISSUE THREAD

**Issue by dmitriyyepishin** [OfficeDev/office-js-docs-pr#3202]
How can I find the version of Office.js. My company requires us to obtain legal approvals for specific versions, so as we use Office JavaScript API we need to be able to find out how versions change.

**Comment by AlexJerabek** [comment]
Hi @dmitriyyepishin,

Office.js doesn't have versions, in this sense. We only support the latest version published to the CDN. Our officially stated policy can be found here: https://github.com/OfficeDev/office-js#support

Is there a specific concern your company has?

**Comment by dmitriyyepishin** [comment]
Thank you for your response. Our legal department reviews various product versions that we use to check for security and other issues to ensure that we protect our customers. Most products have version numbers and security and other issues can be tracked by version. Does Office.js have an issue tracker of some sort that we can access and monitor?

**Comment by AlexJerabek** [comment]
Issues with Office.js are tracked on the product repo here: https://github.com/OfficeDev/office-js

The NPM package you linked is _usually_ the latest version, though I should call out this line from the Support section:
> The frequency of the updates to this repository and related NPM package to match the CDN version is not guaranteed.

In practice, that accounts for the lag between publishing a new version to the CDN and that version getting published as an NPM package. Office Add-ins technically run off of the former.

Let me loop in @jeremy-msft, in case further clarifications are needed.

**Comment by dmitriyyepishin** [comment]
Thank you for the feedback. How can one know what version an issue has been fixed in?

**Comment by AlexJerabek** [comment]
Well, the answer is probably unfulfilling, but there aren't version notes in that capacity. Fixes are also often implemented through changes to Office itself, so the npm version wouldn't reflect that change anyway. What we can say is that the latest version on the CDN is the most patched version and that we maintain backward compatibility.

I'm going to close this issue, since there's nothing actionable to be done here. Please let us know if you have further questions.
