### ISSUE TITLE
No npm run watch or npm run start:desktop

### ISSUE THREAD

**Issue by Herz3h** [OfficeDev/office-js-docs-pr#3229]
Neither 

`npm run watch`

nor:

`npm run start:desktop`

Project generated with yo + vue, here is the package.json:
```
{
  "name": "test-addin",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@zip.js/zip.js": "^2.4.3",
    "core-js": "^3.6.5",
    "fast-xml-parser": "^4.0.2",
    "fs-extra": "^10.0.0",
    "howler": "^2.2.3",
    "jszip": "^3.7.1",
    "office-addin-debugging": "^4.3.9",
    "unzipit": "^1.4.0",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "vue-template-compiler": "^2.6.11"
  }
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bedd430-d224-565e-c1b1-15f90994aa52
* Version Independent ID: b41539c4-c9ec-c678-e44b-27bd456b9c0b
* Content: [UI-less custom functions debugging - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-debugging)
* Content Source: [docs/excel/custom-functions-debugging.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-debugging.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by samantharamon** [comment]
Thank you for reaching out, @Herz3h. To assist us in our investigation, do you receive a particular error when you attempt to run `npm run watch` and `npm run start: desktop`?

@alison-mk, could you please assist with this? Thanks!

**Comment by Herz3h** [comment]
Here is what I get upon running `npm run watch` 
![image](https://user-images.githubusercontent.com/1900696/153366285-70feb327-48c0-4d97-a005-f5e5de74778e.png)

**Comment by Rick-Kirkham** [comment]
Your package.json `scripts` section is definitely missing those scripts (and all the Office Add-in scripts). Did you create this with Yo Office _and no other tool_?

**Comment by Rick-Kirkham** [comment]
After looking at this article [Use Vue to build an Excel task pane add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-vue), it appears that our guidance for a Vue-based add-in is to take the "manifest only" option in Yo Office. One effect of this is that the Office Add-in related scripts are not installed, nor mentioned in the `scripts` section of the package.json. Our debugging instructions assume these scripts are present. 

Because the Vue project and the add-in project each install and use their own servers, it will not be easy to merge them.

Try this: 
1. Create a Yo Office project. Take the custom functions option.
2. Create a Vue project in another folder.
3. Merge contents of the package.json file in the Vue project into the corresponding sections of the package.json file of the add-in project. So, for example, the `scripts` section has all the scripts of both package.json files and the `dependencies` section has all the dependencies of both package.json files, etc.
4. In the root of the add-in project project (with the supersized package.json), run `npm install`. 
5. Copy any source code files from your existing project (the one that's not working) to the new project.
6. In the new project, see if `npm watch` and `npm start:desktop` will run as expected.

**Comment by Herz3h** [comment]
Thank you, maybe this should be documented on the page ?

**Comment by Rick-Kirkham** [comment]
@Herz3h Did it work? If so, I'll update the page with this information.

**Comment by Herz3h** [comment]
Yes thank you

**Comment by Rick-Kirkham** [comment]
Before we change the documentation, we're looking into the possibility of changing Yo Office so that it adds the scripts even when the manifest-only option is chosen.

**Comment by Rick-Kirkham** [comment]
The change to Yo Office is not going to happen until Fall at the earliest, so I have added a remark in the documentation about this problem.
