### ISSUE TITLE
iOS Mobile Add-in embedded browser control uses Safari and our client requires to use a more secure Edge browser. How can we achieve this?

### ISSUE THREAD

**Issue by priyankak9** [OfficeDev/office-js-docs-pr#3257]
## Article URL
 https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins

## Issue

 Outlook Add-in in iOS Mobile uses Safari as the embedded browser (see article) and our client's security policies requires them to use a more secure Edge browser. 

Client has Azure Single Sign-on policies so that a user can only use the Edge browser to log in. See image
 
![image](https://user-images.githubusercontent.com/98601216/154730383-a6aa9569-e569-4909-98b0-2437479e2b57.png)

Client does not want to update Conditional Access policy to Allow Safari which leaves us with switching the browser in iOS for the Outlook Add-in to Edge which, from the article, is not supported by Microsoft

Looking for suggestions of option we have to allow our clients a secure access into out Outlook Add-in using Mobile:

-  To see if there is a way we can use Edge somehow that Microsoft has seen others firms use that we can build for the product in the long term for a more secure access. (And/Or)
- Asses the risk of using Safari, with Microsoft  for our clients to feel safe about conditionally allowing Safari as the embedded browser control, if not, see what else Microsoft can suggest in these cases

Thank you for taking a look

Intapp Inc

**Comment by AlexJerabek** [comment]
Hi @priyankak9,

Sorry for the delayed response. Currently, iOS add-ins only run through an embedded Safari browser, as documented here: https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins

To request the feature of Edge support, please go to the [M365 feedback portal](https://feedbackportal.microsoft.com/feedback) and create an issue. Because there's nothing actionable to do in the documentation, I'll close the issue.
