### ISSUE TITLE
ta

### ISSUE THREAD

**Issue by NightGreyMoon** [OfficeDev/office-js-docs-pr#3316]
[Enter feedback here]
Got below message
Unable to download project zip file for "https://github.com/OfficeDev/Office-Addin-TaskPane-JS/archive/yo-office.zip".
Error: read ECONNRESET
after ran the "yo office" with following the guide

Tried on both Windows and Mac, anyone can help?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4ddde7-f1fd-44ba-fba1-0ae9d0131df7
* Version Independent ID: d946ffe6-f29f-1563-b679-121090ba60a1
* Content: [Build your first Excel task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/excel-quickstart-jquery.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @NightGreyMoon,

Thanks for reporting this. I am unable to reproduce your issue. It might be that your local firewall settings are blocking the file download. Let me tag @millerds and @igor-ribeiiro to see if they have any thoughts.

**Comment by igor-ribeiiro** [comment]
I also couldn't reproduce the issue. I'm not sure what could be causing this issue other than network-specific configuration that could be blocking the download

**Comment by AlexJerabek** [comment]
@NightGreyMoon,
My next two troubleshooting steps would be:
1. Make sure you can download that zip file directly. If you can't navigate to that URL, you definitely have a network configuration that's blocking GitHub or external files.
2. Make sure you're running your command prompt as an administrator. 

Since we can't reproduce this issue and it doesn't seem like a problem with yo office, I'm going to close this issue. If you're still having network problems, I'd recommend looking on Stack Overflow for answers. Here's one I found that may help you: https://stackoverflow.com/questions/18419144/npm-not-working-read-econnreset

**Comment by NightGreyMoon** [comment]
> 

@AlexJerabek , thank you very much for the reply.

I've tested that I can download this zip on browser, but it is slow (don't know if it affects)

And for point 2, I also tested with running VS Code as Administrator on Windows, same error there

After all, I was wondering if it is network to GitHub unstable (I'm from China)

**Comment by AlexJerabek** [comment]
@NightGreyMoon Are you able to try the [Visual Studio version of the quick start](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=visualstudio). If you have Visual Studio (not Visual Studio Code), that might be a good test whether it is your network connectivity or something else.

Otherwise, my theory is that you are hitting a timeout when running yo office. That file should download pretty fast. I don't think being in China should cause issues, since part of our team is located in Beijing and they regularly run yo office.
