### ISSUE TITLE
The content is blocked because it isn't signed by a valid security certificate

### ISSUE THREAD

**Issue by DainisVerdins** [OfficeDev/office-js-docs-pr#3344]
I have developed an addin for outlook 365 but i can't start then in my desktop outlook, i get the error The content is blocked because it isn't signed by a valid security certificate.
![image](https://user-images.githubusercontent.com/55252915/160558378-0e598af0-0a82-4288-8eae-310fc356c8da.png)

then I am using my add-in in ethernet outlook in chrome it works fine as expected.

i run this command `npx office-addin-dev-certs install ` as suggested [where](https://github.com/OfficeDev/office-js-docs-pr/issues/1598), but the error still happening.
 
What I tried 
* Switching flag in Edge browser to allow not certified certificates to "work"(same thing was done in chrome and it worked there)
[![edge changed flag][2]][2]

* As suggested in comments to use `office-addin-dev-certs`. Well I installed them on my project by using `npm install office-addin-dev-certs` and then I am trying to verify it by this command `office-addin-dev-certs verify` it throws error in console see image 3 
[![office-addin-dev-cert error on verify][3]][3]

* exported certificates from chrome and imported them in edge browser and also on my machine . It did not helped.

* deleting content of folder `C:\Users\{username}\.office-addin-dev-certs` and `npx office-addin-dev-certs install` it did not helped .

My specs :
* Windows 10 Pro . Version: 21H1 . Os build: 19043.1586. Experience: Windows Feature Experience Pack 120.2212.4170.0 
* Desktop outlook : Version 2202 Build 16.0.14931.20128) 64-bit 

  [2]: https://i.stack.imgur.com/xkusa.png
  [3]: https://i.stack.imgur.com/d7gKO.png

**Comment by nkkinariwala** [comment]
@preethikakiru  - Is it something you can help with?

**Comment by millerds** [comment]
The reason the verify command didn't work is because you didn't use 'npx" at the beginning.

Note that the certificate is for running the add-in locally (using webpack) and the host being able to access it from there.  It's not affected by browser settings when using desktop apps.

Can you run this in PowerShell and share the results here: 
'Get-ChildItem cert:\\CurrentUser\\Root | Where-Object Issuer -like "*CN=Developer CA for Microsoft Office Add-ins*" | Where-Object { $_.NotAfter -gt [datetime]::today.AddDays(-1) } | Format-List'

Can you also try loading this URL in the browser after you get the error (when the add-in is supposed to be loaded).
https://localhost:3001/taskpane.html
