### ISSUE TITLE
When will the nightmare end?

### ISSUE THREAD

**Issue by mendeza** [OfficeDev/office-js-docs-pr#3376]
Seriously, when will IE11 be gone for good?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @mendeza,

The browser control running IE11 is still embedded in older versions of Office (or used with older versions of Windows). To target those Office versions, you'll need to support IE11. As of right now, there are no plans to backport a new Webview controller in those non-subscription Office versions.

That said, you can have your add-in gracefully fail if IE11 is the browser. As shown in the code sample [here](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/support-ie-11#determine-at-runtime-if-the-add-in-is-running-in-internet-explorer), you can check the browser and provide an alternative experience for IE11. That experience could be a message saying the add-in needs a new version of Office to work.

I'm going to close this issue, since there's nothing actionable we can do from the documentation side of things.

**Comment by mendeza** [comment]
OK. Right. Next order of business: kill off those older versions of Office. Thank you.
