### ISSUE TITLE
Custom Functions Accessing Sheet Properties 

### ISSUE THREAD

**Issue by PeterTippett** [OfficeDev/office-js-docs-pr#344]
Currently testing this function as want to store information between sheet opening. 

An example is storing the token for API access.

This isn't working for Custom functions but works for the normal add-ins.  Think this is related to context?

BUT I can access the url property in this - Office.context.document.url

Sample Code

```
function getProperty(name) {
    var setting = Office.context.document.settings.get(name);
    console.log("ReadSettings: "+ name+", "+setting);
    if (setting == ""){
        return null;
    } else {
        return setting;
    }
}

function setProperty(name, data) {
    console.log("setSetting: "+name+":"+data);
    Office.context.document.settings.set(name, data);
    Office.context.document.settings.saveAsync(function (asyncResult) {
        console.log('set settings saved with status: ' + name + " - "+ data + ", " + asyncResult.status);
    });
}

```

**Comment by kbrandl** [comment]
@PeterTippett thanks for reaching out and sorry to hear that you've run into this problem. Issues in this GitHub repository (**OfficeDev/office-js-docs-pr**) are intended for reporting errors/problems with the API *documentation*.  While there is certainly some overlap at times, errors/problems with the API itself (such as the one you've described) should be posted to the **OfficeDev/office-js** repository, which members of the product team monitor for customer-reported API issues such as this. 

I'm going to close this issue here in the docs repository; can you please post this issue to the [OfficeDev/office-js](https://github.com/OfficeDev/office-js/issues) repository instead? Thank you!
