### ISSUE TITLE
Can't figure out JS runtime of addin, docs not clear

### ISSUE THREAD

**Issue by jkscx** [OfficeDev/office-js-docs-pr#3462]
Hello, 

I would like to figure out the JS runtime which Excel uses to run the addin we're developing, but the docs on how exactly to do this are very sparse. Namely, it says that it should be available in the "Personality menu" under "Security info", but there is no such info available for us (picture below).

![image](https://user-images.githubusercontent.com/18429283/172145812-4ab6b10c-0806-47f6-bc1c-3bd163682770.png)

The docs do say that "The runtime isn't included on the dialog in older versions of Office" but I wouldn't say that our Office version (picture below) is that old?

![image](https://user-images.githubusercontent.com/18429283/172146210-85a60642-fe0b-4df9-9e8f-684e07377b75.png)
![image](https://user-images.githubusercontent.com/18429283/172146219-9492d157-3ccc-4d16-b087-afeabc481aca.png)

As such, I wanted to ask what I could do to figure out the JS runtime?

Kind regards,

Filip

---
#### Windows specs
Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎08/‎02/‎2022
OS build	19044.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc051b98-1aaa-20ad-b740-6ac4d377529e
* Version Independent ID: fc051b98-1aaa-20ad-b740-6ac4d377529e
* Content: [Debug Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-overview)
* Content Source: [docs/testing/debug-add-ins-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/debug-add-ins-overview.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @jkscx,

Thanks for reaching out. @Rick-Kirkham, could you please help provide clarity here?

**Comment by Rick-Kirkham** [comment]
@jkscx Thanks for your interest in Office Add-ins. 

The main way of determining what runtime is being used is by consulting the table in the article, [Browsers used by Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins). See the sentence immediately above the **Tip** that you quoted. The **Tip** is only meant to point out an alternate, easier way that is sometimes available. When it is not, you have to use the table. 

Since you are on Windows 10 version greater than 1903 and you have an M365 version that is between 16.0.11629 and 16.0.13530.20424, the 3rd row from the bottom of the table applies to you. So, your computer uses **Microsoft Edge with original WebView (EdgeHTML)**.

Your version of M365 is 1906, which is 3 years old. That does count as "older" in the context of discussing the Personality menu. The reason we are vague and say "older" is because there are some complexities in determining where the Personality menu is supported; it is not simply a matter of being supported by all builds after a certain specified build number. It isn't worth documenting these complexities because if people find that the Security Info isn't there, they can just fall back to using the table. 

I'll close this issue for now, but you can still add comments to it and we will see them.

**Comment by jkscx** [comment]
@Rick-Kirkham Thank you very much for the quick and detailed reply. 

Sorry if I phrased my question badly, I know about the table which you mentioned and came to the same conclusion as you, but wanted to know if there is a way to get the runtime info at runtime (pun not intended). The reason being that I want to use the WebView2 runtime and followed the guide in footer 4 of the article which you linked on how to enable it, but not sure if I got it to work. That's why getting the runtime info would be useful.

Also thanks for informing me about the Excel version being that old (thought that it was max 1-2y old), have requested our company's IT support to allow me to update to something newer to mitigate this issue. But just for completeness sake, is there a way to the runtime info at runtime for older versions (if not by GUI, then maybe via code in the add-in)?

**Comment by Rick-Kirkham** [comment]
The only way that I know of to determine the runtime at runtime the technique described in [Determine at runtime if the add-in is running in Internet Explorer](https://docs.microsoft.com/office/dev/add-ins/develop/support-ie-11#determine-at-runtime-if-the-add-in-is-running-in-internet-explorer). This links to another article that tells you what strings to look for.

**Comment by jkscx** [comment]
Will check out, thank you for the help :)
