### ISSUE TITLE
Two sample codes in the tutorial are missing commas

### ISSUE THREAD

**Issue by JHJ-MS** [OfficeDev/office-js-docs-pr#3463]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/94002141/172148189-9c2753bb-16a6-4d28-9aba-9fd6a1ed50c3.png)
![image](https://user-images.githubusercontent.com/94002141/172148213-b5dce737-94d0-47b5-9bb9-93c757ada307.png)

These two sample codes cause errors because of missing commas. After adding a comma after the circle place, it works fine.
Hope to correct the sample code. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac7d9e2d-b537-cf1f-95fb-4e216514f3b1
* Version Independent ID: 4a86c93b-70d8-38e4-f62e-83c43a0158dd
* Content: [Excel add-in tutorial - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial)
* Content Source: [docs/tutorials/excel-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/excel-tutorial.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @JHJ-MS,

Thanks for reaching out. Could you please show the errors you're getting in those two instances? Neither piece of code should need a comma where highlighted because it's the end of a list. I just tried out the [Create a table](https://github.com/OfficeDev/office-js-snippets/blob/main/samples/excel/46-table/create-table.yaml) snippet in [Script Lab](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab) (which uses the same 2D array to create the table), and it works fine.

![image](https://user-images.githubusercontent.com/38896772/172207031-6dc4ba54-697f-4142-a290-340f60e75f58.png)

Also, potentially unrelated, but how old are those screenshots? We changed the tutorial to not use `var` [with a commit back in February](https://github.com/OfficeDev/office-js-docs-pr/commit/97a4ed44c107d2357b4d17148c9b1a281bd598f2). If the old version of the page is still showing, that would be a huge problem. Please make sure you're fully refreshed the page (Ctrl-F5 in most browsers) and see if you're still seeing the older code that used `var`. 

Thanks!

**Comment by JHJ-MS** [comment]
Thanks, @AlexJerabek. We found it is a warning caused by a prettier config. I'll close this issue. Besides, this is a screenshot in January.Thank you again!
