### ISSUE TITLE
Event Type="ItemSend" 

### ISSUE THREAD

**Issue by DanilKorotenko** [OfficeDev/office-js-docs-pr#3527]
Where exactly should be "Event Type="ItemSend"" ?

Inside "VersionOverrides" ? Or on root level ?

Could you, please, provide complete example?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e12d688-9620-e8f2-871d-922ec98008b5
* Version Independent ID: a8b409f3-44f7-97e5-d722-cbf04edc0653
* Content: [On-send feature for Outlook add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=unix#limitations)
* Content Source: [docs/outlook/outlook-on-send-addins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/outlook-on-send-addins.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @DanilKorotenko,

There is a sample under the [Code examples](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=unix#code-examples) section of that article. There, you're find a link to a [full sample showing a working add-in using the On-send feature](https://github.com/OfficeDev/Outlook-Add-in-On-Send).

Please let me know if I misinterpreted your request and that sample does not answer your question.

**Comment by DanilKorotenko** [comment]
Hi @AlexJerabek,
My question relates to this issue:
https://github.com/OfficeDev/Outlook-Add-in-On-Send/issues/32

I am confused. 
"office-addin-manifest validate" script says that "ItemSend" should not be inside "VersionOverrides".

**Comment by AlexJerabek** [comment]
Thanks for clarifying @DanilKorotenko. @samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Hi @DanilKorotenko,

Thanks for reaching out. `Event Type="ItemSend"` should be inside the **VersionOverrides** block as shown in [Contoso Message Body Checker](https://github.com/OfficeDev/Outlook-Add-in-On-Send/blob/master/outlook-add-in-on-send/Contoso%20Message%20Body%20Checker.xml) and [Contoso Subject and CC Checker.xml](https://github.com/OfficeDev/Outlook-Add-in-On-Send/blob/master/outlook-add-in-on-send/Contoso%20Subject%20and%20CC%20Checker.xml). The error appears when validating the manifest because add-ins that use the on-send feature can't be published to AppSource and can only be deployed by admins. For additional information, please see https://github.com/OfficeDev/Office-Addin-Scripts/issues/613 where this is being addressed. I will work on adding a note about this in [On-send feature for Outlook add-ins](https://docs.microsoft.com/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=windows#installing-outlook-add-ins-that-use-on-send).

Despite the error, your add-in should still run. Please let me know if you encounter additional issues.

I also wanted to take this opportunity to inform you about [Smart Alerts and the OnMessageSend and OnAppointmentSend events](https://docs.microsoft.com/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough), which are currently in preview for Outlook on Windows. It's similar to on-send, but has [additional send mode options](https://docs.microsoft.com/javascript/api/manifest/launchevent?view=common-js-preview) you can use. It will be supported in OWA and will allow you to publish your app to AppSource soon (these are currently being worked on by the team).
