### ISSUE TITLE
webpack.config.js is missing in project, how to add it?

### ISSUE THREAD

**Issue by bhattikashif** [OfficeDev/office-js-docs-pr#3568]
I created a Excel Add in project using Visual Studio 2019 few months back. Its shared runtime is causing problems, so I decided to check documentation again and came across this page. It talks about changing "webpack.config.js" file but it is not present in the project. Can you update this page for older projects to guide about how to add this file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 056e0311-c24e-6342-a3f0-36120930107d
* Version Independent ID: dd406dd4-8384-190a-2385-01324cf1ba3a
* Content: [Tutorial: Share data and events between Excel custom functions and the task pane - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial)
* Content Source: [docs/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
This tutorial creates an add-in project with Yo Office. That kind of project runs in Node.js. WebPack is a tool for bundling multiple JavaScript files into one. WebPack is only relevant to Node.js based projects. Since you created your project in VS 2019, your project uses C# or VB.NET on the server side and runs in an IIS server. WebPack is not used in that environment. That's why there is no webpack.config.js file. Whatever problems you are having with the shared runtime, you're not going to solve it with WebPack. 

Consider raising your problem on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/search.html?type=question%20OR%20idea%20OR%20kbentry%20OR%20answer%20OR%20topic%20OR%20user&redirect=search%2Fsearch&sort=relevance&q=office-addins-dev). Be sure to "office-addin-dev".

Alternatively, consider recreating your project as a Node.js project. You can use this tutorial as a good place to start. 

I'll close this for now, but you can still add comments and request that it be reopened if we've misunderstood.
