### ISSUE TITLE
What is the best method to distribute an add in to clients in different organisations?

### ISSUE THREAD

**Issue by edlgg** [OfficeDev/office-js-docs-pr#367]
I have several clients to whom I would like to sell add ins with a subscription model. What is the best way to do this? Thanks!

**Comment by kbrandl** [comment]
@edlgg thanks for reaching out with this question. By design, the Office Add-ins documentation set doesn't contain guidance about how to sell add-ins with a subscription model.  I'd suggest that you start by reviewing this article which discusses how to publish your add-in to AppSource:

https://docs.microsoft.com/en-us/office/dev/store/submit-to-the-office-store

In terms of how to enable a subscription model for your add-in, that type of logic will need to be part of your app itself (not a feature that you can simply enable via your AppSource listing).
