### ISSUE TITLE
cannot access manifest url at https://127.0.0.1:3000/manifest.xml

### ISSUE THREAD

**Issue by ajadavis** [OfficeDev/office-js-docs-pr#3747]
Following directions here: https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-react

Running on Mac, running other webpack projects successfully today.

Upon running "npm run dev-server", server appears up and healthy from terminal. trying to access localhost:3000, 127.0.0.1:3000, localhost:3000/manifest.xml, 127.0.0.1:3000/manifest.xml unsuccessful in browser (404). This results in error in title of issue when trying to sideload addin from onedrive using "npm run start:web -- --document {url}" 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 49ccc61e-06b1-fd30-63a0-625301ea0bc8
* Version Independent ID: 1fdff452-de8f-5b97-9f53-389eb9576b25
* Content: [Use React to build an Excel task pane add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-react)
* Content Source: [docs/quickstarts/excel-quickstart-react.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/excel-quickstart-react.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by samantharamon** [comment]
Thank you for reaching out, @ajadavis.

I tested the quick start on the Mac client and the browser, but I couldn't replicate the error you're getting. To confirm, when you run `npm run start:web -- --document {url}`, did you enclose your URL in single quotation marks by any chance?

**Comment by ajadavis** [comment]
hello apologies for the late reply, but seems this might already be closed? yes i can confirm that i enclosed my url in single quotation marks, i have the npm run dev-server + npm start working locally with excel, but the npm run start:web -- --document {url} still reads "cannot access manifest url at https://127.0.0.1:3000/manifest.xml". 
i can confirm access https://127.0.0.1:3000/manifest.xml in the browser, but not through the excel online hosted at https://onedrive.live.com/... could it be settings of office online account?

**Comment by samantharamon** [comment]
Apologies for the delayed response, @ajadavis. I was able to replicate the issue you're experiencing. When you get a chance, please try running `npm run dev-server` before running `npm run start:web -- --document '{url}'`. I received the "Cannot access manifest" error when I only ran the latter command, but not the first. Let me know if that fixes the issue for you.

**Comment by ajadavis** [comment]
no worries @samantharamon , i still see the issue even with the `npm run dev-server` command preceding the other command. i leave the dev server running in a separate terminal and still receive a "cannot access https://localhost:3000/manifest.xml" error. i can confirm that if i enter that url into the browser, i can see the manifest xml.

my command looks like:
`npm run start:web -- --document 'https://onedrive.live.com/edit.aspx?action=editnew&resid=XXXXXXXXXXXXXXX&ithint=file%2cxlsx&action=editnew&wdNewAndOpenCt=XXXXXXXXXXXX&wdPreviousSession=XXXXXX-XXXXXX-XXXXX-XXXXX&wdOrigin=OFFICECOM-WEB.START.NEW' `

where i have omitted the sensitive url values

**Comment by samantharamon** [comment]
Thanks for giving that a try. Could you also try clearing your browser cache (see [Remove a sideloaded add-in](https://learn.microsoft.com/office/dev/add-ins/testing/sideload-office-add-ins-for-testing#remove-a-sideloaded-add-in)) while the localhost server isn't running, then try running `npm run start:web` again?

If that still doesn't work, the following are other troubleshooting steps we could try.
- Restart your computer, if you haven't already, before running the quick start.
- Try creating a different Excel file in your OneDrive account and then copying the URL from the address bar, so that the URL looks something like https://onedrive.live.com/edit.aspx?resid=XXX.
- Try creating a new instance of the quick start and running that.
- Test running a similar quick start in a different Office product, such as Word. You could use the tutorial in [Use Fluent UI React in Office Add-ins](https://learn.microsoft.com/office/dev/add-ins/design/using-office-ui-fabric-react) until the 'Try it out' section.

**Comment by rubi-rastko** [comment]
After importing Yeoman generated certificates into the browser, and checking off trust boxes, both for the ca and localhost certificate, I was able to access it. The giveaway was opening the manifest, and getting the certificate invalid warning.

**Comment by hbnrmx** [comment]
Given the query parameters

```
https://some.sharepoint.com/[...]/example.pptx
?wdaddindevserverport=...
&wdaddinmanifestfile=...
&wdaddinmanifestguid=...
```

Office on the Web will expect your manifest file to be served at 

```
https://127.0.0.1:{wdaddindevserverport}/{wdaddinmanifestfile}
```

which is very frustrating because `office-addin-dev-certs install` installs a certificate for `https://localhost`, but `https://127.0.0.1` needs to be trusted manually. 

side note: we tried moving away from `office-addin-dev-certs` to `dotnet dev-certs` but it looks like they also don't do self signed certs for `127.0.0.1`: https://github.com/dotnet/aspnetcore/issues/18959

I would appreciate if you could reopen this ticket.
Thank you :)

**Comment by AlexJerabek** [comment]
@hbnrmx, thanks for raising this concern. Could you please open a new issue in the [Office-Addin-Scripts](https://github.com/OfficeDev/Office-Addin-Scripts) repo where office-addin-dev-certs is maintained?

**Comment by hornta** [comment]
> Given the query parameters
> 
> ```
> https://some.sharepoint.com/[...]/example.pptx
> ?wdaddindevserverport=...
> &wdaddinmanifestfile=...
> &wdaddinmanifestguid=...
> ```
> 
> Office on the Web will expect your manifest file to be served at
> 
> ```
> https://127.0.0.1:{wdaddindevserverport}/{wdaddinmanifestfile}
> ```
> 
> which is very frustrating because `office-addin-dev-certs install` installs a certificate for `https://localhost`, but `https://127.0.0.1` needs to be trusted manually.
> 
> side note: we tried moving away from `office-addin-dev-certs` to `dotnet dev-certs` but it looks like they also don't do self signed certs for `127.0.0.1`: [dotnet/aspnetcore#18959](https://github.com/dotnet/aspnetcore/issues/18959)
> 
> I would appreciate if you could reopen this ticket. Thank you :)

We use mkcert for this.
`mkcert -key-file .certs/localhost-key.pem -cert-file .certs/localhost.pem localhost 127.0.0.1 ::1`

And also make sure you install mkcert as trusted CA
`mkcert -install`

Then we just use those certs in our dev server(vite)
```js
{
  key: fs.readFileSync(path.resolve(__dirname, ".certs/localhost-key.pem")),
  cert: fs.readFileSync(path.resolve(__dirname, ".certs/localhost.pem")),
}
```
