### ISSUE TITLE
The certificate for this server is invalid. 

### ISSUE THREAD

**Issue by ajadavis** [OfficeDev/office-js-docs-pr#3757]
## Issue

Hello
I am attempting to use fetch inside my excel taskpane addin for a network request. I have an express server, and originally i was unable to fetch due to lack of https. i have provided a self signed certificate and excel addin appears to reject this (i am on mac and have safari web inspector set up so i can read from the console inside a desktop version of excel with the addin present). everything i am running is internal so i either need http to be viable or a self-signed certificate to be viable, but i cannot find documentation on how to achieve this.

**Comment by davidchesnut** [comment]
Hi @ajadavis, thanks for letting us know about this. You could try the manual self-certification steps in this [hello world readme](https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/hello-world/excel-hello-world/README.md#configure-a-localhost-web-server-and-run-the-sample-from-localhost). Only don't use the http-server part of it since you are using express server.
1. Run `npm install --global office-addin-dev-certs`
2. Copy the localhost.crt and localhost.key files to your own project folder.
3. Configure express server to use these files.

You can also find more details on the [office-addin-dev-certs package here](https://github.com/OfficeDev/Office-Addin-Scripts/tree/master/packages/office-addin-dev-certs). 

Hope this helps,
David

**Comment by ajadavis** [comment]
hi @davidchesnut , this worked like a charm. thank you so much for your assistance, it is truly appreciated!
