### ISSUE TITLE
Getting a whole document from the Add-in

### ISSUE THREAD

**Issue by pbnsilva** [OfficeDev/office-js-docs-pr#3769]
I'm following the documentation to send a whole Word document to my backend, but don't know how to read what gets sent.

## Article URL
https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/includes/file-get-the-whole-document-from-an-add-in-for-powerpoint-or-word.md

## Issue
I seem to be able to get the document in my backend, but it would be nice to include information on how exactly to read what gets sent.

For instance, attempting to do it `python-docx`:
```python
doc_bytes = base64.b64decode(body)
docx = Document(BytesIO(doc_bytes))
```

Just results in `BadZipFile: File is not a zip file`.

Could we include some more information about how to read this?

**Comment by ElizabethSamuel-MSFT** [comment]
@pbnsilva Thanks for asking about this.

@wangyun-microsoft Can you provide any guidance on this?

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@wangyun-microsoft Any update here? Thx.

**Comment by ElizabethSamuel-MSFT** [comment]
@pbnsilva Apologies for taking so long to get back to you. Actually, this may be a question to ask the community on Stack Overflow. Unfortunately, the server-side aspect is outside the scope of this article and Office JavaScript API. Make sure to also tag your question with python since you seem to be using that option.
