### ISSUE TITLE
example do not work  in Typescript 

### ISSUE THREAD

**Issue by Chewbee** [OfficeDev/office-js-docs-pr#3779]
Hello I am sorry to say but in TS it does not works

I do not mean the tests fails ;) that is my problem 

I mean the setup, here is the code 

```
import { setSelectedTextRange,GetFirstofSelectedShapes, GetTextFrameVerified, GetTextRangeText } from "../commands/setSelectedText";
import { OfficeMockObject } from "office-addin-mock";
import OfficeAddinMock from "office-addin-mock";

const PowerPointMockData = {
  host: "powerpoint",
  context: {
    document: {},
  },
  CoercionType: {
    Text: {},
  },
};

describe(`Tools function `, function () {

  it("GetFirstofSelectedShapes  OK", async function () {
    const officeMock = new OfficeAddinMock.OfficeMockObject(PowerPointMockData);
    global.Office = officeMock;
    
    expect(await GetFirstofSelectedShapes(context: PowerPoint.RequestContext)).resolves.toBeInstanceOf(PowerPoint.Shape)
  });

});
```

for example the import of the mock does not work it would work if i imported : OfficeMockObject but it seems
OfficeAddinMock  is not exported 
 

Long story short, the doc is not very useful  , please advise 
I know my tests are not yet well written but the code above does not compile therefore ...

```
FAIL  src/tests/setSelectedText.tests.ts
  ● Test suite failed to run

    src/tests/setSelectedText.tests.ts:2:10 - error TS2305: Module '"office-addin-mock"' has no exported member 'OfficeAddinMock'.

    2 import { OfficeAddinMock } from "office-addin-mock";

```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 186af615-3198-eaba-a32b-a367476f92b3
* Version Independent ID: 186af615-3198-eaba-a32b-a367476f92b3
* Content: [Unit testing in Office Add-ins - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/unit-testing)
* Content Source: [docs/testing/unit-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/unit-testing.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @Chewbee,

I'm sorry to hear you're having issues. @samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Hi @Chewbee,

Thanks for reaching out. Because the [module](https://www.npmjs.com/package/office-addin-mock?activeTab=explore) you're trying to import from doesn't have a default export (doesn't contain `export default`) attempting to import from it using `import OfficeAddinMock from "office-addin-mock";` will not work. The equivalent of `const OfficeAddinMock = require("office-addin-mock");` using `import` in this case would be `import * as OfficeAddinMock from "office-addin-mock";`.

For a shorter syntax, you can continue using `import { OfficeMockObject } from "office-addin-mock";` instead.

We welcome your feedback for improvement on the doc. I'll add this task to our backlog to provide examples on the use of the `import` statement for cases like this.

Let us know if there's anything else we can help you with.

**Comment by Chewbee** [comment]
Thanks for this will test it hopefully today

**Comment by Chewbee** [comment]
Hello ,

Thanks 

I tried to import like that 

```
import {
  setSelectedTextRange,
  GetFirstofSelectedShapes,
  GetTextFrameVerified,
  GetTextRangeText,
} from "../commands/setSelectedText";
// import { OfficeMockObject } from "office-addin-mock";
import * as OfficeAddinMock from "office-addin-mock";

// Create the seed mock object.

const PowerPointMockData = {
  context: {
    document: {},
  },
  // Mock the Office.CoercionType enum.
  CoercionType: {
    Text: {},
  },
};

describe("the power poinnt fuunctionns", () => {
  it("Dummy always Ok For campaign", function () {
    expect(true).toBeTruthy();
  });
  //

  xit("setSelectedTextRange  OK", async () => {
    const officeMock = new OfficeAddinMock(PowerPointMockData) as any;
    global.PowerPoint = officeMock;

    const data = await setSelectedTextRange();
    console.log(data);
    expect(data).toBeString();
  });
[Edited for brievty]
```

And got the error 

```
Impossible de construire cette expression.
  Le type 'typeof import("/Users/.../node_modules/office-addin-mock/lib/main")' n'a aucune signature de construction.ts(2351)
```

**Comment by AlexJerabek** [comment]
Hi @Chewbee,

Sorry for the delayed response. The holidays mean a lot of people are out. I'll try to look into this issue soon and get back to you.

**Comment by AlexJerabek** [comment]
Hi @Chewbee,

The error you're getting is because PowerPoint.run is not mocked up in the mock object. The `PowerPointMockData` object in your code needs to replicate as much of the [PowerPoint.RequestContext object](https://learn.microsoft.com/javascript/api/powerpoint/powerpoint.requestcontext) as you're going to use, as well as the `run` function and enums.

The relevant section to copy code from in the document would be under [Mocking the Office application-specific APIs](https://learn.microsoft.com/office/dev/add-ins/testing/unit-testing#mocking-the-office-application-specific-apis). You can see in the final block of code there is a testing version of the `run` function:

```
// Create the seed mock object.
const mockData = {
...
  // Mock the Word.run function.
  run: async function(callback) {
    await callback(this.context);
  },
};
```

Please let me know if that helps unblock you. Additionally, if you find that there are problems you're encountering due to TypeScript or jest, I'd recommend posting on [Stack Overflow](https://stackoverflow.com/) with the appropriate tags. You'll reach a wider audience there and find people with lots of knowledge in areas beyond Office.js.
