### ISSUE TITLE
Can you manage 365 add-ins in the Microsoft 365 admin centre for Excel 2019?

### ISSUE THREAD

**Issue by LeapSoftware** [OfficeDev/office-js-docs-pr#3982]
Can you manage 365 add-ins in the Microsoft 365 admin centre for Excel 2019? The documentation is unclear whether this process of centralized installation works with Excel 2019.

https://learn.microsoft.com/en-us/microsoft-365/admin/manage/manage-addins-in-the-admin-center?view=o365-worldwide

If this does not work, what is the process for centrally deploying 365 add-ins in Excel 2019?

**Comment by AlexJerabek** [comment]
Hi @LeapSoftware,

I received an answer from @AkhileshShah-MS. If the tenant has Exchange Online, they can centrally deploy from the admin center. Otherwise (they're on-premises), they will need to use the a [SharePoint catalog](https://learn.microsoft.com/en-us/office/dev/add-ins/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog).

**Comment by LeapSoftware** [comment]
Thanks for the answer Alex!
