### ISSUE TITLE
Indicated code not found

### ISSUE THREAD

**Issue by bkl6221** [OfficeDev/office-js-docs-pr#3985]
[Enter feedback here]
I installed the yeoman generator using Angular since that is the framework we're using for our application. The code that was indicated as being in the main section in taskpane.html was not found there. Instead, the main section was in app.component.html rather than taskpane.html. Nor did the code execute as indicated. Essentially, the instructions did not accurately reflect the code. As someone who is fairly new to javascript and html, it's very confusing to figure this out.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac7d9e2d-b537-cf1f-95fb-4e216514f3b1
* Version Independent ID: 4a86c93b-70d8-38e4-f62e-83c43a0158dd
* Content: [Excel add-in tutorial - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial)
* Content Source: [docs/tutorials/excel-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/excel-tutorial.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @bkl6221,

Thank you for this feedback. The Excel tutorial assumes you've started with the [jQuery quick start](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator), instead of different framework. We should make that clearer.

I would recommend starting with the jQuery version, since you're new to web development space. The other frameworks add a level of complexity. There are also known issues in [our Angular template](https://github.com/OfficeDev/Office-Addin-TaskPane-Angular/issues/115).
