### ISSUE TITLE
Could you provide me with more information on how to clear the cache for Office?

### ISSUE THREAD

**Issue by t-ariyoshi30907** [OfficeDev/office-js-docs-pr#3990]
Hello,

I am creating and selling an Outlook JavaScript add-in. I have a question about the method for clearing the cache that is published on the following page:

office-js-docs-pr/clear-cache.md at main · OfficeDev/office-js-docs-pr](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/clear-cache.md)

On this page, it is written that in order to manually clear the cache, the following folder should be deleted:

%LOCALAPPDATA%\Microsoft\Office\16.0\Wef\

I have confirmed that deleting this folder ensures that all the latest programs are loaded and any issues are resolved. However, there is no mention of what role this folder plays or whether deleting it will affect the operation of Office. Could you please explain this to me?

Many of my customers use the add-in on Outlook for Windows, and they often encounter issues related to the cache. I am considering asking my customers to perform this cache clear process, but I need a sufficient explanation to provide to them.

**Comment by AlexJerabek** [comment]
Thanks for reporting this issue @t-ariyoshi30907. Could you tell us more about your add-in? How are your customers getting the add-in (AppSource, centralized deployment, manual sideloading, etc)?

@samantharamon, could you please continue the investigation?

**Comment by samantharamon** [comment]
Thanks for providing us with details about your deployment environment, @t-ariyoshi30907. I understand that you've already done some tests, but if your users haven't yet, we recommend them to restart Outlook (and their computers for good measure) before clearing the cache folder. That sometimes resolves the issue. However, if they've already done this and the issue persists, then clearing their cache would be the next best option to try.

The "Is the add-in manifest installed properly, and does Outlook have a cached copy?" section of the [Troubleshoot Outlook add-in activation](https://learn.microsoft.com/office/dev/add-ins/outlook/troubleshoot-outlook-add-in-activation#is-the-add-in-manifest-installed-properly-and-does-outlook-have-a-cached-copy) article provides an overview of the Outlook caching process, which may provide some guidance to you and your users. If your users have other add-ins installed, we recommend only renaming or deleting the folder tied to your add-in from the `Wef` folder, so that the configuration of their other add-ins won't be affected.

Let us know if you need further guidance.

**Comment by takanori19910907** [comment]
@samantharamon 

Thank you for your reply.

Unfortunately, there are cases where restarting Outlook does not solve the issue. Therefore, as another solution, I need to guide my customer to clear their cache.

To minimize the impact, I would like to only delete the cache of my product, leaving other files as they are. Is the file mentioned in the document shared with me the cache of the add-in?

\<insert your guid>\<insert base 64 hash>\Manifests\<ManifestID>_<ManifestVersion>

If my understanding of where the product cache is stored is incorrect, please provide me with the correct information. Additionally, I would like to use this as knowledge, so please tell me the roles of the following folders stored in the wef folder:
- webviews2
- AsyncStorage
- Resources

**Comment by samantharamon** [comment]
That's right. To only delete the files related to your add-in, you'll need to delete the following folders and files while the Outlook client is closed.
- `%LOCALAPPDATA%\Microsoft\Office\16.0\Wef\<your Outlook GUID>\<Base64 hash encoding>\Javascript\<your add-in's ID>`
- `%LOCALAPPDATA%\Microsoft\Office\16.0\Wef\<your Outlook GUID>\<Base64 hash encoding>\Manifests\<your add-in's ID>`

Here is a brief description of what each folder is for.
- **webview2** - contains performance metrics and cached resources specific to the WebView2 runtime.
- **AsyncStorage** - stores data used by features that rely on the React runtime and invokes the `OfficeRuntime.Storage` API.
- **Resources** - stores the icons for all installed add-ins in Word, Excel, PowerPoint, and Outlook.
