### ISSUE TITLE
Deploying to App Service linux instance fails

### ISSUE THREAD

**Issue by TiMMaTTiee** [OfficeDev/office-js-docs-pr#3991]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version of Node and the tools
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected behavior

Following [this guide](https://learn.microsoft.com/en-us/office/dev/add-ins/publish/deploy-office-add-in-sso-to-azure?tabs=linux#update-packagejson) using the default yo office starter project for sso on localhost, I was expecting to be able to deploy to App Services.

# Current behavior

During the `npm install` part of deployment, the process hangs after 4/5 lines of logs related to installed packages. Waited for many hours, and tried other node versions within App Service. Somehow, now the deployment fails even before that, logs are below. Eventually tried deploying on Windows, and it worked fine right away.

## Steps to Reproduce

1. Manually create App Service on azure portal (since using VSCode resulted in error due to no resources in region)
2. Follow guide to prepare project for deployment
3. Right click dist folder and choose to deploy to webapp

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Linux
* Node version: Node - 16-lts
* Office version:
* Tool version: 5.0.5

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

4:23:27 PM dalle-sso-linux: Starting deployment...
4:25:23 PM dalle-sso-linux: Creating zip package...
4:25:23 PM dalle-sso-linux: Ignoring files from "appService.zipIgnorePattern"
"node_modules{,/**}"
".vscode{,/**}"
4:25:24 PM dalle-sso-linux: Zip package size: 1.38 MB
4:27:28 PM: Error: The service is unavailable. View troubleshooting tips [here](https://aka.ms/AA772mm).

**Comment by davidchesnut** [comment]
Hi @TiMMaTTiee,

Since the error you are getting is that the service is unavailable you'll want to check that the App service is running. Also check the .vscode/settings.json file in your project that there isn't a default setting pointing to an older App service (since you created a new one.)

Note: I ran through the steps again for Linux deployment and spotted a few things that can affect the deployment. I'll need to refresh the article to be sure these are clear.

1. When deploying, SCM_DO_BUILD_DURING_DEPLOYMENT in the App service configuration needs to be set to true. This runs npm install on the deployment which is needed, but it will also run `npm run build` from package.json which won't work on the server side. So you need to ensure the package.json in the dist folder does not have a build script or you'll get errors during deployment.
2. You need to be sure to update the `<WebApplicationInfo>...<Resource>` tag in the manifest file to point to your deployment URL, not localhost:3000.

Hope this helps,
David
