### ISSUE TITLE
Conflicting Information on minimum requirements for shared folders

### ISSUE THREAD

**Issue by BrendanMayHRB** [OfficeDev/office-js-docs-pr#3999]
Please share the correct minimum requirements to run an outlook Web Add-in on Shared Folders.  

There are two documents (provided below) that seem to contradict each other.  In one, it says that running the add-in on Shared folders is now supported for locally installed Exchange servers, however, on the other page, it clearly says that only the online exchange supports feature set 1.8 which is required to run the add-in on shared folders.

## Article URL
[](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/outlook-api-requirement-sets?view=excel-js-preview&tabs=xmlmanifest#requirement-sets-supported-by-exchange-servers-and-outlook-clients)

https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access?tabs=windows%2Cxmlmanifest

https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/outlook-api-requirement-sets?view=excel-js-preview&tabs=xmlmanifest

**Comment by AlexJerabek** [comment]
Thanks for reporting this @BrendanMayHRB.

@samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Apologies for the delayed response, @BrendanMayHRB. I looked into this further and would like to clarify that the shared folder scenario is only supported in Mailbox 1.8 and later requirement sets. The Mailbox 1.5 supported requirement set per the [Exchange server support table](https://learn.microsoft.com/javascript/api/requirement-sets/outlook/outlook-api-requirement-sets#exchange-server-support) only applies to Outlook on the web in Exchange on-premises environments. If you use the Outlook on Windows desktop client in an Exchange on-premises environment, you can still run an add-in that supports shared folder scenarios as long as the client is a minimum of Version 2206 (Build 15330.20000) for the Current Channel or Version 2207 (Build 15427.20000) for the Monthly Enterprise Channel. This will work because the desktop client supports Mailbox 1.8.

I realize that this information is different from what I provided earlier, so I apologize for the confusion. This is a bug in our docs that I will fix as soon as possible.

Let me know if you need further clarification.
