### ISSUE TITLE
How to work with the member shapes of a Group shape?

### ISSUE THREAD

**Issue by tmtm24680135** [OfficeDev/office-js-docs-pr#4008]
[Enter feedback here]
The "Work with shapes" section (https://learn.microsoft.com/en-us/office/dev/add-ins/powerpoint/shapes?view=powerpoint-js-preview) does not mention shapes of type Group. 

Would like to access member shapes and may be also change the group composition.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9bcbfa95-c75b-102d-2f3f-45935f4c37bd
* Version Independent ID: b1d630f9-c744-5bfb-7288-89573a9efd57
* Content: [Work with shapes using the PowerPoint JavaScript API - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/powerpoint/shapes)
* Content Source: [docs/powerpoint/shapes.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/powerpoint/shapes.md)
* Service: **powerpoint**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@tmtm24680135 Thanks for letting us know about this.

@alison-mk Can you take a look or reassign/move as appropriate?

Thanks.

**Comment by alison-mk** [comment]
Hi @tmtm24680135, thank you for submitting this question. 

I'm researching the answer internally and will report back when I have more information.

**Comment by AlexJerabek** [comment]
Hi @tmtm24680135,

Sorry for the delay here. Shape groups are not currently supported in the JS APIs. There is a feature request for grouping/ungrouping on TechCommunity that you can upvote: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/provide-group-ungroup-functionality-in-powerpoint-js-api/idi-p/4038743#comment-on-this

I'm going to close this issue, since there's nothing actionable to do in the docs.
