### ISSUE TITLE
Please provide example in Typescript and appropriate webpack.

### ISSUE THREAD

**Issue by thethingisannie** [OfficeDev/office-js-docs-pr#4009]
Hi,

I can get the example working, but I hit a wall when I try to implement it in Typescript and use existing modular code.

It would be really useful if the example could be updated to use Typescript with the example code accessing modular code, including how to adjust Webpack to do this.

That the import directive isn't supported actually makes this area much more complicated than you would think.

Thanks

Annie

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 193780ba-aa43-dc5c-fc28-adc96a0fdeda
* Version Independent ID: da41da2b-207e-e976-3491-61672d1e3493
* Content: [Configure your Outlook add-in for event-based activation - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest)
* Content Source: [docs/outlook/autolaunch.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/autolaunch.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@thethingisannie Sorry you are having difficulties. As a general rule, we find that we don't have the staff to create and maintain both JavaScript and TypeScript versions of our samples and snippets. We try to mix it up, but we lean to JavaScript because TypeScript users can read and understand JavaScript since it is a subset of TypeScript, but not all JavaScript users can understand TypeScript. 

But I will create a "bug" for your request in our backlog.  

As for the limitation on the import directive, I saw that note myself just a week ago and it puzzles me. That note has been in that article for years and the writers who put it there are long gone. My team is investigating what it means and if it is still true.
