### ISSUE TITLE
Document mentions wrong files for fallback

### ISSUE THREAD

**Issue by SAgnihotri200895** [OfficeDev/office-js-docs-pr#4082]
Missing fallbackauthhelper.js file in yo office SSO project and authentication failure in Teams desktop app

## Article URL

https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/sso-quickstart#authentication

## Issue
The documentation mentions generating a project structure from yo office SSO project, stating that the project will have a ./src/helpers/fallbackauthhelper.js file, which contains the task pane JavaScript that invokes the fallback authentication strategy when SSO authentication is not supported. However, this file is not present in the generated project.

Due to the absence of the fallbackauthhelper.js file, the getaccesstoken() function fails in the Teams desktop app, displaying an error message indicating that the API is not supported. Additionally, a blank pop-up window opens and immediately closes in the Teams desktop app. It is assumed that this issue is caused by the missing fallbackauthhelper.js file.

It is also worth noting that the article does not mention an option specifically for SSO localhost, as stated.

Please address these issues and update the documentation accordingly.

Images:

 ./src/helpers/fallbackauthhelper.js
 
<img width="484" alt="image" src="https://github.com/OfficeDev/office-js-docs-pr/assets/137901433/8de3541e-27ad-4ff4-be37-59885c903e93">

<img width="178" alt="image" src="https://github.com/OfficeDev/office-js-docs-pr/assets/137901433/8442260d-647a-4b0c-92b2-73119d675b46">

**Comment by Rick-Kirkham** [comment]
I will update the documentation. It no longer matches the project that gets generated. There is no longer a fallbackauthhelper.js file in the project. So the absence of this file is not what's causing the error. Since this repo's issues are for documentation problems, I recommend that you create a new issue in the OfficeDev\office-js repo for the error. Don't mention the documentation error in the new issue to avoid confusion. But do explain what you mean by " fails in the Teams desktop app". Office Add-ins run in the context of an Office Application, like Excel, not in the Teams application.
