### ISSUE TITLE
ReferenceError: exports is not defined After changing Home.js to Home.ts with ES6 TS code

### ISSUE THREAD

**Issue by zjda** [OfficeDev/office-js-docs-pr#4155]
## Article URL

[https://learn.microsoft.com/en-us/office/dev/add-ins/develop/convert-javascript-to-typescript]()

## Issue

 I was able to follow the the document to convert a Word Addin generated by Visual Studio 2022 to TypeScript.  I tried to update the Home.ts by copying some code in taskpane.ts generated by Yeoman as shown below:

```
import { getUserData } from "./src/helpers/sso-helper";

Office.onReady((info) => {
    if (info.host === Office.HostType.Word) {
        document.getElementById("getProfileButton").onclick = run;
    }
});
```

I got the message:

> Uncaught Error Error: Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page.

It also showed the error message:

>Uncaught ReferenceError ReferenceError: exports is not defined
    at (program) (C:\dev\DocWise\DocWiseWeb\Home.js:42:23)

if I include 

`<script src="./Home.js" type="text/javascript"></script>`

in the Home.html.  

It looks like it is caused by ES5, ES6, and CommonJS because exports is defined in CommonJS.  

Any solution or guidance will be appreciated!

Thanks,
-ZJ

**Comment by zjda** [comment]
Followed the instruction in the article again using Visual Studio 2022.  Everything worked as expected until I replaced the generated Home.ts with the following code:

```
Office.onReady((info) => {
    if (info.host === Office.HostType.Word) {
        console.log("In onReady!");
    }
});

export function testExport() {
    console.log("In test export!");
}
```

The compiled Home.js is 

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.testExport = void 0;
Office.onReady(function (info) {
    if (info.host === Office.HostType.Word) {
        console.log("In onReady!");
    }
});
function testExport() {
    console.log("In test export!");
}
exports.testExport = testExport;
```

The last line of the js code causes the error.

Thanks for help,
-ZJ

**Comment by Rick-Kirkham** [comment]
Sorry for the delay. I was out for a medical procedure.

Your error suggests that you are using a version of Office that uses Trident (IE11) to run add-ins. see [Browsers and webview controls used by Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins). 

Projects created with the Office Yeoman generator have a polyfill and a transpiler to convert code from recent versions of JavaScript into JavaScript that Trident can understand. But projects created with Visual Studio do not have this. That's why it is always problematic to try and copy code from a Yeoman project to a VS project. 

What version and build of Office are you using?

**Comment by zjda** [comment]
Thank you for providing the information, Rick. I hope you have a speedy recovery for your medical procedure.

This is my Word version information: 

Microsoft® Word for Microsoft 365 MSO (Version 2302 Build 16.0.16130.20690) 32-bit 

Actually, I prefer the Yeoman TypeScript project in VS Code to C# web application in VS 2022.  However, I am unable to use VS Code on my PC because my company has a very tight controls over our PCs.  When I start command

> npm start or
> 
> npx office-addin-debugging start ./manifest.xml, 

I got the following message

> Debugging is being started...
> App type: desktop
> Allow localhost loopback for Microsoft Edge WebView? Yes
> Error: Unable to start debugging.
> Error: Access Denied, run the command as an administrator    

It will be appreciated if you can provide a solution.

Best,
-ZJ

**Comment by Rick-Kirkham** [comment]
I just noticed that your error message says "exports" instead of "export". Could you have put "exports" somewhere where you should have the keyword "export"?

The error "Error: Access Denied, run the command as an administrator" simply means that you have to start the Windows Command Prompt as an Administrator before you run `npm start` or `npx office-addin-debugging start ./manifest.xml` in it.

**Comment by zjda** [comment]
I searched my project and there is no "exports" in my source files.  The "exports" was created/defined by the TS compiler.

Do you know which commands (e.g. IP port 9000, localhost loopback for Microsoft Edge WebView, or something else) in 
"npm start" or "npx office-addin-debugging start" require the Admin privilege?  I can not be an Admin on the PC, but I can ask my IT to change some system settings.

Thanks,
-ZJ

**Comment by Rick-Kirkham** [comment]
What is the code at C:\dev\DocWise\DocWiseWeb\Home.js:42:23? I want to see where this term "exports" appears.

I don't know for sure what causes the requirement for Admin access, but I think that allowing the localhost loopback attempts to write to the computer's registry. That might be what requires an Admin.

**Comment by zjda** [comment]
This is my "Home.ts":

```
Office.onReady((info) => {
    if (info.host === Office.HostType.Word) {
        console.log("In onReady!");
    }
});

export function testExport() {
    console.log("In test export!");
}
```

and this is the transpiled Home.js

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.testExport = void 0;
Office.onReady(function (info) {
    if (info.host === Office.HostType.Word) {
        console.log("In onReady!");
    }
});
function testExport() {
    console.log("In test export!");
}
exports.testExport = testExport;

```
```
As long as I added the function in Home.ts:

export function testExport() {
    console.log("In test export!");
}
```

I got the following error:

> Uncaught ReferenceError ReferenceError: exports is not defined
>     at <anonymous> (C:\dev\TestTS\TestTSWeb\Home.js:2:23)
> Uncaught Error Error: Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page.
>     at <anonymous> (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:29456)
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4250)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)
>     --- setTimeout ---
>     at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4202)

**Comment by Rick-Kirkham** [comment]
OK. I see what is happening. The transpiled Home.js has put two lines that reference Office **ABOVE** the line that calls `Office.onReady`. Since Office has not loaded at that time, you get the 2 errors: One about Office not being loaded and the other about "exports" not being defined.  

Without seeing more of the project, it will be hard to fix this. 

I presume that your Home.html file has a <script> tag that loads Home.js. Try putting the call to `Office.onReady` in a <script> tag in the Home.html file **ABOVE** the <script> tag that loads Home.js.

I will be on vacation for the next 2 weeks, so it might be some time before I can respond again.

**Comment by zjda** [comment]
Hi Rick,

You are right that `Ofifce.onReady` was not called due to the `"exports" not being defined` error.  If I moved the  `Ofifce.onReady` to Home.html, it was called with no problem. However, I still got the error:

> Uncaught ReferenceError ReferenceError: exports is not defined
>     at <anonymous> (C:\dev\TestTS\TestTSWeb\Home.js:9:23)

Actually, I created this test project by following the article.  Only additional thing I did is that I replaced the original code in Home.ts with 

```
Office.onReady((info) => {
    if (info.host === Office.HostType.Word) {
        console.log("In onReady!");
    }
});

export function testExport() {
    console.log("In test export!");
}
```

Therefore, you should be able to easily reproduce the problem.

Have a nice weekend and wonderful vacation!
-ZJ

**Comment by Rick-Kirkham** [comment]
I reporduced your errors.

I fixed the error about onReady by adding it to the Home.html file like this: (Note that I put it directly under the tag that loads office.js.) 
    <script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js" type="text/javascript"></script>
    <script>
        Office.onReady((info) => {
            if (info.host === Office.HostType.Word) {
                console.log("In onReady!");
            }
        });</script>

The error about "exports" is caused by using the "export" keyword in a file that's not being processed in NodeJS. Your Home.ts (or more exactly the Home.js that's transpiled from it) is being run in an embedded browser in Word. The JavaScript runtime in this environment doesn't understand "export" (or the "exports" that it is transpiled into). 

In a project created with Yo Office, there is a file called webpack.config.js that (among other things), traces the chain of "export" and "import" statements and uses them to merge all the JavaScript module files into a single file, which itself doesn't have any "export" (or "exports") so it can run in a browser. The projects in Visual Studio don't have this built-in. If you are determined to stick with Visual Studio, you need to research tools that will bundle the transpiled JavaScript files. For example, [BundlerMimifier](https://marketplace.visualstudio.com/items?itemName=Failwyn.BundlerMinifier64).

**Comment by zjda** [comment]
I will switch to my Mac machine and use VS Code and Yomen for development.  

Thank you very much, Rick!
