### ISSUE TITLE
Outlook Add-In with SSO

### ISSUE THREAD

**Issue by vishalshitole** [OfficeDev/office-js-docs-pr#4192]
Hello, I am creating an Outlook Add-in task pane project using React framework that should support SSO. I referred the linked Microsoft article for SSO configuration, and one of the important step is registering the add-in with Microsoft Identity platform (AAD). https://learn.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet#register-the-add-in-with-microsoft-identity-platform

I have couple of questions regarding steps in this article.

In [Expose a web API](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet#expose-a-web-api) section of the article, it has been suggested to insert fully qualified domain name as part of Application ID URI format of the app registration. E.g. `api://<fully-qualified-domain-name>/<app-id>` 

Is this required? I tried testing my Outlook add-in (sideloaded) against my app registration having Application ID URI without domain name i.e. `api://<app-id>`, but it failed to get the access token at method OfficeRuntime.auth.getAccessToken(). In general, I have seen Application ID URIs without domain names.

What if I have multiple add-ins or add-in versions (dev, uat, prod) hosted in separate domain/subdomains? Do I then need to create separate app registration for each?

Please suggest the right approach in the context of Outlook Add-In with SSO.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93c00914-b10b-632d-83a9-31a92b480312
* Version Independent ID: 420a6dfe-d17e-1e32-f25b-e6a0daac2101
* Content: [Create an ASP.NET Office Add-in that uses single sign-on (SSO) - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet)
* Content Source: [docs/develop/create-sso-office-add-ins-aspnet.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/create-sso-office-add-ins-aspnet.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for raising these questions @vishalshitole.

@davidchesnut, could you please take look here and update the documentation as appropriate?

**Comment by vishalshitole** [comment]
@davidchesnut Any updates/suggestions on this?

**Comment by davidchesnut** [comment]
Hi @vishalshitole, 

Yes, the `api://<fully-qualified-domain-name>/<app-id>` format is required by Office as part of how it works with SSO. It also appears in the `<Resource>` section of the manifest which must match.

If you are working with a CI pipeline going through dev, test, staging, then I would recommend creating a separate manifest and app registration for each stage. Otherwise, with a single app registration/manifest you'd have to update it each time when you moved to a new stage (with different URI endpoints).

For multiple add-ins you can deploy them from one domain, or multiple subdomains under one domain. SSO in Office will work with either approach, However, I don't know if there may be security implications around keeping add-ins in one domain versus multiple. If you have further questions on security around domain management, I recommend reaching out to the [Microsoft identity team](https://learn.microsoft.com/azure/active-directory/develop/developer-support-help-options).

Hope this helps!
David
