### ISSUE TITLE
Sideloading from url disabled

### ISSUE THREAD

**Issue by cbishop-fv** [OfficeDev/office-js-docs-pr#4219]
With the recent changes we now need to go to https://outlook.office.com/mail/inclientstore this URL to sideload addins. As of today the from URL link is disabled. 

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/56599161/2adcf8d3-5dfe-4123-a222-c6cd19d1e646)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f364ae0-b7dd-edb3-b51b-8f6d0d99afbe
* Version Independent ID: 7dd1ce8f-16e7-88f8-f291-4afbe76baba7
* Content: [Sideload Outlook add-ins for testing - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=windows)
* Content Source: [docs/outlook/sideload-outlook-add-ins-for-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/sideload-outlook-add-ins-for-testing.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @cbishop-fv,

Thanks for raising this issue. @samantharamon, could you please look into clarifying this in the sideloading docs?

**Comment by samantharamon** [comment]
Thanks for reporting this, @cbishop-fv. We already have a [PR](https://github.com/OfficeDev/office-js-docs-pr/pull/4221) to update our documentation that's in review. Because the **Add from URL** option is no longer available, as a workaround, please open the URL in your preferred browser to download the manifest file, then use the **Add from File** option to sideload the add-in.

I've linked this issue to the PR, so it will automatically close once the PR is merged. However, if you need further assistance, please don't hesitate to reopen the issue or open a new one.

**Comment by cbishop-fv** [comment]
> Thanks for reporting this, @cbishop-fv. We already have a [PR](https://github.com/OfficeDev/office-js-docs-pr/pull/4221) to update our documentation that's in review. Because the **Add from URL** option is no longer available, as a workaround, please open the URL in your preferred browser to download the manifest file, then use the **Add from File** option to sideload the add-in.
> 
> I've linked this issue to the PR, so it will automatically close once the PR is merged. However, if you need further assistance, please don't hesitate to reopen the issue or open a new one.

Thank you for the update. This will make things very complicated for our test automation.

**Comment by samantharamon** [comment]
Thanks for your feedback, @cbishop-fv. I've passed it on to the team.
