### ISSUE TITLE
How to access a variable value from manifest.xml file in other js files

### ISSUE THREAD

**Issue by arshadansari10** [OfficeDev/office-js-docs-pr#4230]
Hi,  

I m developing a login api based project using excel addin api in js and I m using a globalUrl variable in a .js file which will change based upon the requirement. So during the build of the project is there any way through which I could declare my globalUrl value in manifest.xml file and accordingly access that value in other .js files like command.js or taskpane.js

**Comment by millerds** [comment]
You add-in can include any xml of json files you want as long as you deploy them with your code.  However, the manifest.xml file has a specific schema it has to follow in order to be interpreted by the hosts and I don't believe that include options for custom properties.  The manifest would fail validation if it had extra stuff in there.

**Comment by AlexJerabek** [comment]
Thanks for the response @millerds!

@Rick-Kirkham, are there documentation updates we should make with regards to this issue? If not, can we close this?

**Comment by Rick-Kirkham** [comment]
We can close this.
