### ISSUE TITLE
IMAP and POP3 support

### ISSUE THREAD

**Issue by usselite** [OfficeDev/office-js-docs-pr#4264]
Hi, 

Is there any update on the part if IMAP and POP3 will be supported in the future for the new Outlook add-ins platform?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9c9b375-5f5a-7a79-d654-e8ca9bcb23e5
* Version Independent ID: ee1bb242-ed4c-5b99-9e85-973f79cd4513
* Content: [Outlook add-in requirements - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/add-in-requirements)
* Content Source: [docs/outlook/add-in-requirements.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/add-in-requirements.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by alison-mk** [comment]
Hi @usselite, thanks for submitting! We use GitHub issues to report bugs with the product, and it looks like you are requesting a feature. For feature requests, we recommend submitting via [Microsoft 365 Developer Platform Ideas](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). We use Microsoft 365 Developer Platform Ideas to prioritize community requests for additions to the product. If the community upvotes your request, it's more likely to be added to the add-ins platform.

Since this isn't a bug, I will close this issue. Let me know if you have any questions!

Cheers, 
Alison
