### ISSUE TITLE
how can I publish my add-in on amazon AWS?

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js-docs-pr#4346]
OS: Canonical, Ubuntu, 22.04 LTS
CPU: t2.micro [ t2.micro ](https://aws.amazon.com/ec2/instance-types/t2/) with 1 GB Ram
Storage: 8 GiB
is that okay that space and storage for my add-in have can I publish it on this server

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a6812c3-fbf6-1a89-6305-8da71f83b5a3
* Version Independent ID: 614c2c5a-f3e7-fa28-6e4a-8ad68634c0d9
* Content: [Host an Office Add-in on Microsoft Azure - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/publish/host-an-office-add-in-on-microsoft-azure?view=word-js-preview)
* Content Source: [docs/publish/host-an-office-add-in-on-microsoft-azure.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/publish/host-an-office-add-in-on-microsoft-azure.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by junaid042** [comment]
@AlexJerabek can you please help me

**Comment by AlexJerabek** [comment]
Hi @junaid042,

Without much context about your add-in, I can't say what the hosting requirements are. If you've hosted a webservice through your AWS account before, you should be fine to do so with your add-in. 

Hosting on AWS is outside of my expertise. If there are issues with the Azure hosting instructions, I'm happy to help there.

I'm going to close this issue, since there's not an actionable step to take for the documentation. If you encounter errors with AWS, your best bet is to ask on Stack Overflow.
