### ISSUE TITLE
No get add-ins button in new look Outlook

### ISSUE THREAD

**Issue by caedmonm** [OfficeDev/office-js-docs-pr#4351]
There's no "get add-ins" button on the web or in the new look Windows desktop app, the link provided on this page in this section just reopens outlook as normal for me:

If you don't see the Get add-ins option in either the classic or simplified ribbon layouts, you must access the Add-Ins for Outlook dialog through https://aka.ms/olksideload.

**Comment by AlexJerabek** [comment]
Hi @caedmonm,

Thanks for reporting this. @samantharamon, could you please investigate?

**Comment by caedmonm** [comment]
I managed to get the button back by signing in with a business account rather than a personal one and then making it the primary account in Outlook. I don't know if that's by design (I do hope not).

**Comment by samantharamon** [comment]
Hi @caedmonm,

Thanks for the update. The entry points for accessing add-ins in Outlook have changed (see the [September Office Add-ins community call](https://youtu.be/XNykp7pLXgI?list=PLR9nK3mnD-OVExAWBr2QtS_5UmqUr7HL4&t=84) for more information). Currently, the only way to sideload an add-in is through <https://aka.ms/olksideload>. Note that it may take a few seconds for the add-in management dialog to appear from when the page loads.

The **Get add-ins** button appears when you sign into Outlook using your business account because your organization may still be using an older version or configuration of Outlook or Exchange that supports it.

**Comment by Rick-Kirkham** [comment]
[like]  Ricky Kirkham reacted to your message:
________________________________

**Comment by caedmonm** [comment]
Hi @samantharamon,

Thanks for following up on this, however I'm afraid that link doesn't work for me - no dialog appears, no matter how long I wait.

**Comment by samantharamon** [comment]
When you get a chance, could you try accessing <https://aka.ms/olksideload> from a different browser or clearing your current browser's cache? Let us know if that helps.

**Comment by samantharamon** [comment]
Thanks for your patience, @caedmonm.

After investigating this further, I found out that the team is still developing the add-in and app installation experience in the new Outlook on Windows client. So what you're seeing isn't the final expected experience. To help you track the progress of this feature, see [Outlook: New Outlook for Windows - New location for add-ins and integration with Teams search-based message extensions](https://www.microsoft.com/microsoft-365/roadmap?rtc=1&filters=&searchterms=184668).

Regarding the <https://aka.ms/olksideload> dialog, if it isn't working in your personal Outlook account, please try the following:
1. From an email, select the ellipsis (`...`) from the message action bar.
1. From the dropdown menu, select **Get Add-ins**.

![Get Add-ins option in the dropdown menu.](https://github.com/OfficeDev/office-js-docs-pr/assets/15154970/78741430-d3f2-4a52-9d81-daf7338414aa)
