### ISSUE TITLE
Spam-reporting add-in (preview) Outlook

### ISSUE THREAD

**Issue by Draki1893** [OfficeDev/office-js-docs-pr#4452]
[Enter feedback here]
Hello, I'm currently attempting to integrate the Spam Reporting add-in, but it's not loading after appearing in Outlook.

To preview the integrated spam-reporting feature, I joined the Microsoft 365 Insider program, selected the Beta Channel option to access the Office beta builds, and updated everything to the latest build.

Environment:
I've set up my environment and followed the Microsoft documentation on how to build apps with the Yeoman generator.

Configuration:
I meticulously followed all the steps outlined in the Microsoft documentation:

    Inserted the Version node from the documentation into my Manifest.
    Implemented the event handler by creating a new folder "spamreporting" and placing "spamremoving.js" inside it with the provided code.
    Adjusted the Registry setting for the "getAsFileAsync" method.
    Updated the commands HTML file.
    Updated the webpack config settings.

After completing the configuration, I sideloaded the add-in using "npm start."

The initial problem I encountered is that the button does not appear in the top ribbon but on top of the selected email. After clicking on it, I only get the default welcome screen, and the add-in doesn't function as expected—it's not reporting or performing any actions.

Do you have any ideas about what might be causing this issue? Should I modify the provided code from the Microsoft documentation, considering that I only copied it into my project, or could the problem lie elsewhere?

This is how it looks after I sideload my add-in

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/136761323/c5a7cbce-359f-44a2-98bf-e52c164aeb88)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 695f4ab9-5e6f-3b7a-04fe-3f7769958e98
* Version Independent ID: 695f4ab9-5e6f-3b7a-04fe-3f7769958e98
* Content: [Implement an integrated spam-reporting add-in (preview) - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/spam-reporting)
* Content Source: [docs/outlook/spam-reporting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/spam-reporting.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Unknowndotexe** [comment]
I followed the same steps as you, and I have a relatively similar issue. The difference is that in your case, it works, while in mine, it doesn't even appear. 

From your screenshot, it's not apparent that you applied the configurations specified because it's the default version (the one with "Show Taskpane" and "Perform an Action"). It works for me when it's generated by the Yeoman Generator with default code. 

What I have manually installed:
![image](https://github.com/OfficeDev/office-js-docs-pr/assets/79203900/b375a014-9fa2-47c7-acb9-ef19c21cc681)

Yeoman generator:
![image](https://github.com/OfficeDev/office-js-docs-pr/assets/79203900/271f64df-d450-4b36-aa9e-2844ec35cfa7)

I also had a lot of problems with: https://github.com/OfficeDev/generator-office/issues/486 but managed to find a solution
![image](https://github.com/OfficeDev/office-js-docs-pr/assets/79203900/a8f97eaa-ae1e-42a4-88e4-e6cc6c606b2b)

Working with default env: 
![image](https://github.com/OfficeDev/office-js-docs-pr/assets/79203900/f0e82c3c-0284-4468-8502-7edbd4f3c793)

Also the run button doesn't work. The only way to make a default working button and panel is with Visual Studio Code Teams Toolkit (this works for me)
![image](https://github.com/OfficeDev/office-js-docs-pr/assets/79203900/8a59c2e0-ae5b-47e4-8bea-e73d640087a7)

After applying all the instructions, it doesn't even show up anywhere. The question is whether the instructions are still valid and if this report button can still be implemented.

After Spam-reporting add-in instructions: 

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/79203900/4d3ea862-803b-46ec-9b42-50a1d1da0c50)

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/79203900/9fc629e1-f216-47da-aadb-7b8dbbc7085f)

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/79203900/4f3a7e68-dd01-44e4-b5b7-a27d2f6d0fca)

**Comment by AlexJerabek** [comment]
Thanks for reporting this issue. @samantharamon, could you please take a look?

**Comment by samantharamon** [comment]
@draki1893 @unknowndotexe Could you please provide the Outlook version you're on and verify that you're on the Beta channel (if possible, please include a screenshot)? To check this, in Outlook, select **File**, then choose **Office Account**. The version and channel appears in the About Outlook section.

**Comment by Draki1893** [comment]
Just checked my build, I had some issues with updating to beta channel but now its working with Registry Keys.
Thank you

**Comment by Suya677** [comment]
@Draki1893 

I have also same problem right now and following same step as you
did you solve this problem?
If you solved it then can I know how did you solve it?

Thank you
