### ISSUE TITLE
Missing JavaScript-only runtime transpiling rules

### ISSUE THREAD

**Issue by pavelstudeny** [OfficeDev/office-js-docs-pr#4496]
While the [runtime document](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtimes) provides info about notable JavaScript-only runtime features, an additional challenge is that the JavaScript-only runtime does not support the latest language standard and does not run modern JavaScript.

For engines with a well-known feature set, such as legacy Edge, this is normally solved by transpiling tools like Babel. However, the supported JavaScript-only runtime language standard is not documented. While it is possible to experimentally find transpiling rules and polyfills to run a specific code, any update to the code or dependencies may break the code evaluation or cause crashes.

## What is desired
A set of transpiling rules and polyfills is available.

## Environment
* Platform: PC desktop
* Host: Outlook
* Office version number: n/a
* Operating System: Windows

**Comment by Rick-Kirkham** [comment]
@pavelstudeny The official answer is that the JS-only runtime is a bit more up-to-date than I thought. It supports ECMAScript 2016. 

I found a more elaborate documentation at [Support for recent versons of JavaScript](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/support-ie-11?tabs=ie#support-for-recent-versions-of-javascript). I will update the article that you linked to with this information. When that change is published this issue will automatically be closed.

**Comment by dmitriikashin-outreach** [comment]
@Rick-Kirkham could you please let us know what kind of Engine Javascript-only Runtime uses?

According [to this Article](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtimes#javascript-only-runtime), it's from the React Native, which implies `Hermes` engine, or something on top of it, however you are pointing to the `Trident`.

For instance, JS Runtime code using `self`  OR  `globalThis` won't allow Add-in to load at all, which can be fixed by this [webpack setting ](https://webpack.js.org/configuration/output/#outputglobalobject). 

Hermes doesn't support Classes, but your engine does (I think I tried before and it didn't. but for sure does now).

Without knowing the exact engine, we can't evaluate our Javascript against it, and as result after running all the Babel transpilations we still weren't able to load the Add-in, and didn't get any specific error reasons (using event viewer to detect that Add-in wasn't loaded). 

cc @pavelstudeny

**Comment by Rick-Kirkham** [comment]
The engine is Chakra. But we plan to change to V8 at which point recent versions of JavaScript will be natively supported. I can't give you any estimate of when that change will occur.
