### ISSUE TITLE
Is there a way for us to declare fixed/permanent permissions for our app using Azure registration?

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js-docs-pr#4536]
Hello Team Microsoft,

I was looking into the docs again and realized that with NAA-SSO, the permissions can be dynamically requested and granted. However for our use, our set of permissions are actually fixed. Is there a way for us to declare our permissions in the azure portal so that the admin can consent to these fixed permissions on behalf of everyone in the organization?

Having a popup (asking to grant permissions) for each user is something we are trying to avoid. So this is why consenting from the Azure portal and revoking from the azure portal are mechanisms that we really would like to incorporate in our installation/setup flow.

Thank you very much.

**Comment by Rick-Kirkham** [comment]
You can do that on the **API permissions** blade in your add-in's app registration in the Azure portal. The link is grayed out in this screenshot because I wasn't logged in as an admin when I took it. 

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/9088056/8cc7f86f-28b7-4d7f-8f54-3b4dff796fbc)
