### ISSUE TITLE
Timeline for taking add-in custom-functions out of preview stage

### ISSUE THREAD

**Issue by jeffkt95** [OfficeDev/office-js-docs-pr#459]
Would it be possible to provide some indication of when add-ins will be out of the preview state and hence be available to users that are not part of the Office Insider program?

thank you,
Jeff

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94ad7803-d4f7-a700-7c7f-204cd8f34e4a
* Version Independent ID: 9c485bae-cab1-bdad-4c8e-baad2b12b22d
* Content: [Create custom functions in Excel (Preview)](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview)
* Content Source: [docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-overview.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@jeffkt95 thanks for your interest in Excel custom functions! We are unable to disclose an ETA for general availability (GA) of custom functions, but the product team is working to ship as soon as possible. I'd suggest that you keep an eye on Office Dev communication channels like the [Office 365 blog](https://developer.microsoft.com/en-us/office/blogs/) and the [Office Developer](https://twitter.com/officedev) Twitter account for announcements about custom functions GA in the days ahead.

**Comment by jeffkt95** [comment]
Thank you @kbrandl. It's been almost 6 months since my original query. Any update?

**Comment by kbrandl** [comment]
@jeffkt95 thanks for reaching out again! The product team's been working diligently on custom functions since your last inquiry, adding new functionality and working to stabilize all features as we continue to move towards general availability (GA). We're getting closer to having information regarding GA, but as of now there's still no info we can share publicly. Please stay tuned, it'll be publicized via the [Office 365 blog](https://developer.microsoft.com/en-us/office/blogs/) and the [Office Developer](https://twitter.com/officedev) Twitter account when we're ready to announce.
