### ISSUE TITLE
OneNote Add-in will work on OneNote desktop or not?

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js-docs-pr#4630]
In documentation only have detail to install OneNote Add-in on web how can we install on desktop is that possible or not?

**Comment by AlexJerabek** [comment]
Hi @junaid042, 

Office Add-ins (the web-based JavaScript add-ins) are only supported for OneNote on the web client ([source](https://learn.microsoft.com/en-us/javascript/api/requirement-sets?view=onenote-js-1.1#onenote). There is a [feature request for desktop support on the M365 Tech Community site](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/onenote-web-add-ins-in-outlook-rich-client/idi-p/3966688) that I would recommend you upvote.

I'm going to close this issue, since there's nothing actionable to do in the documentation.

**Comment by junaid042** [comment]
thanks you @AlexJerabek
