### ISSUE TITLE
OneNote: Details of supported HTML missing

### ISSUE THREAD

**Issue by jiri-matejka** [OfficeDev/office-js-docs-pr#499]
I am missing details of supported HTML when calling OneNote JS Api by functions such as `paragraph.insertHtmlAsSibling`. 

- what attributes are permitted in the HTML
- what CSS declarations are supported for `style` 
- if and how is HTML processed in the framework before patching the page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13002e9d-09c4-6ca4-860a-46b3349c4992
* Version Independent ID: 9946bc42-836f-18fb-8899-08ec3158a9f4
* Content: [Work with OneNote page content](https://docs.microsoft.com/en-us/office/dev/add-ins/onenote/onenote-add-ins-page-content)
* Content Source: [docs/onenote/onenote-add-ins-page-content.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/onenote/onenote-add-ins-page-content.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @jiri-matejka, 
I've reached out to the product team to get answers to your questions.

**Comment by AlexJerabek** [comment]
Hi @jiri-matejka,
The project team is still looking into what HTML and CSS attributes are supported (though they same they're the same as the rest of the Office JS HTML import logic).

As for what processing OneNote does to imported HTML, here's what one of the engineers said:
-	We may consolidate whitespace
-	We paste everything into 1 outline
-	We detect text direction

I'll keep this thread open while we're investigating the rest of your question. Thanks!

**Comment by kbrandl** [comment]
@jiri-matejka -- information about the HTML that the OneNote JavaScript API supports for creating and updating page content can be found here: https://docs.microsoft.com/en-us/office/dev/add-ins/onenote/onenote-add-ins-page-content#supported-html.

**Comment by jiri-matejka** [comment]
@kbrandl This is exactly the page what I reported in this issue as incomplete. 

For example, style attribute is processed somehow, which is not documented. 
`<table style="border:1px solid">...` ignores the style attribute and creates table without border, while`<table border="1">...` creates the border correctly. Both are correct in HTML so it is very difficult to find out how to form the HTML precisely.

**Comment by kbrandl** [comment]
@jiri-matejka thanks for the clarification and my apologies for the misunderstanding. @AlexJerabek is working with the product team to get more information for you on this topic.

**Comment by AlexJerabek** [comment]
Hi @jiri-matejka 

Sorry for the delay on this. I've been communicating with the OneNote product team about your issue. Their recommendation is that if specific formatting is a requirement, you'll need to use the structured objects exposed by the JavaScript API (like setting the [borderVisible property on the Table object](https://docs.microsoft.com/javascript/api/onenote/onenote.table?view=office-js#bordervisible)). This is because HTML does not exactly match the OneNote content model. There's also an issue of HTML/CSS standards constantly evolving and OneNote being periodically behind.

The team did say they welcome behavior suggestions. If you expect a particular behavior, they will treat the issue as a bug and investigate accordingly. Those issues would be filed on the [office-js repo](https://github.com/OfficeDev/office-js). 

I've updated the documentation with PR #676 to reflect the above guidance. That'd been checked in and will propagate to the live branch soon. I'll close this issue. Please comment on the thread if we should reopen it.

Thanks!
