### ISSUE TITLE
[Word]Document Events,How to handler it?

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js-docs-pr#500]
Document or ContentControl Saved,Changed events etc.

How to check it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52542c44-015a-746d-5d6f-c43f6e4e6774
* Version Independent ID: dfe8c9fb-4107-e19b-972a-c5a58eeb2646
* Content: [Work with Events using the Excel JavaScript API](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-events)
* Content Source: [docs/excel/excel-add-ins-events.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-events.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @hengchengfei, 
Word doesn't have those events at the Word-specific host level. At the Common API level, there are events for [Binding](https://docs.microsoft.com/en-us/javascript/api/office/office.binding?view=office-js#addhandlerasync-eventtype--handler--options--callback-) and [Document](https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=office-js#addhandlerasync-eventtype--handler--options--callback-). Does that work for your scenario?

**Comment by hengchengfei** [comment]
Like in VSTO.

[https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/7322108-need-events-for-office-web-versions-of-word-and-ex](url)

**Comment by AlexJerabek** [comment]
Hi @hengchengfei, 

Today's web add-in APIs do not have parity with VSTO. I suggest upvoting the linked UserVoice request and describing your scenario. That will help us prioritize Word events against the other feature requests.

Since this is a feature request and not a documentation error, I'm going to close the issue. Please reach out again if you have problems with the documentation. Thank you.
