### ISSUE TITLE
Docs improvement: Use $HOME or $(whoami)

### ISSUE THREAD

**Issue by yoursdearboy** [OfficeDev/office-js-docs-pr#609]
`/Users/&lt;username&gt;/Library/Containers/com.microsoft.Excel/Data/documents/wef` may be replaced with either:

* `~/Library/Containers/com.microsoft.Excel/Data/documents/wef`
* `$HOME/Library/Containers/com.microsoft.Excel/Data/documents/wef`
* `/Users/$(whoami)/Library/Containers/com.microsoft.Excel/Data/documents/wef`

Also, why not give `cp` command instead of using Finder.

Anyway, the docs are great. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589820d2-9925-dc5e-76a7-83921a569137
* Version Independent ID: ab8bde36-096f-81f3-f4d1-9b25fc69e6ee
* Content: [Sideload Office Add-ins on iPad and Mac for testing](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac)
* Content Source: [docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@yoursdearboy Thanks for the suggestions. We will give it some thought. In the meantime, I'm inclined to think that for reasons of brevity, and because many people reading this article will be add-in developers who mainly work in Windows and use a Mac _only_ when testing an add-in, we should have just one way of expressing the path and we should have them use Finder. Experienced Mac users will already know of the alternatives.
