### ISSUE TITLE
showNotification() function doesn't work

### ISSUE THREAD

**Issue by andrewkhramov** [OfficeDev/office-js-docs-pr#633]
Hello, everybody
I faced the issue that function showNotification() that is used in many examples in this article doesn't work. I can't find it in API as well. In task pane addin, on button click event, I execute the following method:
function saveData() {
        Excel.run(function (ctx) { 
            showNotification("Hi");
        });
}
In debugger I see exception: "showNotification" is not defined. What am I missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a714626a-058a-789e-6add-5e9dfb21fd1f
* Version Independent ID: 1b88a28c-fc36-4518-2808-7246f08d9753
* Content: [Use the Dialog API in your Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#closing-the-dialog-box)
* Content Source: [docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/dialog-api-in-office-add-ins.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@andrewkhramov thanks for reaching out about this problem. The `showNotification` function referenced within this article is similar to the `showUserName` function referenced in the article -- in that (by design) the implementation of this function is not explicitly shown in the article. You'll need to define a function called `showNotification` that displays the specified message in the task pane UI. The **OfficeDev/Office-Add-in-Dialog-API-Simple-Example** GitHub repo (specifically the [~/SimpleDialogSampleWeb/Taskpane.js](https://github.com/OfficeDev/Office-Add-in-Dialog-API-Simple-Example/blob/master/SimpleDialogSampleWeb/Taskpane.js) file in that project) provides an example of how the `showNotification` function might be implemented.

Thanks again for reaching out; we'll update the docs to clarify this.

**Comment by kbrandl** [comment]
We've addressed this issue with PR #636 and the doc update will be published later today.

**Comment by andrewkhramov** [comment]
Thank you very much for the answer.
