### ISSUE TITLE
How to change the Excel web add ins pane width

### ISSUE THREAD

**Issue by piyush18** [OfficeDev/office-js-docs-pr#739]
How to change the Excel web add ins pane width

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af787b7c-c69c-762b-59c8-53bda7a56024
* Version Independent ID: 805c4596-7aff-f93a-bf35-61c01d570742
* Content: [RequestedWidth element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/requestedwidth)
* Content Source: [docs/reference/manifest/requestedwidth.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/requestedwidth.md)
* Product: **non-product-specific**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@piyush18 it's not currently possible to specify the width of a task pane. If you haven't already done so, can you please upvote this [feature request](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/8892379-adjust-taskpane-width) on UserVoice? (The product team considers UserVoice requests when prioritizing future enhancements to Office JS.) And in the meantime, for information about task pane size on various platforms, see [Task panes in Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/task-pane-add-ins).

**Comment by abhijitrc** [comment]
Is there any further update on this request, i am also exploring the possibility of setting Excel web add-ins task pane width.

**Comment by skrabbe001** [comment]
> [@piyush18](https://github.com/piyush18) it's not currently possible to specify the width of a task pane. If you haven't already done so, can you please upvote this [feature request](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/8892379-adjust-taskpane-width) on UserVoice? (The product team considers UserVoice requests when prioritizing future enhancements to Office JS.)

1. The link to UserVoice doesn't work 

2. The documentation says we can specify the width
https://learn.microsoft.com/en-us/javascript/api/manifest/requestedwidth?view=common-js-preview

3. The namespace says we cant
```
The element 'DefaultSettings' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1' has invalid child element 'RequestedWidth'
```
4. Asking on stackoverflow does not change the status of the issue :D

5. The alternative methods of implementing addins are either not maintained, yeoman (vulnerabilities, deprecated dependencies), vsto (office 2010), and the like OR they are in alpha (the new development tools for office).

Regardless, microsofts documentation is so bad, that we have to write, compile and test code, because the specifics aren't described in the docs, ie RequestedWidth. And the docs are outright wrong, which causes developers to waste even more time. It's infuriating.

**Comment by Rick-Kirkham** [comment]
@abhijitrc and @skrabbe001 I'm sorry that you are having difficulties. 

1. UserVoice has been replaced by [M365 Developer Platform Ideas](https://techcommunity.microsoft.com/category/microsoft365/ideas/microsoft365developerplatform). Please search there to see if someone else has made this request and support it. If no one has created the idea, create one yourself and be sure to tag it **Office Add-ins Development** and **Office Add-ins UX**.
2. Note that in the article one of you linked to, [RequestedWidth](https://learn.microsoft.com/en-us/javascript/api/manifest/requestedwidth), the line "**Add-in type:** Content". This means that the `<RequestedWidth>` element is valid only in [_content_ add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/design/content-add-ins), not task pane add-ins or mail add-ins.
3. VSTO add-ins are a completely different kind of add-in from the web add-ins that this documentation is about. For some information about the differences, see [How are Office Add-ins different from COM and VSTO add-ins?](https://learn.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins?view=common-js-preview#how-are-office-add-ins-different-from-com-and-vsto-add-ins).
4. The Office Yeoman Generator (aka "Yo Office") is being maintained. But new vulnerabilities are discovered almost monthly, sometiems weekly. There is always a time lag between the discovery of the vulnerability and fixing it. The length of the lag depends on how easily the vulnerability can be fixed and the fix tested, and especially the availability of Microsoft staff who can investigate the vulnerability and fix it. 
5. Besides the yeoman generator, there are other tools for creating add-in projects that are past alpha; in fact, the following are all fully released:

   - [Office Add-in Development Kit](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/development-kit-overview?tabs=vscode)
   - [Teams Toolkit](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/teams-toolkit-overview)
   - [Visual Studio](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/develop-add-ins-visual-studio)

We will probably reduce the number of tools in the near future, but as of today, all of the above are available.

**Comment by skrabbe001** [comment]
Thank you. I didn't notice it was only for content add-ins. Weird to make that limitation.

The reason I need to adjust the with of the task pane, is because even Excel's own task pane (with a clean install of excel, and tested on several different machines, with different graphics hardware and drivers), when we resize it to make it wider, produces graphical artifacts, that makes the task pane unusable -  it causes support requests from the users - requests that we shouldn't have to deal with in the first place. It's an office bug, not a problem we can solve, or it will require far much work for us to solve. So I figured, that if we make it wider to start with, fewer users will need to resize it, and hence experience the graphical artifacts, and create bug reports that we know are inherent to the office product.

I've tested all of the frameworks/tools that you mention, except the teams toolkit, as it did not seem to include Excel, and I've used VSTO for many many years.

The Office Add-In development kit seems to be the "new" way, but it is a mess. I suggest at least one person from microsoft tries to install it and download and test one of the samples they supply, with an up to date tool chain (vscode, npm, node.js, pure javascript). It turns out the samples use deprecated packages that aren't maintained anymore. And the versioning of the packages that aren't deprecated are out of date, mismatched because of the deprecated packages, and most likely vulnerable. In my view this kit IS in alpha. And currently vscode only!

The Teams Toolkit can not develop add-ins for excel.

The VSTO that that comes with visual studio have limited templates, they even removed the template to create an app that isn't an extension or an add-in. New users will not know that you can add the interop references manually, nor that they are .net framework only.

Then we've got the VSTO nuget packages for the office interops, which is by some dude, that claims they are signed by microsoft, and supplied without any ... QA.

Yeoman, as we both agree, is not suitable for production.
