### ISSUE TITLE
Parameter eventResult.context is used in Excel.run function, what is the reason behind that?

### ISSUE THREAD

**Issue by andrewkhramov** [OfficeDev/office-js-docs-pr#745]
Dear Team!

My question is related to the article about removing event handlers, available by link 
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-events#remove-an-event-handler

In order to remove event listener in function Excel.run additional parameter eventResult.context is used, where eventResult is a global variable. What is the reason behind that and where I can find all parameters of the Excel.run?

Best regards,
Andrew Khramov

**Comment by AlexJerabek** [comment]
Hi @andrewkhramov, 

Thank you for your question. You can find the `Excel.run` reference section [here](https://docs.microsoft.com/javascript/api/excel?view=office-js#run-context--batch-), in our API reference documentation.

The [context parameter](https://docs.microsoft.com/javascript/api/office/officeextension.clientrequestcontext?view=office-js) acts as a intermediary between your add-in and the instance of Excel. You'll use the context object to synchronize the state of workbook components between your add-in and the actual Excel file. [This article](https://docs.microsoft.com/office/dev/add-ins/excel/excel-add-ins-core-concepts) explains that behavior in detail.

As for why `eventResult` is a global parameter, that's just what made the most sense for conveying the information in that sample. If it's still confusing after reading the linked topics, please reply and we'll take another look at it. You can also find more [event samples in our snippets repo](https://github.com/OfficeDev/office-js-snippets/tree/master/samples/excel/30-events). Those can be run through [Script Lab](https://docs.microsoft.com/office/dev/add-ins/excel/excel-add-ins-get-started-overview#explore-snippets-with-script-lab).

I'm going to close this issue, since there aren't any documentation gaps. Please reply to the thread if you disagree or if you think the information could be better presented or cross-linked.

**Comment by Rick-Kirkham** [comment]
@andrewkhramov Our reference for the `Excel.run` method is waaaaaay down at the bottom of this article: [Excel](https://docs.microsoft.com/en-us/javascript/api/excel?view=office-js).

To remove the handler, it is necessary that the `Excel.run` in the removal function is using the same **ClientRequestContext** object that it was using when the handler was registered.

**Comment by andrewkhramov** [comment]
Thanks @AlexJerabek, for the prompt answer! Could you please, specify what is happening with context if the following signature of the run method is used
run<T>(batch: (context: Excel.RequestContext) => Promise<T>): Promise<T>;
Will it be created from scratch?
Does it make sense to reuse context (by saving context in global variable and passing it to run method) in long running tasks, for example if js receives data from web server by portions and inserts it into worksheet?

**Comment by AlexJerabek** [comment]
Hi @andrewkhramov,

The context is created from scratch in that case. You're providing `run` a function to use with a context. If you pass one in, it'll use that. Otherwise, it creates a new one.

In general, we recommend using a new context each time. You'll rarely have to track objects between calls to `run`. You can make web calls from within `Excel.run`, so you only need to preserve the ranges within that single context. Even if the call is long-running, it sounds like you don't need user intervention with that single operation while it's running. 

If you really want to go into the details of the implementation, there's the book "[Building Office Add-ins using Office.js](https://leanpub.com/buildingofficeaddins/)" that'll give a much more in-depth explanation. I'd also recommend using [Stack Overflow](https://stackoverflow.com/questions/tagged/office-js) (with the "office-js" tag) as a resource. The community can help you decide whether your add-in needs to hold onto a single context or not.

**Comment by Rick-Kirkham** [comment]
@andrewkhramov @AlexJerabek I believe that you can only remove a handler like this with the same context object that was used when it was registered. I think that's why it needs to be global relative to both the registration and the removal functions.
