### ISSUE TITLE
More info about PowerPoint namespace (or examples)

### ISSUE THREAD

**Issue by Motta23** [OfficeDev/office-js-docs-pr#763]
The example about creating a new presentation by using the PowerPoint namespace (PowerPoint.createPresentation()) comes a bit out of the blue. Is there more info about other cool things you can do with PowerPoint.methodExample()? 

A reference to another doc would be really appreciated. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 207b73ed-7aeb-0cf3-34f8-9644af986017
* Version Independent ID: cdac769b-ee13-4d6a-118d-e52fc28d5e0d
* Content: [PowerPoint add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/powerpoint/powerpoint-add-ins)
* Content Source: [docs/powerpoint/powerpoint-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/powerpoint/powerpoint-add-ins.md)
* Product: **powerpoint**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @Motta23, 

Thanks for you interest in Office add-ins. Currently, `createPresentation` is the only PowerPoint-specific function in the JavaScript API. You can build add-ins to work with PowerPoint using the "[Common API](https://docs.microsoft.com/javascript/api/office?view=office-js)" ([as shown here](https://docs.microsoft.com/office/dev/add-ins/powerpoint/powerpoint-add-ins?view=office-js).)

We added that `createPresentation` method in response to [UserVoice](https://officespdev.uservoice.com/) submissions. If you request and upvote features there, it helps us prioritize new API sets.

Since there isn't more content in the PowerPoint namespace, I'm going to close the issue. If the Common API documentation doesn't help, please comment on this thread (or open a new one) so we can dig deeper. Thanks!
