### ISSUE TITLE
The color palette is out of date

### ISSUE THREAD

**Issue by fitojb** [OfficeDev/office-js-docs-pr#798]
The color palette given in this page doesn’t match the the refreshed one developed for Office 365’s iconography. https://fluentfabric.azurewebsites.net/#/color/shared

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5107ee19-7eee-237c-d18b-324f26cdece4
* Version Independent ID: 19466ab5-cb52-e947-e4a1-0757d6675d51
* Content: [Icon guidelines for Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/add-in-icons#feedback)
* Content Source: [docs/design/add-in-icons.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/add-in-icons.md)
* Product: **non-product-specific**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
This is actually by design. The icons in Add-in commands are not rendered with Fabric and deliberately use a different palette from the Fabric shared colors palette. I've added a note about this to the article and it should be published next Tuesday evening Pacific (USA) time zone. See [PR 799](https://github.com/OfficeDev/office-js-docs-pr/pull/799)

**Comment by DragoCubed** [comment]
Why are they different?

**Comment by Rick-Kirkham** [comment]
@DragoCubed The icons in Add-in Commands have to conform to the color scheme of the Office host application, which is an older design paradigm from Fabric.
