### ISSUE TITLE
[excel] when click cell,can enable or disable my ribbon button

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js-docs-pr#844]
hi

i have same question below:

1、when focus on F3 ,can it disable or enable the button of my CustomTab.

![image](https://user-images.githubusercontent.com/3963826/54807472-511c1880-4cb8-11e9-840d-9c90bd5950cc.png)

2、in CustomTab,i know a group only support 6 button.but when i add four button in report 

group. first button is large size .but other is samll size .can i set the four button are same size? 

thanks.

**Comment by Rick-Kirkham** [comment]
I'm afraid that there isn't a direct way to control the algorithm for button size that Office uses internally. I don't know the details of the algorithm, but it might be that the button label size matters. You might see what happens if you change the group label from "Report" to "Performance" and then remove "Performance" from all the button labels. 

Also, it would be great if you could raise this question on StackOverflow, where everyone in the community can see the answers that you get. The issues for this repo are intended only for reporting problems with the documentation.
