### ISSUE TITLE
More details required

### ISSUE THREAD

**Issue by 4tti** [OfficeDev/office-js-docs-pr#855]
Hello,

please prepare more detailed documentation as I am missing many information here (check for https://github.com/OfficeDev/Office-Add-in-Commands-Samples/blob/master/FAQ.md for some details). What I am currently missing is:
- requirements (see the Icons issue in the above link!) 
- how to debug (I am not able to find any useful information).
- tips and tricks or FAQ as in the link above.

Thank you!

**EDIT: for me the debug information is extremely important as currently I am facing issues with the commands and I am not able to identify where the issues are.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f18702b-d735-f775-62db-3ddc9187a11f
* Version Independent ID: 5fc534d7-db48-745e-d2bb-c19e6c2f65a9
* Content: [Add-in commands for Excel, Word, and PowerPoint - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/add-in-commands)
* Content Source: [docs/design/add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/add-in-commands.md)
* Product: **non-product-specific**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks for pointing this out. I'll merge this request into our existing work item to improve this article. Internal bug number is: 3187058.

**Comment by 4tti** [comment]
HI @Rick-Kirkham,

any update please? Could you at least give me some hints how to debug Commands? 
I have issue that any function I use for button does not work (or at least I am not able to find out if it works).

What I did:
- manifest seems correct (validation passed)
- reference to the DesktopFunctionFile seems fine, fiddler shows it is retrieved correctly
- Icon for the button shows
- for the ExecuteFunction I used multiple functions like
-- Show Custom Dialog (nothing happens)
-- Write some data into the sheet (nothing happens)
-- any used console.log does not show anywhere (I was expecting to see it in the Runtime log).
- I use the event.completed();
- I only see "RibbonTest is working on Test" at the bottom of Excel when clicked on "Test" button. "RibbonTest" is name of my addin.

Can you give me reference to some pure javascript sample? 
Thank you.

**Comment by Rick-Kirkham** [comment]
@4tti I've added the request to improve our documentation to our proposed work items. For immediate technical questions, such as this one, please create a question on StackOverflow and tag it `office-js`. This will ensure that the whole community sees the answers that you get.

**Comment by 4tti** [comment]
@Rick-Kirkham, see https://stackoverflow.com/questions/55518754/office-addins-how-to-get-commands-button-working
Any help is really appreciated.

**Comment by Rick-Kirkham** [comment]
See the Stack Overflow issue for more info. It turns out that you can debug Add-in Commands with Office Online. I'll add a note to that effect to the article.

**Comment by Rick-Kirkham** [comment]
Note should appear in the article by Tuesday night.

**Comment by 4tti** [comment]
@Rick-Kirkham Thank you.
But note that I still need info like:
- how to debug on desktop client
- why it does not work there.

**Comment by 4tti** [comment]
To be more clear: It did not help me at all to fix my issue with desktop version - it does not work and I don't understand why.

**Comment by Rick-Kirkham** [comment]
OK. But let's distinguish 3 things:
1. The need for this article about Add-in Commands to say how they can be debugged. 
2. The particular issue of your add-in commands working on Online but not working on desktop. 
3. How to debug on the desktop. 

I think that, thanks to your help, we have solved number 1. Since the issues of this repo are intended to track problems with the documentation, not technical questions, I think it is appropriate to close this issue. (We also have a work item to completely redo the Add-in command documentation and I've added to that a task to incorporate that FAQ you found.)

Number 2 is a technical problem ,as distinct from a problem with this article. Since the same code works on Office Online, this is probably a bug in desktop Office, so I think you should create an issue in the [office-js repo](https://github.com/OfficeDev/office-js/issues). It would be great if you can provide just enough code to reproduce the problem.

I'm not sure what to say about  number 3. All modern browsers are ECMAScript-compatible, so they process JavaScript the same way, with only some exceptions. So if you can debug on any platform, then when you get your code working, it **should** work the same on all platforms. So I don't think there should be a _general_ need to be able to debug on Online _and_ be able to debug on desktop (_and_ be able to debug on Office for Mac, etc.); although I can see why in your case you'd want to be able to debug in both, since you are getting different behavior.
