### ISSUE TITLE
Missing documentation: install manifest.xml in Office 365 Outlook without Exchange

### ISSUE THREAD

**Issue by fbernhard** [OfficeDev/office-js-docs-pr#881]
## Article URL

https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish

## Issue

The documentation does not explain how an Office 365 customer who uses Outlook to connect to G Suite or other email servers, not Exchange, can install an Outlook add-in manifest.xml.

Can you please clarify how these type of organizations can leverage Outlook Addins written with OfficeJS? Thanks!

**Comment by AlexJerabek** [comment]
Hi @fbernhard,
Thanks for suggesting this documentation enhancement. I'm assigning this to @ElizabethSamuel-MSFT to update the content.

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc: Can you provide any details here? Thanks.

**Comment by exextoc** [comment]
Today Outlook Add-ins are supported for Microsoft exchange accounts only, because require manifest XML file to be installed in the mailbox. Supporting non-exchange mailboxes is not a part of the product right now. We track Outlook add-in feature requests on our user-voice page. Please add your request there. Feature requests on user-voice are considered when we go through our planning process.

Looks like there's already a request for this here:
https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/10248942-allow-office-add-in-manifest-to-be-published-to-cl

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc: Thanks for your response.

@fbernhard: Thanks for raising this issue. It seems like exextoc has responded to your question. Please take a moment to vote for that feature in User Voice. I'll go ahead and close it now but let us know if it should be reopened.

Thanks.

**Comment by fbernhard** [comment]
Thanks all!
