### ISSUE TITLE
More clarity required on Office 2016 versions

### ISSUE THREAD

**Issue by rocketraman** [OfficeDev/office-js-docs-pr#935]
This page includes `Office 2016 or later for Windows (build 16.0.6769+)` in the section about supported platforms.

This requires some elaboration, as per my understanding only Office 2016 which comes as part of an Office 365 subscription actually supports this (see https://github.com/OfficeDev/office-js-docs-pr/issues/906).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f18702b-d735-f775-62db-3ddc9187a11f
* Version Independent ID: 5fc534d7-db48-745e-d2bb-c19e6c2f65a9
* Content: [Add-in commands for Excel, Word, and PowerPoint - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/add-in-commands#feedback)
* Content Source: [docs/design/add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/add-in-commands.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@rocketraman we've already submitted doc updates for this doc (and another) as part of PR #914, so you should see updated info rendered in the docs later this week. (Doc updates get published twice a week, and these updates are in the queue for the next publication.) I'm going to go ahead and resolve this issue now (since doc updates are already pending publication), but please feel free to comment again here if the updates that get published later this week don't fully resolve this issue. Thanks!

**Comment by rocketraman** [comment]
Thank you, I didn't notice those changes last time I looked at the pull request, but do see them now. Cheers.
