### ISSUE TITLE
Sideloaded add-ins on mac have to be re-added after each restart

### ISSUE THREAD

**Issue by misaunde** [OfficeDev/office-js-docs-pr#956]
Groing through the instructions on a mac to sideload a manifest (that already works as expected on pc), I notice that every time I close and re-open Excel my add-ins disappear. I have to go to the Insert ribbon, click on the my add-ins drop down menu, and re-select my developer add-in. Is this expected behavior?

On pc, if I add my custom ribbon manifest, it stays there for good, across restarts. Can this be achieved on a mac?

System details:
Excel 16.24 Office 365
Mac OS 10.14.4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589820d2-9925-dc5e-76a7-83921a569137
* Version Independent ID: ab8bde36-096f-81f3-f4d1-9b25fc69e6ee
* Content: [Sideload Office Add-ins on iPad and Mac for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac#feedback)
* Content Source: [docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @misaunde - Thanks for taking the time to read our docs and try out Office Add-ins! Sorry to hear you are having trouble with sideloading on Mac. I am not sure if this is a known issue or not, but I will check with folks over here and get back to you. I'd love to be able to give you an answer right away but as many engineers are very busy due to the upcoming //build conference this may get resolved after the weekend. Thanks for your patience!

**Comment by misaunde** [comment]
New Issue in office-js repo: https://github.com/OfficeDev/office-js/issues/507
